### ISSUE TITLE
Compare logbook to similar technologies

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/logbook#100]

**Comment by kakawait** [comment]
@whiskeysierra do you have idea about other comparable technology? Without comparing just for listing. Thus community (or just me) can try some other solutions and produces feedback

**Comment by whiskeysierra** [comment]
- http://hc.apache.org/httpcomponents-client-4.5.x/logging.html
- http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-configure-accesslogs
- https://tomcat.apache.org/tomcat-7.0-doc/config/filter.html#Request_Dumper_Filter
