### ISSUE TITLE
Allow filtering of objects and arrays inside the body

### ISSUE THREAD

**Issue by eusourafael** [zalando/logbook#1003]
Sometimes a request/response, can contain some properties that are not important for logging purposes.
There could be an option in the library to allow us to filter out those properties (objects or arrays).

## Detailed Description
There could be an option to specify a property name or even better a JSON Path to the properties that should be filtered out from the log.

## Context
We have a Splunk cluster that allows only 10k characters per log. Some of our integrations send us more that this, but we can omit some of the objects and arrays from the log, as they don't contain important information.
This can benefit other people with same issue, or even to reduce the amount of money spent storing logs, etc.

## Possible Implementation
Create a method inside `JsonBodyFilters` class to replace an entire array or entire object.

## Your Environment
* Version used: 2.6.2

**Comment by PascalSchumacher** [comment]
I think this issue should be closed. A JsonPathBodyFilter (see: https://github.com/zalando/logbook#jsonpath-body-filtering-experimental) was added in version `2.9.0`.

**Comment by eusourafael** [comment]
That is true. Great addition to the project. Thank you very much.
