### ISSUE TITLE
Body in response is filtered even though no related configuration is present

### ISSUE THREAD

**Issue by hasancansaral** [zalando/logbook#1011]
## Description
When the response status is 200 or 201, the body is logged with response. However, when there's a validation exception, body is not logged. This happens with no related configuration:

```
logbook.strategy=default
```

or with:

```
logbook.strategy=status-at-least
logbook.minimum-status=200
```

or with:

```
logbook.strategy=body-only-if-status-at-least
logbook.minimum-status=200
````

## Expected Behavior
The body to be logged with response.

## Actual Behavior
The log entry I get for response is:

```
{"origin":"local","type":"response","correlation":"995a243babde9c44","duration":192,"protocol":"HTTP/1.1","status":400}
```

## Possible Fix
I do not have one.

## Steps to Reproduce
Providing a minimal repository that reproduces the behavior below. It's pretty much zero configuration with Spring Boot starter dependency.

## Context
I'm trying to log response bodies for audit purposes.

## Your Environment

* Version used: `2.6.2`
* Spring Boot Version used: `2.4.5`
* Link to your project: [https://github.com/hasancansaral/logbook](https://github.com/hasancansaral/logbook)

**Comment by whiskeysierra** [comment]
Are you sure there is a body?

**Comment by hasancansaral** [comment]
I am sure. The sample project is fairly simple to get it up and a request with Posman shows the body.

**Comment by whiskeysierra** [comment]
My guess would be that the servlet error dispatch is used, which isn't supported.

**Comment by hasancansaral** [comment]
Yes, this was the case.
