### ISSUE TITLE
How can i disbale to log default params & can i rename "correlation" field

### ISSUE THREAD

**Issue by Zipfelchen** [zalando/logbook#1029]
Hi,

currently i just getting started with the lib in a spring-boot project. I just added the starter to pom and found a way to replace the value of my correlation via using a bean. nice... but, can i also overwrite the field name? i would like to call it tracking_id instead of correlation?

Secondly, is there a way to turn of default log fields like "origin" "type" etc?

This is how my log statment looks like currently:

`2021 - 05 - 11 13: 17: 09.954 TRACE 12532-- - [nio - 8082 - exec - 2]org.zalando.logbook.Logbook: {
    "origin": "remote",
    "type": "request",
    "correlation": "de1d86d9-f59e-4e11-b1bf-e5f4b569900c",
    "protocol": "HTTP/1.1",
    "remote": "0:0:0:0:0:0:0:1",
    "method": "POST",
    "uri": "http://localhost:8082/api/v1/dummy",
    "host": "localhost",
    "path": "/api/v1/dummy",
    "scheme": "http",
    "port": "8082",
    "headers": {
        "accept": ["*/*"],
        "accept-encoding": ["gzip, deflate, br"],
        "authorization": ["XXX"],
        "connection": ["keep-alive"],
        "content-length": ["27"],
        "content-type": ["application/json"],
        "host": ["localhost:8082"],
        "postman-token": ["750b3646-839c-4593-a50b-83d428942458"],
        "user-agent": ["PostmanRuntime/7.28.0"]
    },
    "body": {
        "name": "Dummy"
    }
}`

edit: found this in you docs:

`Logbook logbook = Logbook.builder()
    .condition(exclude(
        requestTo("/health"),
        requestTo("/admin/**"),
        contentType("application/octet-stream"),
        header("X-Secret", newHashSet("1", "true")::contains)))
    .build();`
    
seems like you can exclude a header "x-secret" via code..  since i am currently just using the spring properties file, is there a way as well or am i mistaken?

**Comment by PascalSchumacher** [comment]
You can obfuscate headers by setting a spring-boot property: 

`logbook.obfuscate.headers=[X-Secret]`

see: https://github.com/zalando/logbook#configuration

I think customization of fields logged and field names can be done by implementing and registering a custom  https://github.com/zalando/logbook/blob/main/logbook-api/src/main/java/org/zalando/logbook/Strategy.java

**Comment by whiskeysierra** [comment]
> I think customization of fields logged and field names can be done by implementing and registering a custom https://github.com/zalando/logbook/blob/main/logbook-api/src/main/java/org/zalando/logbook/Strategy.java

Not quite. If you want to re-use most of the json mechanics, then a custom `HttpLogFormatter` would be better. 

Take a look at the javadoc for `JsonHttpLogFormatter` to see how:

https://github.com/zalando/logbook/blob/846fd5382b8b1ffaaaee926b37a34dcd02287ace/logbook-json/src/main/java/org/zalando/logbook/json/JsonHttpLogFormatter.java#L18-L49

**Comment by whiskeysierra** [comment]
Within those `format` methods you get a map that contains e.g. `origin`, `type`, etc. You can modify that map to your liking, e.g. drop keys or rename them.

**Comment by whiskeysierra** [comment]
Feel free to re-open, if this doesn't suite your needs.

**Comment by Zipfelchen** [comment]
Thanks i will take a look next week !
