### ISSUE TITLE
Add Support For OpenFeign/Spring Cloud Openfeign

### ISSUE THREAD

**Issue by ankurpathak** [zalando/logbook#1048]
Please add support for OpenFeign/Spring Cloud Openfeign in Logbook. Here are more details:
https://github.com/OpenFeign/feign
https://github.com/spring-cloud/spring-cloud-openfeign

**Comment by whiskeysierra** [comment]
Logbook has support for most of the underlying clients that Feign supports. If you want, you can contribute a direct, native Feign module for Logbook. It would be highly appreciated!

**Comment by ankurpathak** [comment]
You cannot add Logbook to Open Feign by Apache Http Client or OKHttp. As it removes all interceptors of  Apache Http Client or OKHttp. It provide its own interceptor thing. So we should add support for it.

**Comment by whiskeysierra** [comment]
> As it removes all interceptors of Apache Http Client or OKHttp.

Wow, that's such a weird design decision.

> So we should add support for it.

Happy to accept contributions into this repo.

**Comment by sanyarnd** [comment]
https://github.com/zalando/logbook/pull/1154 implementation
