### ISSUE TITLE
Need help with bodyFilter

### ISSUE THREAD

**Issue by nidhis234** [zalando/logbook#1056]
Hi ! Although it is not an issue, just wondering if can be helped. I am trying to mask one of the field in my request with the name as Value, which works fine with below.
Properties is my set with that field's name.
However I have another field with same name in my Json request and it is masking that too. Is it possible if I can specify or mark somehow that which field needs to be masked?

  Logbook.builder().sink(new DefaultSink(new SplunkHttpLogFormatter(), new DefaultHttpLogWriter()))
        .bodyFilter(JsonBodyFilters.replaceJsonStringProperty(properties, "<masked>")

**Comment by nidhis234** [comment]
Also, I tried using JsonPath like below, which worked only for desired object. However this object is not present in my HttpResponse hence while displaying response logbook is throwing exception.

  .sink(new DefaultSink(new SplunkHttpLogFormatter(), new DefaultHttpLogWriter()))
        .bodyFilter(jsonPath("$.object.value").replace("*****"))
        .build();

**Comment by PascalSchumacher** [comment]
As far as I know there is not build in way to only filter the field some of the time (other than using JsonPath). Your can probably implement a custom filter to archive this.

JsonPath has to be configured to allow (not throw an exception) "missing" paths. I guess logbook does not do this, therefore you get an error.

**Comment by nidhis234** [comment]
> As far as I know there is not build in way to only filter the field some of the time (other than using JsonPath). Your can probably implement a custom filter to archive this.
> 
> JsonPath has to be configured to allow (not throw an exception) "missing" paths. I guess logbook does not do this, therefore you get an error.

Thank you, This helps!
