### ISSUE TITLE
Leased connections are not released

### ISSUE THREAD

**Issue by williamboman** [zalando/logbook#1059]
## Description

We're seeing Logbook causing leased connections not to be released. See the following graph, showing the measurement for the Apache client pool (when it recovers is when the instance is rebooted):

<img width="1361" alt="Screenshot 2021-06-09 at 23 14 50" src="https://user-images.githubusercontent.com/6705160/121430739-c26b4300-c978-11eb-9187-970ef73b8290.png">

## Expected Behavior
Leased connections to be released.

## Actual Behavior
Leased connections are not released. Eventually the instance runs out of available connections and becomes inoperative.

```
! org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
! at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:316)
! at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:282)
...
```

## Possible Fix
#1052

## Steps to Reproduce
Details in #1052.

## Context
We are unable to use Logbook due to this which is a bummer because we really like it. It has also caused some unexpected downtime for us.

## Your Environment
N/A

**Comment by PascalSchumacher** [comment]
I guess this can be closed because #1052 was merged.

**Comment by williamboman** [comment]
Yes!

**Comment by williamboman** [comment]
Would be awesome with a new release 😉

**Comment by whiskeysierra** [comment]
I'm preparing 2.10.0 right now. Should be available soon.
