### ISSUE TITLE
Only include zalando loogbook dependencies in logbook-bom

### ISSUE THREAD

**Issue by hackmann** [zalando/logbook#1086]
logbook-bom includes many test dependencies. See https://mvnrepository.com/artifact/org.zalando/logbook-bom/2.11.0

## Description
Because logbook-bom has a parent module and this parent has dependency management too, these dependencies are added to the project when importing dependencies using logbook-bom

## Expected Behavior
That logbook-bom does not inherit dependency management from any parent project

## Actual Behavior
That logbook-bom has logbook-parent as parent which includes dependencyManagement

## Steps to Reproduce
Run:

    mvn -Dartifact=org.zalando:logbook-bom:2.11.0 help:effective-pom 

## Context
I had to create my own logbook-bom without a parent

## Your Environment
* Version used: 2.9.0 and 2.11.0

**Comment by whiskeysierra** [comment]
Very good observation! Care to create a pull request?
