### ISSUE TITLE
How to log spring principal in webflux ?

### ISSUE THREAD

**Issue by mariusstaicu** [zalando/logbook#1098]
I would like to add principal info to all logs generated by logbook in the context of an authenticated user.
Is there any possibility of doing that ?

**Comment by whiskeysierra** [comment]
I can't answer the Spring aspect of that question. Once you show me how to access the current principal in Spring WebFlux, I can think about how to make that work with Logbook.

**Comment by mariusstaicu** [comment]
```
ReactiveSecurityContextHolder.getContext().map(ctx -> ctx.getAuthentication().getPrincipal())
```
however this only works when the call is made in the context of the WebFilterChain of the request, else it returns null

**Comment by mariusstaicu** [comment]
I can think of no way to make it work if I look into the current logbook implementation with netty channels

**Comment by whiskeysierra** [comment]
We don't have a dedicate Spring WebFlux module, since I was hoping a generic Netty module would be a) enough and b) suitable for non-Spring users. If that's not that case, we might need a Spring Webflux-specific module.

**Comment by mariusstaicu** [comment]
It might be the case, yes.

**Comment by ghostd** [comment]
Maybe the `Logbook#process` signature could accept an additionnal generic parameter (`Object` or `Map<String, ?>` or other) named "context" or whatever. Each module of would be free to fill it with some reliable data, eg:
* the webflux module could add the `ServerWebExchange` object (which would allow access to `ServerWebExchange#getAttributes`), and it could copy the context of the WebFilter Mono (where is stored the principal of Spring Security)
* the servlet module could add the servlet `RequestAttributes` into it
* i don't know the other modules

This new context would be exposed to the `Strategy`, the filters and the `Sink` (by adding a new parameter to each signature ? by wrapping in into the logbook `HttpRequest` object ?)

**Comment by kaivanshah14** [comment]
> I can think of no way to make it work if I look into the current logbook implementation with netty channels

Did you find a way to log the principal? The principal from ReactiveSecurityContextHolder will be returning a Mono Object it's not useful if we need the username/principal name. 

You can try working with Aspects but that will generate an asynchronous log.

**Comment by mariusstaicu** [comment]
ended up not needing a reactive solution anymore. However, I believe that a Mono object is to be expected in a reactive context, you wouldn't want to block
