### ISSUE TITLE
Un-finalize formatting class

### ISSUE THREAD

**Issue by kakawait** [zalando/logbook#114]
I'm trying to use *logbook*, especially `httpclient` integration. However I want to customize output, here I want to add authenticated user id to track call origin (at least from which user `httpclient` has been triggered).

I was thinking about extending `JsonHttpLogFormatter` to add context user. But `JsonHttpLogFormatter` is `final`... 

Moreover if you plan to remove `final` from `JsonHttpLogFormatter`, it can be cool that `JsonHttpLogFormatter` has a method that returning `Map<String, Object>` or `JsonNode` to easily extend content.

---

PS it may be have a better way to achieve what I want, I'm open to any other solution. **How to achieve it is not really important, only thing I want is to add some additional informations**

**Comment by whiskeysierra** [comment]
I agree that the JsonHttpLogFormatter is useful and that it feels natural to extend it. However, I'm not a big fan of inheritance, as it complicates class design and evolution in the long run. To provide a solution for your requirement, I'd suggest to introduce a new interface:

```java
public interface JsonHttpLogEnhancer {

    Map<String, Object> enhance(Precorrelation<HttpRequest> precorrelation, Map<String, Object> data);

    Map<String, Object> enhance(Correlation<HttpRequest, HttpResponse> correlation, Map<String, Object> data);

}

new JsonHttpLogFormatter(new JsonHttpLogEnhancer());
```

**Comment by kakawait** [comment]
I don't think that I will totally solve all my needs. I think I opened issue to quickly, let me time to rewrite it before developing anything.

**Comment by kakawait** [comment]
@whiskeysierra I analyzed deeply `Logbook` code and finally yes such `Enhancer` could be cool but what do you think about more *generic* `Enhancer` like:

```
public interface HttpLogEnhancer<T> {

    Map<String, Object> enhance(Precorrelation<HttpRequest> precorrelation, T data);

    Map<String, Object> enhance(Correlation<HttpRequest, HttpResponse> correlation, T data);

}
```

Thus we can override both `Json` and `Http` formatter.

---

I'm aware about *type erasure* but there is a workaround using intermediate class like `Spring` does, see http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/ParameterizedTypeReference.html

**Comment by whiskeysierra** [comment]
Do we need the same functionality for the HttpLogFormatter?

**Comment by kakawait** [comment]
In fact at the moment I write, I do not finally choose which formatter I wanted to use lol (I need to check with teammates), just that.

**Comment by whiskeysierra** [comment]
But in which way would you modify/extend the ouput that the HttpLogFormatter produces?

**Comment by kakawait** [comment]
Something like

```
Outgoing Request <XXXXXXXXXXXX>
```

(where `<XXXXXXXXXXXX>` is correlation id)

to 

```
Outgoing Request <XXXXXXXXXXX> from user <username>
```

or somewhere else 

(but I'm ok with you, `JSON` is better for such thing)

**Comment by whiskeysierra** [comment]
> Outgoing Request <XXXXXXXXXXX> from user <username>

That makes sense

**Comment by whiskeysierra** [comment]
I thought about it a little and, even though not necessarily better or cleaner, but once could do both of these things (appending to specific lines for http and adding/overwriting json properties) by wrapping the existing formatters and augmenting their return values:

```java
String[] lines = httpLogFormatter.format(..).split("\n");
lines[0] += " from user " + userName;
return Arrays.stream(lines).collect(joining("\n"));
```

For the json part this would require to parse the json, which is ugly, but doable, as a workaround.

**Comment by kakawait** [comment]
yes re-parsing json is not optimized but I will not use *logbook* on production (not activated)... So is totally acceptable.
