### ISSUE TITLE
Path filter doesn't take the end of the path expression into account

### ISSUE THREAD

**Issue by solo-yolo** [zalando/logbook#1140]
## Description

I might have misunderstood it and it is expected behavior, but here's the deal :)

In my application I have two different HTTP endpoints, similar to the following:
1. `/profile/<user-id>/info`
2. `/profile/summary`

For the first endpoint, I don't want Logbook to log specific user ids, so I've set up the path filter:
```
PathFilters.replace("/profile/{user-id}/info", "hidden")
```
This works well, but it unintentionally filters out the path of the second endpoint as well, logging it as `/profile/hidden/info`.

## Expected Behavior
I would expect a path filter with the expression `/a/{b}/c` does not match `/a/b` path since it doesn't end with `/c`.

## Actual Behavior
It actually matches, without regard to the end of the expression.

## Possible Fix
Didn't think about the fix yet.

## Steps to Reproduce
I've created a unit test that reproduces the issue, https://github.com/zalando/logbook/pull/1139.

## Your Environment
It is basically a spring-boot app, which exposes a few HTTP endpoints.
* Version used: 2.11.0
* Link to your project: it is a private repo.

**Comment by whiskeysierra** [comment]
@skjolber Thanks for the fix, much appreciated! 📣 
@solo-yolo Thank you for reporting this! 📣

**Comment by ssolohub** [comment]
Thanks for such a quick fix! 🥳
Any chance it gonna be released soon?

**Comment by solo-yolo** [comment]
Thanks for such a quick fix! 👍🏻
Any chances it gonna be released soon?
