### ISSUE TITLE
Provide Logbook TCK

### ISSUE THREAD

**Issue by sokomishalov** [zalando/logbook#1151]
Provide [TCK](https://en.wikipedia.org/wiki/Technology_Compatibility_Kit) for Logbook at `logbook-test` module.

## Detailed Description
While implementing various implementations it's quite a common case when you need to cover all functionality for logbook API. This requires writing a lot of boilerplate test code (i.e. [netty](https://github.com/zalando/logbook/blob/main/logbook-netty/src/test/java/org/zalando/logbook/netty/LogbookClientHandlerTest.java), [ktor](https://github.com/zalando/logbook/blob/main/logbook-ktor-client/src/test/kotlin/org/zalando/logbook/client/LogbookClientTest.kt), [okhttp](https://github.com/zalando/logbook/blob/main/logbook-okhttp/src/test/java/org/zalando/logbook/okhttp/LogbookInterceptorTest.java)). TCK would help to reduce the current codebase and let to write new modules easier.

## Context
It's not a must-have feature, but it would help to scale the codebase for new modules.

## Possible Implementation
Example: [reactive-streams-tck](https://github.com/reactive-streams/reactive-streams-jvm/tree/master/tck)

**Comment by whiskeysierra** [comment]
I've been thinking about this before, but it wasn't painful enough to me.
