### ISSUE TITLE
Log duration of response

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/logbook#116]

**Comment by lukasniemeier-zalando** [comment]
Please expand the description. What do you want to log? The time it takes from logging the request until logging the response? The time it takes sending out the response?

**Comment by whiskeysierra** [comment]
I'd say the duration between request and response. We could do this with scalyr by modifying the parser or logbook is doing it automatically.

**Comment by lukasniemeier-zalando** [comment]
Why not solve this via a `Filter` like this [one](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/MetricsFilter.java)?

**Comment by AlexanderYastrebov** [comment]
Timespan between request and response feels as natural as response status, body and headers

**Comment by lukasniemeier-zalando** [comment]
> Timespan between request and response feels as natural as response status, body and headers

Natural to what?

**Comment by AlexanderYastrebov** [comment]
@lukasniemeier-zalando Natural to log-starring eye

**Comment by lukasniemeier-zalando** [comment]
I assume that your log-starring eye wants to see the time that has been spend in any application code, not only the part spanning a correlation's life. As most guys are probably using *Logbook* as a filter, there might be other costly stuff going on before the *Logbook* filter that add to your applications response time.

That's why I argue for measuring the response time outside of Logbook. It has nothing to do with logging IMO.

**Comment by AlexanderYastrebov** [comment]
Ok. I got your point. Looks like this will log incorrect times in case of SecurityStrategy

**Comment by AlexanderYastrebov** [comment]
I would like to resurrect this one with the following points:
* for most of our applications we have logbook and usually it is the almost only thing that logs anything
* calculating duration in separate middleware and logging it separately will increase log size and will make it harder to correlate duration to original particular request. Doing so in logbook is natural and easy.
* the measured duration could be documented intentionally as not an exact request-response measure but log correlation time, nevertheless it allows user to find particular slow requests.

@lukasniemeier-zalando @whiskeysierra

**Comment by whiskeysierra** [comment]
Fine with me.
