### ISSUE TITLE
Dynamic path parameters replacing of PathFilters

### ISSUE THREAD

**Issue by ismail2ov** [zalando/logbook#1164]
t would be quite useful and consistent add a functional replacing interface to PathFilters, in the same mode that JsonPath filters. (Related to [#1127](https://github.com/zalando/logbook/issues/1127) )

I will create a PR to add this feature. 

## Context and Possible Implementation
We need to salt with SHA512 the path param value instead of fixed replacing.

```
List<PathFilter> pathFilters = new ArrayList<>();

pathFilters.add(DynamicPathFilter.replace("/profiles/{organization}/email/{email}/user", DigestUtils::sha512Hex));

Logbook logbook = Logbook.builder()
        .pathFilters(pathFilters)
        .build();
```

**Comment by atrujillofalcon** [comment]
Related with #1155 too
