### ISSUE TITLE
Logging DeferredResult Body

### ISSUE THREAD

**Issue by LeoBarykin** [zalando/logbook#1175]
I log Http Requests and Responses via implementing javax.servlet.Filter. I log responses with TeeOutputStream and it works fine in most cases.
The problem is that DeferredResult class is used. Since the request is completed in another thread, the response body is unreachable. I wonder if it is implemented in this library. If not. is it even possible?

## Context
I need to apply custom logic before logging http requests and responses. 

## Your Environment
Spring Boot 2.9 Java 11

**Comment by whiskeysierra** [comment]
Yes, what you describe is usually referred to as *async dispatch* and Logbook supports that:

https://github.com/zalando/logbook/blob/846fd5382b8b1ffaaaee926b37a34dcd02287ace/logbook-servlet/src/test/java/org/zalando/logbook/servlet/ExampleController.java#L36-L39

https://github.com/zalando/logbook/blob/846fd5382b8b1ffaaaee926b37a34dcd02287ace/logbook-servlet/src/test/java/org/zalando/logbook/servlet/AsyncDispatchTest.java#L125-L136

**Comment by whiskeysierra** [comment]
> I need to apply custom logic before logging http requests and responses.

If it's related to filtering (e.g. obfuscation) and formatting, then Logbook can be use here too.

**Comment by LeoBarykin** [comment]
@whiskeysierra Thank you for your answer! I will dive deeper into documentation and include it into my project.
