### ISSUE TITLE
Issues with setting log level

### ISSUE THREAD

**Issue by juyoungjung0326** [zalando/logbook#1183]
Hello, I am new to Java Spring Boot and Zalando Logbook and I am not sure if this is the place to post this. I am trying to change the log level of the logger to log at the DEBUG level. However, changing the log level in application.properties to logging.level.org.zalando.logbook: DEBUG the logs do not get recorded in my log file. I see that in the Logger section of the README it says the logger can be customized through:
Logbook logbook = Logbook.builder()
    .sink(new DefaultSink(
            new DefaultHttpLogFormatter(),
            new DefaultHttpLogWriter()
    ))
    .build();
but I am not sure where to go from there.
Is it possible to change the log level of the logger? If so, how would I be able to do this?

Thank you in advance!

**Comment by whiskeysierra** [comment]
You'd need to write your own version of `DefaultHttpLogWriter` which uses `isDebugEnabled()` and `debug(..)` respectively:

https://github.com/zalando/logbook/blob/846fd5382b8b1ffaaaee926b37a34dcd02287ace/logbook-core/src/main/java/org/zalando/logbook/DefaultHttpLogWriter.java#L14-L27

**Comment by juyoungjung0326** [comment]
I got it to work! Thank you so much for your help and fast response! :)
