### ISSUE TITLE
"logbook.write.max-body-size" not working when creating own BodyFilter that includes defaultValue()

### ISSUE THREAD

**Issue by kosi2801** [zalando/logbook#1202]
## Description
With using Spring autoconfiguration when a custom BodyFilter is created and the BodyFilters.defaultValue() is used in it, the configuration property "logbook.write.max-body-size" is not working anymore. 
This is somewhat unexpected, as there is no indication that the BodyFilters.truncate() is *not* a default filter. 
By reading the documentation it would be assumed that the truncation is always possible (ie. part of the defaultValue() filters).

## Expected Behavior
When a custom `@Bean BodyFilter bodyFilter()` is created and the BodyFilters.defaultValue() is part of the filters, the truncation functionality is applied.

## Actual Behavior
No truncation of the body content configured by the "logbook.write.max-body-size" property is applied.

## Possible Fix
No exact fix, but as a workaround I had to use:
```
@Autowired
LogbookAutoConfiguration autoConfiguration;

@Bean
public BodyFilter bodyFilter() {
    return merge(
            autoConfiguration.bodyFilter(), 
            replaceJsonStringProperty(singleton("secret"), "XXX"));
}
```

## Steps to Reproduce

1. Create SpringBoot app, create dummy endpoint
2. Create custom @Bean BodyFilter bodyFilter like in the documentation example 
```
@Bean
public BodyFilter bodyFilter() {
    return merge(
            defaultValue(), 
            replaceJsonStringProperty(singleton("secret"), "XXX"));
}
```
3. configure "logbook.write.max-body-size = 10"
4. send request to dummy endpoint with larger body content

## Context
I was trying to add custom filtering to the existing filters, suddenly the logfiles were swamped by large body logs.

## Your Environment

* Version used: 2.14.0
* SpringBoot Version: 2.0.3.RELEASE
* Java Version: 1.8

**Comment by kosi2801** [comment]
This issue is still present. If a better handling is not possible or feasible, maybe a mention in the documentation could indicate that this is an unexpected behavior? eg. at the documentation for "logbook.write.max-body-size" or the @Bean Bodyfilter.

**Comment by kasmarian** [comment]
This should be covered by https://github.com/zalando/logbook/pull/1592 and will be in the next release. Please re-open the issue if it's not fully addressed
