### ISSUE TITLE
logbook-spring-webflux：Unable to compact body, is it a JSON?

### ISSUE THREAD

**Issue by yiminyangguang520** [zalando/logbook#1220]
First add logbook-spring-webflux in spring cloud gateway，when access backend application A via gateway，It occur "Unable to compact body, is it a JSON?"
## Description

1、backend application A enable compression by "server.compression.enabled=true" in bootstrap.yml
2、access backend application A by gateway
3、It record response log in spring cloud gateway，but the response log is compressed，when parsing response log，It occur error "Unable to compact body, is it a JSON?"
## Expected Behavior

It won't report error
## Actual Behavior

"Unable to compact body, is it a JSON?"
## Possible Fix

decide if the response log is compressed

![image](https://user-images.githubusercontent.com/7455230/144746693-ea3eba82-5fba-424b-a207-06643e5c05da.png)

## Steps to Reproduce

1、backend application A enable compression by "server.compression.enabled=true" in bootstrap.yml
2、access backend application A by gateway
3、It record response log in spring cloud gateway，but the response log is compressed，when parsing response log，It occur error "Unable to compact body, is it a JSON?"

## Your Environment

* Version used:
spring cloud: 2020.0.3
spring boot : 2.5.4
logbook:  2.14.0

**Comment by kkrzeminski** [comment]
Hello there is a simple solution to this issue:

`
@Configuration
public class LogbookConfiguration {
    @Bean public Sink defaultSink(RequestResponseJsonFilter filter, HttpLogFormatter formatter, Set<MessageBodyDecoder> messageBodyDecoders) {
        Map<String, MessageBodyDecoder> messageBodyDecodersByEncodingType = messageBodyDecoders.stream()
                .collect(Collectors.toMap(MessageBodyDecoder::encodingType, identity()));

        return new PathFilterSink(new LogstashLogbackSink(formatter), filter) {
            @Override public void write(Correlation correlation, HttpRequest request, HttpResponse response) throws IOException {
                if (isContentEncodingGzip(response) && isJson(response.getContentType())) {
                    super.write(correlation, request, new DecodingHttpResponse(response, messageBodyDecodersByEncodingType));
                } else {
                    super.write(correlation, request, response);
                }
            }

            private boolean isContentEncodingGzip(HttpResponse response) {
                return Objects.equals(
                        HttpHeaderValues.GZIP.toString()
                        , response.getHeaders().getFirst(HttpHeaders.CONTENT_ENCODING));
            }
        };
    }

    @AllArgsConstructor private static class DecodingHttpResponse implements ForwardingHttpResponse {
        private final HttpResponse response;
        private final Map<String, MessageBodyDecoder> messageBodyDecodersByEncodingType;

        @Override public HttpResponse delegate() {
            return response;
        }

        @Override public byte[] getBody() throws IOException {
            return decodeBody(unwrapResponse(response).getBody());
        }

        @Override public String getBodyAsString() throws IOException {
            // TODO maybe/better use charset from response.getContentType ?
            return new String(getBody(), StandardCharsets.UTF_8);
        }

        private byte[] decodeBody(byte[] body) {
            MessageBodyDecoder decoder = messageBodyDecodersByEncodingType.get(HttpHeaderValues.GZIP.toString());
            return decoder.decode(body);
        }

        private HttpResponse unwrapResponse(HttpResponse response) {
            HttpResponse result = response;
            while (result instanceof ForwardingHttpResponse) {
                ForwardingHttpResponse forwardingHttpResponse = (ForwardingHttpResponse) result;
                result = forwardingHttpResponse.delegate();
            }
            return result;
        }
    }
`

**Comment by yiminyangguang520** [comment]
@kkrzeminski Ok, thanks for your replay, I will try it later

**Comment by sandra-markerud** [comment]
@kkrzeminski I wasn’t able to use your approach due to some dependency issues.
But shouldn’t there be an easier solution?
According to the documentation https://github.com/zalando/logbook#known-issues the logbook interceptor should be last, but using the spring webflux autoconfiguration there are no interceptors but only filters to configure

“The Logbook HTTP Client integration is handling gzip-compressed response entities incorrectly if the interceptor runs before a decompressing interceptor. Since logging compressed contents is not really helpful it's advised to register the logbook interceptor as the last interceptor in the chain.”

**Comment by ZivanHaripershad** [comment]
Hi there, is this issue being resolved?

**Comment by mklschreiber** [comment]
Any updates on the issue? I'm using Spring Boot 3.2.5 with Logbook 3.8.0. I'm returning in my Controller some GZIP encoded response which contains JSON. Postman and Swagger is able to decompress it but the Logbook library just displays the gzip content in the log with following error logs:

15:09:33.416 TRACE o.z.l.json.CompactingJsonBodyFilter      : Unable to compact body, is it a JSON?. Keep it as-is: `Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 2]`
15:09:33.416 TRACE o.z.l.json.JacksonJsonFieldBodyFilter    : Unable to filter body for fields [...], compacting result. `Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 2]`
15:09:33.417 TRACE org.zalando.logbook.Logbook              : Outgoing Response: b2fcda46a91d6282
