### ISSUE TITLE
Support for JDK HTTP server

### ISSUE THREAD

**Issue by phejl** [zalando/logbook#1255]
## Detailed Description
It would great to have support for JDK HTTP server. Available directly in JDK and good enough for simple tasks.
https://docs.oracle.com/javase/8/docs/jre/api/net/httpserver/spec/com/sun/net/httpserver/HttpServer.html

## Context
JDK server works great is lightweight and baked into the JDK. I think others might find it useful.

## Possible Implementation
New module supporting the server.

**Comment by kasmarian** [comment]
This is released in 2.15.0
