### ISSUE TITLE
Configuration logbook.format.style = json not work

### ISSUE THREAD

**Issue by bara666** [zalando/logbook#1263]
When try to configure json format style not work

## Description
I need to configure de json format, and see on documentation:

![image](https://user-images.githubusercontent.com/8573431/147826507-7070c6ba-4ecc-40c3-92c3-b924ce3b7850.png)

but default format is in "http" and when I change it to json not work. I have to expand configuration on Code and hardcode Formatter:

![image](https://user-images.githubusercontent.com/8573431/147826588-0e1f786a-818f-4020-8cfa-78d1e60ea277.png)

## Expected Behavior
logbook.format.style = json
LOG: {"origin":"remote","type":"request","correlation":"949835fdec08d0a9","protocol":"HTTP/1.1","remote":".....

## Actual Behavior
logbook.format.style = json
LOG: Outgoing Response: c76b760c9ca06370\nDuration: 231 ms\nHTTP/1.1 200 OK\nConnection: keep-alive\nContent-Length:.....

## Possible Fix
Probaly adding line 295 of my screenshot
![image](https://user-images.githubusercontent.com/8573431/147826757-5c4a668a-9f8c-4ff2-bc7a-fa843dc4fff7.png)

I think that is important to generate test cases:
- test/java/org/zalando/logbook/autoconfigure/FormatStyleJsonTest.java
- test/java/org/zalando/logbook/autoconfigure/FormatStyleDefaultTest.java

## Your Environment
* Version used: 2.14.0

**Comment by kasmarian** [comment]
@bara666 `json` is the default value at this point and should be used if you don't specify anything in `logbook.format.style`. I'll close the issue, but please feel free to re-open it, if you still have issues with it.
