### ISSUE TITLE
Add property to disable correlation

### ISSUE THREAD

**Issue by nhmarujo** [zalando/logbook#1265]
Provide a way to disable correlation, for cases where it is already provided in another way.

## Detailed Description
I would like to see a property (like `logbook.correlation.enabled` with default `true`) that would allow to disable the correlation step if needed. This might be useful if, for instance, one is using `Sleuth` which already provides correlation, making the correlation provided by logbook redundant and unnecessary.

**Comment by noway1979** [comment]
We also have Sleuth in place and tried quickly to simply override the CorrelationId bean to delegate to Tracer from sleuth: 


```java
  @Bean
  CorrelationId sleuthCorrelationId(Tracer tracer) {
    return new SleuthBackedCorrelationId(tracer);
  }

  @RequiredArgsConstructor
  private class SleuthBackedCorrelationId implements CorrelationId {

    private final Tracer tracer;

    @Override
    public String generate(HttpRequest request) {
      return tracer.currentSpan().context().spanIdString();
    }
  }
``` 
As a result; I at least get the same correlationId issued by sleuth showing in LogBook output: 

```,log
2023-05-23 22:46:43.554 TRACE [XXXX,b012666b5e73a838,b012666b5e73a838] 30580 --- [nio-8080-exec-2] org.zalando.logbook.Logbook              : {"origin":"remote","type":"request","correlation":"b012666b5e73a838","protocol":"HTTP/1.1","remote":"0:0:0:0:0:0:0:1","method":"POST","
```
Its not disabled but at least consistent.
Maybe helps...
