### ISSUE TITLE
GET request contains empty body property in json

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/logbook#127]
```
[org.zalando.logbook.Logbook] {"origin":"remote","type":"request","correlation":"46dde784-6488-48cc-a5a9-2f97e57052b0","protocol":"HTTP/1.1","remote":"XXX","method":"GET","uri":"XXX","headers":{"Accept":["application/json, application/*+json"],"Authorization":["XXX"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Content-Type":["application/json"],"host":["XXX"],"Pragma":["no-cache"],"singularityheader":["XXX"],"User-Agent":["Java/1.7.0_80"],"X-Forwarded-For":["XXX"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"]},"body":""}
```

Note `"body":""` - in case of absent body one would expect absence of `body` property instead of empty one.

**Comment by whiskeysierra** [comment]
HTTP makes no difference between *no body* and *empty body*, does it?

**Comment by tkrop** [comment]
No, but isn't the question how this should be best represented in logbook. Logfile inspection will rely on this, so it cannot be changed after release 1.0.0. I would vote to remove the body field, if it is empty, i.e. content length is 0.

**Comment by whiskeysierra** [comment]
My question was whether we can even differentiate between an empty body and a missing one. Just dropping the property from the object is easy, but an empty string is a nice indicator that it's actually empty. You can't query for non-existing properties (at least not in scalyr).

**Comment by tkrop** [comment]
My answer was No, there are just requests that have to have a message body and others that might have not. Bad for scalyr ..., :(

**Comment by whiskeysierra** [comment]
So the question is what's the better representation of an empty/absent body: An empty string or an absent property. I'd say depends on how you look at it.

**Comment by whiskeysierra** [comment]
I'll close this for now. An empty string is as good as a representation of a message without a body as an absent property would be. The things in favor of the empty string:

1. We have an empty string right now, so it's no effort to leave it like that
2. It makes it easier for tools to decide whether there was a body or not (`$httpBody == ""`)
