### ISSUE TITLE
How to get request info in bodyFilter

### ISSUE THREAD

**Issue by kangarooxin** [zalando/logbook#1296]
i want to process the body depends on request, how to get request info in bodyFilter.

JsonPath body filtering for example：

hide same field usually not global requirement.

hide field `a` on request path "/a"
hide field `b` on request path "/b"

**Comment by skjolber** [comment]
@kangarooxin did you try the `RequestFilter`? There is however no corresponding path method in the `ResponseFilter`'s `HttpResponse` input.
