### ISSUE TITLE
Passing APM trace information into log contexts

### ISSUE THREAD

**Issue by peterbecker** [zalando/logbook#1325]
We are trying to use Logbook for logging outbound requests using the Netty HTTP client in the context of a Spring Boot application, which is monitored using APM tooling (to be exact: Azure Application Insights). This means we look at log entries in the context of the APM traces.

The problem we experience is that the logging that happens from Logbook is on a separate thread from the application threads, and thus does not provide the necessary key value pairs on the [MDC](https://www.slf4j.org/api/org/slf4j/MDC.html) that would tie the log entries against the traces. That means we can't access the Logbook logging from the APM tooling at all, which is our normal (and usually only) mode of access. We can see them in the raw logs, but it is not practical to correlate those with the trace context.

What we would need is some way of passing key value pairs from the MDC of the original thread that created the request to the MDC when the Logbook logging happens. I was not able to see such a feature and given the use of `final` on many classes it seems hard to even come up with a dirty solution to this.

**Comment by whiskeysierra** [comment]
> The problem we experience is that the logging that happens from Logbook is on a separate thread from the application threads

Why is that?

**Comment by peterbecker** [comment]
> Why is that?

Good question. I had quietly assumed it's since Logbook was doing the logging in some background thread, but your question made me think a bit more and check a bit closer.

It is because we are using Spring Webflux. Not a Logbook problem, sorry about the noise.
