### ISSUE TITLE
Gradle use documentation

### ISSUE THREAD

**Issue by atrujillofalcon** [zalando/logbook#1328]
Add Gradle use documentation

## Detailed Description
With currently README.doc, is not easy to figure out how integrate Logbook into a project with Gradle as build tool; especially the use of logbook-bom in Gradle.

**Comment by whiskeysierra** [comment]
There is nothing special about logbook's artifacts in comparison to any other OSS Java project. Spring, Jackson, Jersey, Netty, etc. all have BOMs as well. You should also note that the use of BOMs is completely optional. You can directly depend on the modules that you need and specify their version explicitly.

**Comment by atrujillofalcon** [comment]
I only ask to put into README this fragment for example:

```
dependencies {
   implementation 'org.zalando:logbook-spring-boot-starter'
}

dependencyManagement {
    imports {
        mavenBom "org.zalando:logbook-bom:${logbookVersion}"
    }
}
```

In the same way as you have a Maven installation example.

**Comment by whiskeysierra** [comment]
Great! Why didn't you say so? Happy to get a pull request for this.
