### ISSUE TITLE
Log level in test with @DynamicPropertySource

### ISSUE THREAD

**Issue by fr3sh** [zalando/logbook#1339]
When you try to set up property of logging.level.org.zalando.logbook in tests trough @DynamicPropertySource logbook will not work. Only manual setting in application.yaml is handling logbook properly.
    
@DynamicPropertySource
static void props(DynamicPropertyRegistry reg) {
reg.add("logging.level.org.zalando.logbook", ()-> "TRACE");
}

**Comment by whiskeysierra** [comment]
The `logging.level.*` property doesn't belong to logbook but Spring directly.

If you want to change log levels at runtime, they offer eg a management bean/endpoint, iirc.
