### ISSUE TITLE
Add request/response logging to Spring's RestTemplate

### ISSUE THREAD

**Issue by jasonchaffee** [zalando/logbook#134]
It would be nice if this was being logged as well and added to the spring-boot module

**Comment by whiskeysierra** [comment]
That would require to provide a single RestTemplate in our AutoConfiguration which comes with a lot of hidden dependencies/requirements that we didn't feel comfortable taking, e.g.:

- which http client technology to choose and how to configure it
- which base url to use, if any
- which http message converters to choose and how to configure it

All of those things highly depend on the needs of individual applications. Nothing that we can decide upfront, especially not in this project. So we came up with a different route:

If you need client-side request/response logging we suggest to use Apache's HTTP Client, for which we in fact do have a logbook integration (check the readme). This should get you going 90%+ of the way.

In addition we prefer to have isolated RestTemplates per API/Service that we're talking to. For this we developed [*Put it to REST!*](https://github.com/zalando-incubator/put-it-to-rest). It connects several of our open source libraries into one easy-to-use library that generates completely wired RestTemplates baed on a few lines of configuration.

**Comment by jasonchaffee** [comment]
Actually, it wouldn't.  

First, you don't have to have it autoconfigured.  

Or, you created a named bean for the RestTemplate that is autoconfigured for the logging with an interceptor and if users wanted to customize it themselves they could inject that named bean and modify it in their own configuration.   You do not need to specify the client technology or the base url to create a RestTemplate.

As for implementation, you could simply provide log interceptors that could be added to the RestTemplate.  It could be a ClientHttpRequestInterceptor that uses logbook and this could be added to any and all RestTemplates regardless of client technology and then the logging would be uniform with RestController logging.

**Comment by nhomble** [comment]
Hey @whiskeysierra, I can create another ticket if you prefer, but I agree with @jasonchaffee here. 

If you are open to supporting another module for spring implementations, I was able to write my own implementation of `ClientHttpRequestInterceptor` that is composed of `LogbookHttpRequestInterceptor` and `LogbookHttpResponseInterceptor` and just adapted the spring interfaces into apache. 

To your point about unique `RestTemplate`'s this property can still be held. The autoconfiguration would just create the interceptor bean and then users can just autowire the interceptor + `RestTemplateBuilder` and construct a unique `RestTemplate` as needed.

**Comment by whiskeysierra** [comment]
I'd be OK with an interceptor approach. Pull requests are welcome.

**Comment by nhomble** [comment]
Awesome, raised #917

**Comment by kyle18th** [comment]
@nhomble Thanks, i need this feature. Now the RestTemplate I use uses OkHttp to send requests, and I added logbook to OkHttpClient. But I think it’s a better way to use `ClientHttpRequestInterceptor`.
@whiskeysierra When will it be released? I can’t wait to use this feature!

**Comment by whiskeysierra** [comment]
@kyle18th @nhomble I merged #917.

I'm releasing 2.5.0 as we speak.

@nhomble 📣 🎉 Thank your for your contributions. Highly appreciated!
