### ISSUE TITLE
Not able to write logs into File

### ISSUE THREAD

**Issue by kspkuldeep** [zalando/logbook#1348]
I am using spring boot with logs to capature request/response.
I am able to genereate logs into console but not able to log the same into files. Does any one know how to enable FileAppender and write logs over there.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Link to your project:

**Comment by whiskeysierra** [comment]
That has nothing to do with Logbook, but is specific to your logging solution of choice (log4j2, logback, etc.).
