### ISSUE TITLE
[httpclient] RemoteResponse.withBody() breaks gzip decompression

### ISSUE THREAD

**Issue by BGehrels** [zalando/logbook#135]
`RemoteResponse.withBody()` replaces `response.getEntity()` with a newly constructed `ByteArrayEntity`. It does so by extracting the original entities content (`InputStream`), transforming it to a `byte[]` and then constructing the new `ByteArrayEntity` from it.

Sadly, the `contentStream` is not the only piece of data present in an `AbstractHttpEntity`: It also contains a `contentEncoding` field, which is lost when during copying.

The `contentEncoding` field is used by httpclient to determine if it must decompress the content. As a result, if you put the logbook interceptor as first interceptor in the chain, gziped requests will not be unziped any more.

**Comment by whiskeysierra** [comment]
Do you have control over the ordering of the interceptors? I'd put the logbook interceptor at the last place (or at least after gzip), assuming we're talking about response interceptors here.

**Comment by BGehrels** [comment]
Is probably a good idea anyway, because otherwise we will log compressed bodies. Yes, just tried it and it works as a workaround.

**Comment by whiskeysierra** [comment]
> because otherwise we will log compressed bodies

Exactly!

I'll adjust the readme and clarify it in the *Known issues* secion.

**Comment by whiskeysierra** [comment]
@BGehrels Would be willing to share a simple code snippet before and after your change here?

**Comment by whiskeysierra** [comment]
Thanks for the snippets.

> Is there a good reason not to include the following in the RemoteResponse?

No, there isn't. If you want you can create a PR, otherwise I'll do it.

**Comment by whiskeysierra** [comment]
@BGehrels Fixed in [1.0.1](https://github.com/zalando/logbook/releases/tag/1.0.1), thanks for the pull request :+1:
