### ISSUE TITLE
Questions: Possible to ignore Outgoing response bases on HTTP status code ?

### ISSUE THREAD

**Issue by sherry-ummen** [zalando/logbook#1355]
Hi,

I wonder if it's possible to ignore printing those "Outgoing response" trace logs for the cases which are not say 500 or 400. ?

**Comment by whiskeysierra** [comment]
Yes, you need to provide a different strategy. Check whether any of the
built-in ones are sufficient. If not, implementing a custom one should be
easy as well.

https://github.com/zalando/logbook#strategy

**Comment by sherry-ummen** [comment]
Hey, thank you for the quick response. That worked very well 👍
