### ISSUE TITLE
can logbook log custom Filter log

### ISSUE THREAD

**Issue by ethfun** [zalando/logbook#1358]
i created an authentication Filter for validate user info, if user validate pass, then go to Spring Controller, otherwise return directly from custom Filter.

i had set Filter priority, but it did't work.

how can i set logbook log all request into custom Filter, but return directly.?

**Comment by whiskeysierra** [comment]
Did you take a look at https://github.com/zalando/logbook#security?

**Comment by ethfun** [comment]
I solved it by disabled add logbookFilter by springboot autoconfig

manual add logbookFilter  in filter config, set logbookFilter priority = Ordered.HIGHEST_PRECEDENCE,  it worked 

filter.enabled: false

```Java
    @Bean
    FilterRegistrationBean logbookFilter() {
        LogbookFilter filter = new LogbookFilter(logbook);
        final FilterRegistrationBean registration = new FilterRegistrationBean(filter);
        registration.setName("logbookFilter");
        registration.setDispatcherTypes(REQUEST, ASYNC);
        registration.setOrder(Ordered.HIGHEST_PRECEDENCE);
        return registration;
    }

```
