### ISSUE TITLE
NPE at FeignLogbookLogger.java method logAndRebufferResponse if response body is empty

### ISSUE THREAD

**Issue by hgabor83** [zalando/logbook#1360]
## Description
If I got a response from feign client server, like 401 unauthorized with empty body, the logAndRebufferResponse throws an NPE here:
response.body().asInputStream()

## Expected Behavior
It should handle if there is empty body and skip the body checking part

## Actual Behavior
It always want to process body even if it is null

## Possible Fix
Check first if body is null, something like this:
byte[] body = response.body()!=null? ByteStreams.toByteArray(response.body().asInputStream()) : null;

## Steps to Reproduce
Have a response with empty body

## Context
N/A

## Your Environment
Spring Boot project

**Comment by kasmarian** [comment]
This is released in 2.15.0
