### ISSUE TITLE
Spring auto configuration failed when the container has multiple ObjectMapper beans

### ISSUE THREAD

**Issue by dai0304** [zalando/logbook#138]
> Parameter 0 of method jsonFormatter in org.zalando.logbook.spring.LogbookAutoConfiguration required a single bean, but 2 were found:

Similar issue: https://github.com/spring-projects/spring-boot/issues/6529

Usually, we can avoid error to specify `@Primary` annotation to one of ObjectMapper bean.  But how can we do when we want to use other ObjectMapper for each auto configurations?

**Comment by whiskeysierra** [comment]
> for each auto configurations

Which auto configuration**s** are yo referring to? Do you want a special `ObjectMapper` just for the logging?

**Comment by dai0304** [comment]
Yes, our projects register multiple ObjectMapper beans for each role.
For http request / response body, for denormalized data on database, for event messaging, and so on.
Each ObjectMapper has different configuration.  So we want define new ObjectMapper bean for logbook.

**Comment by whiskeysierra** [comment]
Ok, got it, fundamentally I think it's purely a Spring issue and not really related to Logbook. Having said that, the easiest way that I see to resolve your issue is to define the following bean yourself:

```java
@Bean
public HttpLogFormatter jsonFormatter(@Qualifier("special") final ObjectMapper mapper) {
    return new JsonHttpLogFormatter(mapper);
}
```

**Comment by dai0304** [comment]
Thank you, my issue is resolved! 😉
