### ISSUE TITLE
Support for Spring Boot 3

### ISSUE THREAD

**Issue by joshlong** [zalando/logbook#1382]
Hi, Spring Boot 3 is here. At a minimum you'd need to add a file called AutoConfiguration.imports to make your Boot 2 auto configuration work. There's also the new AOT engine supporting GraalVM. I'd be happy to answer questions and help if this would be interesting 

## Your Environment

* Version used:
* Link to your project:

**Comment by nhmarujo** [comment]
Hi @joshlong . I think that is already being addressed [here](https://github.com/zalando/logbook/issues/1344) 🙂

**Comment by Kinmarui** [comment]
@nhmarujo maybe it's worth changing changelog, now its a bit misleading suggesting that in [2.15.0](https://github.com/zalando/logbook/tree/2.15.0) we got Support for Spring Boot 3 where it is still in development
![image](https://user-images.githubusercontent.com/3742151/225601776-d509e3f7-fa11-427e-87c1-62d535654366.png)
