### ISSUE TITLE
How to implement Custom Formatter?

### ISSUE THREAD

**Issue by kaltindas** [zalando/logbook#140]
How can i implement my own JSON Log Formatter? I can't extend JsonHttpLogFormatter, cause it's final class. I would override some methods and add some properties to log..

**Comment by whiskeysierra** [comment]
`JsonHttpLogFormatter` was designed with composition in mind. It has public `prepare` methods that you can use:

```java
public class CustomsFormatter implements HttpLogFormatter {

    private final JsonHttpLogFormatter delegate;

    public CustomsFormatter(final ObjectMapper mapper) {
        this.delegate = new JsonHttpLogFormatter(mapper);
    }

    @Override
    public String format(final Precorrelation<HttpRequest> precorrelation) throws IOException {
        Map<String, Object> request = delegate.prepare(precorrelation);
        // TODO modify request here
        return delegate.format(request);
    }

    @Override
    public String format(final Correlation<HttpRequest, HttpResponse> correlation) throws IOException {
        Map<String, Object> response = delegate.prepare(correlation);
        // TODO modify response here
        return delegate.format(response);
    }

}
```

See also #114

**Comment by kaltindas** [comment]
thank you.. worked like a charm .. thank you for this awesome library 👍

**Comment by AlexanderYastrebov** [comment]
@whiskeysierra Could your response be added as paragraph in README?

**Comment by whiskeysierra** [comment]
@AlexanderYastrebov I think it's too big as a whole for the README, but I could imagine adding it as a javadoc comment to the class and have a single sentence with a link in the README.

**Comment by whiskeysierra** [comment]
@kaltindas Thanks for the issue and the compliment! :heart:
