### ISSUE TITLE
Unable to exclude logbook-httpclient from Spring Boot starter

### ISSUE THREAD

**Issue by Infeligo** [zalando/logbook#141]
I wanted to have Logbook auto-configured, but without `logbook-httpclient`, because I have no use for it and it also brings Apache HttpClient dependency. I expected the following to work:

```
compile("org.zalando:logbook-spring-boot-starter:1.1.0") {
    exclude group: "org.zalando", module: "logbook-httpclient"
}
```

However, `LogbookAutoConfiguration` complained that the `LogbookHttpRequestInterceptor` class was missing. I think that it should have `@ConditionalOnClass` check becuase this is how other Spring starters work. For example, with Spring Cloud Starter Feign, I can exclude Hystrix, Ribbon and Archaius and auto-configuration guesses that my intention is to create pure Feign clients:

```
compile("org.springframework.cloud:spring-cloud-starter-feign:1.2.3.RELEASE") {
    exclude group: "io.github.openfeign", module: "feign-hystrix"
    exclude group: "org.springframework.cloud", module: "spring-cloud-starter-ribbon"
    exclude group: "org.springframework.cloud", module: "spring-cloud-starter-archaius"
}
```

**Comment by whiskeysierra** [comment]
Thanks for raising this issue. The current version of our auto configuration was not designed in a way to partially exclude optional dependencies. For that we need split it up into smaller configuration classes that are included with `@Import`. While we're at it this should not only work for the Apache HttpClient but also other dependencies, where it makes sense.

**Comment by whiskeysierra** [comment]
@Infeligo I created a PR #144. Could you try this locally to see if it works? It's hard to verify in a unit test.

**Comment by Infeligo** [comment]
I tried it exactly the same way as I have described in the issue (i.e. excluding `logbook-httpclient`) and it fails when there is Apache HttpClient on the classpath (works otherwise). I think that you should also have to add `@ConditionalOnClass` check for one of `logbook-httpclient` module classes.

**Comment by whiskeysierra** [comment]
@Infeligo Sorry for taking so long. I updated the PR and incorporated your suggestions. Can you take another look if it now fixes your problem?

**Comment by Infeligo** [comment]
I tried your updated PR and it works. I even created [a small project](https://github.com/Infeligo/logbook-spring-boot-demo) on GitHub to test that.

**Comment by whiskeysierra** [comment]
Good to hear. I'll release a new version.

**Comment by whiskeysierra** [comment]
@Infeligo I deployed 1.1.1 to central
