### ISSUE TITLE
There is no Content-Type header in response with async requests

### ISSUE THREAD

**Issue by iribaar** [zalando/logbook#143]
I have a spring controller that is defined like this:

@GetMapping(path = "somePath" produces = MediaType.APPLICATION_JSON_VALUE)
public ListenableFuture<SomeClass> retrieveSomething() {
    ...
}

Without logbook it returns the content type header, with logbook autoconfiguration the header is missing in response.

I haven't done any debuging on this issue. So i can not provide more details. Sorry.

**Comment by whiskeysierra** [comment]
@iribaar Thanks for reporting this. Would you be willing to create a small test case that exposes this issue?

**Comment by iribaar** [comment]
Hi, i am sorry i have no time to spend right now. But i will try to supply you a test case within the next two weeks.

**Comment by whiskeysierra** [comment]
@iribaar Were you able to define a test case?

**Comment by wyzssw** [comment]
some issue，and
```
 @Override
    public PrintWriter getWriter() throws IOException {
        if (withBody) {
            return tee().getWriter(this::getCharset); //charset is ISO-8859
        } else {
            return super.getWriter();
        }
    }
```

**Comment by whiskeysierra** [comment]
`1.2.5` includes a fix for this and is deployed to central.

**Comment by cybuch** [comment]
It's still not fixed. Also it swallows the status code - without logbook my endpoint returns 422, but with logbook it's always 200, I'm debugging this

**Comment by cybuch** [comment]
https://github.com/cybuch/sample-spring-reactive

I've made you a test case when you can observe Logbook misbehaving

**Comment by whiskeysierra** [comment]
@cybuch Thanks for the sample project. I'll take a look.

**Comment by whiskeysierra** [comment]
Logbook 1.5.0 should contain a fix.
