### ISSUE TITLE
Is it possible to make a new instance of Logbook based on the existing one with some modifications?

### ISSUE THREAD

**Issue by amseager** [zalando/logbook#1449]
Suppose I created a Logbook instance with `Logbook.builder()....build()` method (or took it from Spring's logbook auto config).
Now I need to create another one with overriding e.g. `bodyFilter()`. I plan to use it only for specific externall calls. Can I use the original object as a base for a new one?

**Comment by whiskeysierra** [comment]
If you created the original instance manually, then I'd just extract the
common parts into a function and call that function twice with different
filters eg.
