### ISSUE TITLE
Add filters to JsonPathBodyFilterBuilder jsonPath

### ISSUE THREAD

**Issue by bata19** [zalando/logbook#1466]
Add filters to:
``` java
public static JsonPathBodyFilterBuilder jsonPath(final String jsonPath) {
        return new JsonPathBodyFilterBuilder(compile(jsonPath));
    }
```
```java
public static JsonPathBodyFilterBuilder jsonPath(final String jsonPath, Predicate... filters) {
        return new JsonPathBodyFilterBuilder(compile(jsonPath, filters));
    }
```
For example, we can select only leaf element:
```java
jsonPath("$..pets[?]", new Predicate() {
    @Override
    public boolean apply(PredicateContext ctx) {
        Object val = ctx.item();
        return !(val instanceof Map || val instanceof List);
    }
});
```

**Comment by bata19** [comment]
Happy to contribute

**Comment by pedroluiznogueira** [comment]
Anyone working on this one?

**Comment by pedroluiznogueira** [comment]
> Anyone working on this one?

@kasmarian

**Comment by kasmarian** [comment]
@pedroluiznogueira If @bata19 is not looking into this, then I'd not expect any progress at the moment. I haven't seen PRs yet

**Comment by pedroluiznogueira** [comment]
@kasmarian may I work on this then?

**Comment by bata19** [comment]
@pedroluiznogueira Feel free to do it if you have any bandwidth. I could only do it some time at a later point.

**Comment by pedroluiznogueira** [comment]
Will do! I've got some time to take a look into that.

**Comment by pedroluiznogueira** [comment]
@kasmarian @whiskeysierra I was searching for a way to contribute to this project and I remembered this issue, is this still worth doing? I took a look and it seems like it's still not supported.

**Comment by kasmarian** [comment]
@pedroluiznogueira if you find a need for this feature, feel free to reopen this issue and add a PR with your proposal. There was no interest in the issue in the last several months, so the bot closed it.
