### ISSUE TITLE
Logbook (spring starter RC) 3 appears to ignore "minimum status" and some strategies, strategies with "status-at-least"_ & "body-only-if-status-at-least"

### ISSUE THREAD

**Issue by darrenskywalker** [zalando/logbook#1480]
If I include in my application.yml :

  minimum-status: 200
  strategy: body-only-if-status-at-least

It appears to ignore the minimum status setting and log alll requests/responses regardless of it being set to 200(Like 400 statuses etc..) As well as it ignores the "body-only" part where it logs the whole request/response. However without-body works just fine etc..but obviously ignores the minimum-status part.  
  
OR

  minimum-status: 200
  strategy: status-at-least
  
  Similarly, It appears to ignore the minimum status setting and log alll requests/responses regardless of it being set to 200(Like 400 statuses etc..)

**Comment by darrenskywalker** [comment]
Maybe I understand the "minimum status" backwards from what it is. Because at minimum of "400" it doesn't log 200s which I would have expected it would. 

So me personally, I only want to log 200 or successful requests.

**Comment by whiskeysierra** [comment]
It interprets the status numerically, i.e. a *minimum status* of 400 means the request/response pair is only logged if the status is >= 400.

**Comment by darrenskywalker** [comment]
Yeah, I just want to ONLY see 200s , so basically could we someday get a maximum status then?

**Comment by darrenskywalker** [comment]
It looks like I'll need to customize my own sort of "conditions like org.zalando.logbook.Conditions? With some custom Predicates?

I also don't want to log GET requests as well so ... :)

**Comment by whiskeysierra** [comment]
Yeah, providing your own `Strategy` implementation is the quickest and most flexible route here.
You can take a look [`BodyOnlyIfStatusAtLeastStrategy`](https://github.com/zalando/logbook/blob/main/logbook-core/src/main/java/org/zalando/logbook/BodyOnlyIfStatusAtLeastStrategy.java#L12) for inspiration or as a blueprint.

Only 2xx is a pretty weird feature, to be honest.
I'd be surprised if there is any widespread desire for this, hence it probably won't make it into Logbook's core.

**Comment by darrenskywalker** [comment]
My opinion is that it's not weird but very useful in the case of considering an audit changelog...ie...only log requests that modified something in the DB.

**Comment by whiskeysierra** [comment]
Huh, that's  an interesting use case, true.

**Comment by darrenskywalker** [comment]
Thank you. That looks like it'll work great for what I want!

**Comment by darrenskywalker** [comment]
@whiskeysierra ; real quick. I wrote my new Strategy which was simple...and I made a new Configuration file for it too to read from the application.yml.....does applicaiton.yml logbook section for Spring Boot able to read custom strategies there under the logbook section or do I need to do more manual LogBook configuration and not be able to use application.yml under the logbook section?

**Comment by whiskeysierra** [comment]
You can drop those two lines and register your strategy as a Spring bean, i.e. add a `@Component` annotation.
That should be enough for the auto configuration to find it and pick it up.

**Comment by darrenskywalker** [comment]
Thanks!

**Comment by darrenskywalker** [comment]
I've got it all working! It only logs successful & modifying requests....kind of like an audit change log. Thanks for your help @whiskeysierra !
