### ISSUE TITLE
MDC in request and response 

### ISSUE THREAD

**Issue by dkubicki** [zalando/logbook#1481]
As a developer, I would like to add MDC to correlate all requests and responses for each flow. 

## Description
My incoming request for an application 

`13:31:55.532 [XNIO-1 task-1] TRACE org.zalando.logbook.Logbook`

My outgoing response to the above request 

`13:31:56.012  [XNIO-1 task-1] TRACE org.zalando.logbook.Logbook`

Internal HTTP client request 

`13:31:55.678  8d74bcb5fa424119a91ca5aa69df7453 request-id  [XNIO-1 task-1] TRACE org.zalando.logbook.Logbook`

## Expected Behavior
I'd expect to add Filter or Interceptor to Logbook which adds to each request and response some MDC.

## Actual Behavior
I see only MDC context after setting it in my Endpoints not before.
Incoming requests to an application which logbook log.

## Possible Fix
Is there any way to add to a registry, configure an additional interceptor, or filter to the logbook? 

## Your Environment
* Version used: { module = "org.zalando:logbook-bom", version = "2.16.0" }
* Spring configuration

**Comment by dkubicki** [comment]
Let's clarify right now my app use MDC context. 
Unfortunately, Logbook does not consume this MDC for requests which incoming to my controller and the last response which I return - outgoing response. 

I tried using a filter or interceptor like below but it still Logbook does not register this and does not work as I'd like. 

`
  @Override
  protected void doFilterInternal(
    HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
    throws ServletException, IOException {
    try {
      ContentCachingRequestWrapper req = new ContentCachingRequestWrapper(request);
      ContentCachingResponseWrapper resp = new ContentCachingResponseWrapper(response);
      filterChain.doFilter(req, resp);

      byte[] requestBody = req.getContentAsByteArray();
      byte[] responseBody = resp.getContentAsByteArray();

      var jsonRequest = parseObject(new String(requestBody, StandardCharsets.UTF_8));

      if (jsonRequest.containsKey(SOME_KEY)) {
        MDC.put(MDC_ID, jsonRequest.getString(SOME_KEY));
      }

      var jsonResponse = parseObject(new String(responseBody, StandardCharsets.UTF_8));
      if (jsonResponse.containsKey(SOME_KEY)) {
        MDC.put(MDC_ID, jsonResponse.getString(SOME_KEY));
      }

      resp.copyBodyToResponse();
    }finally {
      MDC.remove(PROVIDER_ID);
   }
`
Example log -> 
The first request is what is incoming to us. How can I set MDC to it in Logbook?
`
15:20:41.133     [XNIO-1 task-1] TRACE org.zalando.logbook.Logbook - {
  "origin" : "remote",
  "type" : "request",
  "correlation" : "fe6cc087f71720a7",
  "protocol" : "HTTP/1.1",
  "remote" : "127.0.0.1",
  "method" : "POST",
  "uri" : "http://localhost:8080/123",
  "host" : "localhost",
  "scheme" : "http",
  "port" : "8080",
  "headers" : {
  },
  "body" : {}
}
15:20:41.272  MDC HERE -> 8d74bcb5fa424119a91ca5aa69df7453 request-id  [XNIO-1 task-1] TRACE org.zalando.logbook.Logbook - {
  "origin" : "local",
  "type" : "request",
  "correlation" : "8f89d4322967c24e",
  "protocol" : "HTTP/1.1",
  "remote" : "localhost",
  "method" : "POST",
  "scheme" : "https",
  "port" : null,
  "headers" : {
  },
  "body" : {}
}
`

**Comment by whiskeysierra** [comment]
So you want to set the whole request/response body/json as your MDC values?

**Comment by dkubicki** [comment]
Sorry for the long delay. 
I set MDC (not the whole request only some params) per the request.
Logbook RequestFilter works perfectly. However, we do not have a ResponseFilter and I had to do it by Spring filter.

```
class AppRequestFilter implements RequestFilter {

  private final AppMdcRequestStrategySelector appRequestPathFilter;

  public AppRequestFilter(MeterRegistry meterRegistry) {
    requireNonNull(meterRegistry, "meterRegistry");
    this.appRequestPathFilter = new AppMdcRequestStrategySelector(meterRegistry);
  }

  @Override
  public HttpRequest filter(HttpRequest request) {
    appRequestPathFilter.select(request.getPath()).addMdc(request);

    return request;
  }
}
```

**Comment by kasmarian** [comment]
@dkubicki I believe you can set anything you'd like to MDC in a filter or in an interceptor. You just need to make sure they will be executed before Logook. You don't really need Logbook Filters for this.
