### ISSUE TITLE
logbook-spring-boot-autoconfigure in 3.0.0-RC.2 is still using javax namespace dependencies

### ISSUE THREAD

**Issue by marcindabrowski** [zalando/logbook#1490]
Logbook in version 3.0.0 was supposed not to use `javax` dependencies.

## Description

In `logbook-spring-boot-autoconfigure`  [pom.xml](https://repo1.maven.org/maven2/org/zalando/logbook-spring-boot-autoconfigure/3.0.0-RC.2/logbook-spring-boot-autoconfigure-3.0.0-RC.2.pom)  there are two entries with `javax` artifacts.

```xml
<dependency>
  <groupId>org.zalando</groupId>
  <artifactId>logbook-servlet</artifactId>
  <version>${project.version}</version>
  <classifier>javax</classifier>
  <optional>true</optional>
</dependency>

<dependency>
  <groupId>javax.servlet</groupId>
  <artifactId>javax.servlet-api</artifactId>
  <version>4.0.1</version>
  <scope>compile</scope>
</dependency>
```

## Expected Behavior

Artifacts with `jakarta` namespace should be used.

## Actual Behavior

Artifacts with `javax` namespace are used.

## Your Environment

* Version used: 3.0.0-RC.2

**Comment by michael-schnell** [comment]
Same problem here. 

The artifact "org.zalando:logbook-spring-boot-autoconfigure:3.0.0-RC.2" still depends on "javax.servlet".

**Comment by ChristianLohmann** [comment]
Hi, the `logbook-servlet` dependency is set to `optional`. That means it won't be pulled if not explicitly needed.

**Comment by marcindabrowski** [comment]
Thanks for the fix. After migration to 3.0.0 final javax namespace is not imported anymore.
