### ISSUE TITLE
Support for ANSI colors

### ISSUE THREAD

**Issue by mimly-wkit** [zalando/logbook#1494]
Is it possible to customize the HTTP log output, for example as below?

![issue](https://github.com/zalando/logbook/assets/120388796/981a8084-c22f-4416-a18b-7d2ffcdf4fcb)

`DefaultHttpLogFormatter` seems to not work this way:
``` bash
2023-05-09T18:17:37.155+02:00 TRACE 18434 --- [nio-8989-exec-4] org.zalando.logbook.Logbook              : Incoming Request: f3f81601ffef19ed
Remote: 127.0.0.1
POST http://localhost:8989/api/login HTTP/1.1
accept: */*
content-length: 31
content-type: application/json
host: localhost:8989
user-agent: curl/8.0.1

{"username":"a","password":"b"}
```

**Comment by kasmarian** [comment]
It is possible to write your own implementation of [HttpLogFormatter](https://github.com/zalando/logbook/blob/main/logbook-api/src/main/java/org/zalando/logbook/HttpLogFormatter.java) and have colors defined there. If you're using Spring, just having a bean of type `HttpLogFormatter` will be sufficient.
