### ISSUE TITLE
Springboot configuration file prompt: Cannot resolve configuration property 'logbook.include'

### ISSUE THREAD

**Issue by 343585776** [zalando/logbook#1506]
## Description
After upgrading the package version 3.0.0, the Springboot configuration file prompts: Cannot resolve configuration property 'logbook.include'.

## Expected Behavior
Support prompts in yml

## Actual Behavior
<img width="571" alt="image" src="https://github.com/zalando/logbook/assets/15976826/02b5b49d-f61d-47c0-9440-624bbd700b7d">

**Comment by kasmarian** [comment]
@343585776 care to create a pull request?

**Comment by kasmarian** [comment]
This should be covered by https://github.com/zalando/logbook/pull/1592 and will be in the next release. Please re-open the issue if it's not fully addressed
