### ISSUE TITLE
Exclude some headers from output

### ISSUE THREAD

**Issue by liviamoroianu** [zalando/logbook#151]
Hello! Is there a way to log only some of the http headers(and not just obfuscating, literally exclude headers)?
Thanks

**Comment by whiskeysierra** [comment]
I'm on mobile right now, so I can't provide you an example how to do that.
I'll just copy a section from the readme here. If write your own
RequestFilter you can definitely do it. It will not be as easy and short as
obfuscation, but it will work.

For more complicated setups one should fallback to the low-level variants,
i.e. RawRequestFilter andRawResponseFilter as well as RequestFilter and
ResponseFilterrespectively (in conjunction withForwardingRawHttpRequest/
ForwardingRawHttpResponse and ForwardingHttpRequest/ForwardingHttpResponse).

**Comment by AlexanderYastrebov** [comment]
Should be possible with `HeaderFilter` https://github.com/zalando/logbook#filtering

OTOH it may be a bad idea to exclude headers since you will never know that header was or was not there at all.

**Comment by liviamoroianu** [comment]
Hi Alexander, from what I know about HeaderFilter, it helps you obfuscate headers(for security reasons, so that u don't log sensitive information) but I'll definitely take a closer look at it. 

I'll probably work on a custom RequestFilter implementation for my logbook object, as whiskeysierra suggested.

Thanks for your answers
