### ISSUE TITLE
Tracing not working for LogbookClientHandler

### ISSUE THREAD

**Issue by rajapanda15** [zalando/logbook#1512]
## Description
The LogbookClientHandler in Spring Boot 3 is not printing trace IDs when logging requests and responses using the LogbookClientHandler.

## Expected Behavior
The logbook instance passed to LogbookClientHandler should log the trace and span ids. 

## Actual Behavior
The logs are printing empty/blank values.
<img width="1357" alt="image" src="https://github.com/zalando/logbook/assets/10570559/c27b0556-519a-4232-b875-8bf284a86b46">

The below project can be referred 
https://github.com/rajapanda15/Springboot3-Logbook.git

**Comment by kasmarian** [comment]
Related to #1513 ?

**Comment by grassehh** [comment]
I have the same issue. 
I don't know if you are using Micrometer and Webflux, but you can check my [issue](https://github.com/reactor/reactor-netty/issues/2850) on Reactor Netty.
I managed to make webClient calls working by overriding Logbook's `logbookNettyClientCustomizers` and wrapping the `LogbookClientHandler`with a custom Netty's `ChannelDuplexHandler` as suggested by Violeta. 
However, using the same mecanism for custiming the Netty `HttpServer`does not work, even though the `LogbookServerHandler` is called.

Checkout my sample (here)[https://github.com/grassehh/spring-boot-3-tracing-coroutine] on the **issues/reactor-netty** branch.

**Comment by msdousti** [comment]
You set log pattern to get the `traceId` and `spanId` from the MDC:

```
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] ...
```


And then expect them to be added to the log lines of Logbook (red boxes below, where they are empty):

![image](https://github.com/zalando/logbook/assets/3616518/e413fc83-5f1b-48d7-abf5-d201b2962947)

However, notice that green boxes in the above figure: They show that Logbook is being executed from a separate thread called `reactor-http-nio-2`, while the original thread was called `http-nio-8080-exec-*` (not shown in the figure). It appears that `WebClient` runs in a thread separate from the controller.

The important point to note, from [Logback documentation](https://logback.qos.ch/manual/mdc.html) (**Logback** is an implementation of **SLF4J API**, and is used behind the scenes by **Logbook**):

> The MDC manages contextual information on a per thread basis.

![image](https://github.com/zalando/logbook/assets/3616518/a0778555-7d3f-4936-a816-fe53b11d3216)

So, here is what happens:

1. Your controller receives a call, and the MDC is populated by `traceId`/`spanId`
2. The controller calls WebClient without propagating the MDC. It creates a new thread with an empty MDC map.
3. Any logs printed (regardless whether they are by Logbook or not) will not have `traceId`/`spanId`.

This article might be helpful: https://ttddyy.github.io/mdc-with-webclient-in-webmvc/

Pay special attention to Spring Boot 3 section. Hope this helps!
