### ISSUE TITLE
Logbook not logging request and responses to log4j log file

### ISSUE THREAD

**Issue by alimohsin25** [zalando/logbook#1543]
I am using spring boot version 2.6.7 and log4j. I used logbook to log my request and responses, I can view request and responses in console. I have added following configuration to log request and response in log file. This configuration is logging information of my class into a separate log file but not of Logbook.

`
log4j.rootLogger=TRACE, file
log4j.appender.File=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=logs/kbs-application.log
log4j.appender.file.MaxFileSize=5MB
log4j.appender.file.MaxBackupIndex=10
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

log4j.logger.mypackage.service=TRACE, MyPackageHandler
log4j.additivity.mypackage.service=false
log4j.appender.MyPackageHandler=org.apache.log4j.RollingFileAppender
log4j.appender.MyPackageHandler.File=logs/burnup-application.log
log4j.appender.MyPackageHandler.MaxFileSize=5MB
log4j.appender.MyPackageHandler.MaxBackupIndex=10
log4j.appender.MyPackageHandler.layout=org.apache.log4j.PatternLayout
log4j.appender.MyPackageHandler.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

log4j.logger.org.zalando.logbook=TRACE, logbookappender
log4j.additivity.org.zalando.logbook=false
log4j.appender.logbookappender=org.apache.log4j.RollingFileAppender
log4j.appender.logbookappender.File=logs/logbook-application.log
log4j.appender.logbookappender.MaxFileSize=5MB
log4j.appender.logbookappender.MaxBackupIndex=10
log4j.appender.logbookappender.layout=org.apache.log4j.PatternLayout
log4j.appender.logbookappender.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
`

## Expected Behavior
I am able to log request and responses in a separate log file

## Actual Behavior
I am able to log request and responses in a separate log file

**Comment by kasmarian** [comment]
@alimohsin25 could you create a repo where the issue is reproducible? I tried repeating the steps and was able to see logbook's logs in a file.
