### ISSUE TITLE
Autoconfigured NettyServerCustomizer for webflux does not log for 4XX/5XX response code

### ISSUE THREAD

**Issue by gedankennebel** [zalando/logbook#1555]
Hi, not sure if this is a bug in generall or just an issue with our setup.

We are using spring-cloud-starter-gateway 3.0.6 (webflux netty based spring application) and by adding 
org.zalando:logbook-spring-boot-webflux-autoconfigure:3.1.0 we only see request/response logging for a 2XX successfull request/response call. By hitting 403 or 404 no request/response logs are printed. 

However, using the LogbookWebFilter from the logbook webflux component all incoming request/responses are printed as expected regardless of the resulting response status code. 

This currently brings us to the solution to not use the webflux autoconfigure package and add something like this to our application by our own:
```
Bean
@Order(Ordered.HIGHEST_PRECEDENCE)
@ConditionalOnWebApplication(type = REACTIVE)
public WebFilter logbookServerFilter(Logbook logbook) {
    return new LogbookWebFilter(logbook);
}
```

A debug session using the debug log level showed us that the LogbookServerHandler got removed if the application ran into an error, we assume that this is the reason why the final "write" is never happening.
```
 
reactor.netty.ReactorNetty               : [1c159a01-13, L:/[0:0:0:0:0:0:0:1]:8080 - R:/[0:0:0:0:0:0:0:1]:54112] Added decoder [LogbookServerHandler] at the end of the user pipeline, full pipeline: [reactor.left.httpCodec, reactor.left.httpTrafficHandler, LogbookServerHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0] 
reactor.netty.http.server.HttpServer     : [1c159a01-13, L:/[0:0:0:0:0:0:0:1]:8080 - R:/[0:0:0:0:0:0:0:1]:54112] Handler is being applied: org.springframework.http.server.reactive.ReactorHttpHandlerAdapter@72bc5a26 
r.n.http.server.HttpServerOperations     : [1c159a01-13, L:/[0:0:0:0:0:0:0:1]:8080 - R:/[0:0:0:0:0:0:0:1]:54112] Last HTTP response frame 
r.n.http.server.HttpServerOperations     : [1c159a01-13, L:/[0:0:0:0:0:0:0:1]:8080 - R:/[0:0:0:0:0:0:0:1]:54112] No sendHeaders() called before complete, sending zero-length header 
r.n.http.server.HttpServerOperations     : [1c159a01-13, L:/[0:0:0:0:0:0:0:1]:8080 - R:/[0:0:0:0:0:0:0:1]:54112] Decreasing pending responses, now 0 
r.n.http.server.HttpServerOperations     : [1c159a01-13, L:/[0:0:0:0:0:0:0:1]:8080 - R:/[0:0:0:0:0:0:0:1]:54112] Last HTTP packet was sent, terminating the channel 
r.netty.channel.ChannelOperations        : [1c159a01-13, L:/[0:0:0:0:0:0:0:1]:8080 - R:/[0:0:0:0:0:0:0:1]:54112] [HttpServer] Channel inbound receiver cancelled (subscription disposed). 
reactor.netty.ReactorNetty               : [1c159a01, L:/[0:0:0:0:0:0:0:1]:8080 - R:/[0:0:0:0:0:0:0:1]:54112] Removed handler: LogbookServerHandler, pipeline: DefaultChannelPipeline{(reactor.left.httpCodec = io.netty.handler.codec.http.HttpServerCodec), (reactor.left.httpTrafficHandler = reactor.netty.http.server.HttpTrafficHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)} 
```

We can see from the logs that the handler is applied, but also that LogbookServerHandler got removed encountering an application error. 

## Expected Behavior
NettyServerCustomizer from org.zalando:logbook-spring-boot-webflux-autoconfigure:3.1.0 should log all incoming requerst/responses regardless of the resulting response status. 

## Actual Behavior
NettyServerCustomizer from org.zalando:logbook-spring-boot-webflux-autoconfigure:3.1.0 only logs for incoming requerst/responses if  HTTP 2XX. 

## Steps to Reproduce 
1. Spring Netty based web application (version 3.X.X)
2. org.zalando:logbook-spring-boot-webflux-autoconfigure:3.X.X
3. Send application request which leads to non 2XX response code
4. No request/response logs printed out
5. Send application request which leads to 2XX response code
6. Request/response logs printed out as expected

## Your Environment
* Version used:  3.0.1

**Comment by kasmarian** [comment]
Hi @gedankennebel could you help with narrowing down the problem here a bit? I used https://github.com/spring-cloud-samples/spring-cloud-gateway-sample as a base and added logbook (version 3.1.0) there, and wasn't able to reproduce the issue, both success and error logs were printed. Could it be specific to the configuration you're having?

**Comment by alphafoobar** [comment]
I was able to replicate this issue using a build from spring initialzr and then adding in logbook. It worked after I added the `bean` as shared above.

```java
  @Bean
  @Order(Ordered.HIGHEST_PRECEDENCE)
  @ConditionalOnWebApplication(type = Type.REACTIVE)
  public WebFilter logbookServerFilter(Logbook logbook) {
    return new LogbookWebFilter(logbook);
  }
```

This is a link to the spring boot initialzr that I was using: https://start.spring.io/#!type=gradle-project-kotlin&language=java&platformVersion=3.4.1&packaging=jar&jvmVersion=21&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=lombok,webflux
