### ISSUE TITLE
Can we have filter to exclude by Http method name

### ISSUE THREAD

**Issue by sadhir1502** [zalando/logbook#1556]
it would be great if we are able to exclude logging by http method name

## Detailed Description
For example lets say i want to exclude all the GET,DELETE calls from the logging we should have configurations as we have for excluding by urls, and excluding by contenttype.

**Comment by whiskeysierra** [comment]
@sadhir1502 Care to create a pull request?

**Comment by sadhir1502** [comment]
Sure i will raise a pull request once changes are done.

**Comment by kasmarian** [comment]
@sadhir1502 this should be available starting from the next release. See more details in this PR - https://github.com/zalando/logbook/pull/1606 and [README](https://github.com/zalando/logbook#example-configuration)
