### ISSUE TITLE
Consider removing 'com.google.gag' from dependencies

### ISSUE THREAD

**Issue by voplex95** [zalando/logbook#156]
Hi! Probably not the most important stuff to do... but still... This library has nothing to do with the functionality itself. Was surprised to see "GAGs" on my classpath.

**Update:** **jcip-annotations** library seems to be yet another syntactic sugar.

**Comment by whiskeysierra** [comment]
I'll change the scope to `provided`, that way we can still use them in the code but we won't clutter the runtime classpath of users. The `jcip-annotations` are needed for one test to tell the surefire plugin. Somehow I forgot to use the `test` scope for this.

**Comment by whiskeysierra** [comment]
@voplex95 I released 1.2.4. Thanks for raising this issue.

**Comment by voplex95** [comment]
@whiskeysierra thanks for quick release
