### ISSUE TITLE
Requests/Responses of POST requests in spring cloud gateway are not logged

### ISSUE THREAD

**Issue by MatthiasDrews** [zalando/logbook#1571]
## Description
In a reactive spring cloud gateway application, with Logbook included, there is no logging of requests and responses for HTTP POST requests, when configuring the strategy `logbook.strategy=without-body`. With the default strategy logging works as expected.

## Expected Behavior
Requests/Responses for HTTP POST requests are logged without the bodies.

## Actual Behavior
Requests/Responses for HTTP POST requests are not logged at all

## Possible Fix
Reason: The execution of the `writeHook` is triggered differently between GET and POST requests. For POST requests and `withoutBody` strategy, it is just never invoked.

## Your Environment
* Version used: 3.1.0

**Comment by kasmarian** [comment]
Thank you for the fix @MatthiasDrews , the fix will be part of the next release
