### ISSUE TITLE
HttpRequest not visibile to classloader

### ISSUE THREAD

**Issue by vincent-nagy** [zalando/logbook#1607]
When adding logbook-servlet and also logbook-okhttp I get HttpRequest not visibile to classloader

## Description
The logging for the incoming and outgoing of the servlet is logged but instead of logging the incoming and outgoing of okhttp, I now get these errors.
[INFO] [ERROR   ] org.zalando.logbook.HttpRequest referenced from a method is not visible from class loader
[INFO] org.zalando.logbook.HttpRequest referenced from a method is not visible from class loader

## Expected Behavior
Okhttp should still log as expected.

## Actual Behavior
Okhttp can't log anymore and gives these classloader errors.

## Steps to Reproduce
1. Add both logbook-okhttp and logbook-servlet to a openliberty jakarta project
2. Make an api that uses okhttp to make an external call

## Your Environment
* Version used: 3.3.0
* Openliberty with jakarta 10

**Comment by msdousti** [comment]
Please make sure you have added `logbook-core` as well.

If the problem still exists, please provide a minimum-working example (MWE), preferrably a link to MWE repo on GitHub.

**Comment by msdousti** [comment]
I'm gonna assume that the above comment solved the issue, and close this ticket.
If not, please feel free to re-open it with a minimum-working example (MWE) as explained above.
