### ISSUE TITLE
logbook messy code 

### ISSUE THREAD

**Issue by wyzssw** [zalando/logbook#163]
I have upload the contain-bug project to my repository
https://github.com/wyzssw/logbookbug
please just execute LogbookbugApplication in IDE, and open browse http://localhost:8080/test

**Comment by wyzssw** [comment]
These is two bug
1. messy code
2. miss header `Content-Type:text/html;charset=UTF-8`

**Comment by whiskeysierra** [comment]
`1.2.5` includes a fix for 2. and is deployed to central.
