### ISSUE TITLE
Support native compilation with graalvm

### ISSUE THREAD

**Issue by itineric** [zalando/logbook#1652]
You could support graalvm native compilation.
Currently it is not working, some exception occur:
`com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.zalando.logbook.json.JsonHttpLogFormatter$JsonBody and no properties discovered to create BeanSerializer `

## Detailed Description
Define reflect-config.json files as explained in graalvm documentation.

## Context
Can use logbook when going native

**Comment by jordanorc** [comment]
In my case I was able to solve it in a Spring Boot project following the steps below.

1. Add the file `reflection-config.json` in folder : `src/main/resources` with the content:

```json
[
    {
      "name" : "org.zalando.logbook.json.JsonHttpLogFormatter$JsonBody",
      "allPublicMethods" : true
    }
]
```

2. Add in the `build.gradle` file:
```
buildArgs.add("-H:ReflectionConfigurationFiles=${projectDir}/src/main/resources/reflection-config.json")
```

**Comment by itineric** [comment]
you can do that with only one step:
rename your file `reflection-config.json` to `reflect-config.json` and place it inside `src/main/resources/META-INF/native-image/<group id>/<artifact id>` it will be picked up automatically.

It you are using Spring, you can also use `ReflectionHints` instead.

My point here is that this reflection config could be added directly to the logbook lib then no extra (external) configuration is required.

**Comment by kasmarian** [comment]
Looks like a nice addition to logbook. @itineric would you be interested in contributing to the library to add the necessary changes?
