### ISSUE TITLE
No traceId for SpringCloudGateway request in SpringBoot 3.2.0

### ISSUE THREAD

**Issue by MatthiasDrewsCS** [zalando/logbook#1694]
After upgrading a SpringCloudGateway application to SpringBoot 3.2.0, and SpringCloud 2023.0.0-RC1, there is no traceId logged with the request.

## Description

There is however a traceId logged with the response. We are using the `LogbookWebFilter`.

With SpringBoot 3.1.5 and SpringCloud 2022.0.4, the behavior was the opposite. The traceId was logged with request, but not with the response. However we managed to apply a workaround for our application, to get the traceId also with the response. 

## Expected Behavior

The instrumentation of Spring should make sure, that traceIds are logged for requests and responses.

## Actual Behavior

TraceIds are logged with the response only.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* SpringBoot: 3.2.0
* SpringCloud: 2023.0.0-RC1
* Logbook: 3.6.0

**Comment by kasmarian** [comment]
Is this related a similar problems raised in https://github.com/zalando/logbook/issues/1512 ?

**Comment by MatthiasDrewsCS** [comment]
We can close this issue. It can be fixed by upgrading to SpringFramework 6.1.2, so with SpringBoot 3.2.1 it will be alright
