### ISSUE TITLE
Add support for Servlet API 2.5 

### ISSUE THREAD

**Issue by hanfak** [zalando/logbook#172]
All versions of logbook depend on javax.servlet version 3. 

Can you please add support for version 2.5 of javax.servlet?

We cannot easily upgrade the servlet version.

**Comment by whiskeysierra** [comment]
Can you provide a short list of changes between 2.5 and 3.0? I have never used either directly myself but rather via some frameworks.

**Comment by whiskeysierra** [comment]
> Need to call getParameterMap in the RemoteRequest BEFORE withBody is called in order to ensure the query string/form content is parsed ready for getParameterMap calls. However, this consumes the input stream. This issue seems not related to 2.5 vs 3 but was an existing logbook bug. Not sure how to solve this one...

This is indeed an existing known issue. See #94 and #169.

> No async (e.g. HttpServletRequest getDispatcherType, isAsyncStarted)
> HttpServletResponseWrapper does not have getStatus, getHeaderNames, getHeaders

Not having a compile time dependency to those methods (and enum values) will make things *"a bit"* ugly but technically doable. Spring does it for years, with some success at least.

> Also, it would be useful to keep LogbookFilter non final, so that it can be extended in order to provide a default constructor with Logbook built up in that constructor (e.g. to use it in a web.xml file).

This is not really related to 2.5 but it would be a general feature. Would you expect that this newly created default constructor uses all the defaults for logbook? Or would you expect some customization options? Feel free to open another issue for this feature in particular.

In general, I'd be thrilled if you could open a PR that changes the minimum requirement to 2.5 and also gets rid of the obvious issues (e.g. just uncomment/hardcode/ignore certain features/tests) just so we see the real size of the change we're talking about.

**Comment by hanfak** [comment]
Any ideas on next steps?  We have already pushed a commit.

**Comment by whiskeysierra** [comment]
I did not yet have the time to take a deeper look. Your PR is good first step. I'll try to take it as a foundation. I'll need to:
- instruct travis to build it twice, for 2.5 and 3.0 repsectively
- ensure code coverage

**Comment by whiskeysierra** [comment]
See comment in #182
