### ISSUE TITLE
Does setting the log level to debug enable log output?

### ISSUE THREAD

**Issue by G-Fantastic** [zalando/logbook#1729]
Does setting the log level to `debug` enable log output? When the level is set to `trace`, it outputs a lot of other irrelevant log information. I'd like to set the log level to `debug`. How can I do that?

**Comment by kasmarian** [comment]
You just need to specify the `trace` log level for logbook, but not the whole application. 
E.g., if you're using a spring application, you can do this by adding `logging.level.org.zalando.logbook: TRACE` in the application.yaml/properties file.
