### ISSUE TITLE
Spring Boot 2.0.0 (milestone) incompatibility

### ISSUE THREAD

**Issue by eric239** [zalando/logbook#176]
Hello,

It appears that the latest release of logbook -- `1.4.0` -- is *incompatible* with the latest milestone release of spring boot 2.0 (`2.0.0.M3`), and this problem will persist into upcoming 2.0.0 release.

Specifically, `LogbookAutoConfiguration` has the following code:
```java
@AutoConfigureAfter({
        JacksonAutoConfiguration.class,
        WebMvcAutoConfiguration.class,
})
```
`WebMvcAutoConfiguration` is imported as
```java
import org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration;
```
however in spring boot 2, it has been moved to `org.springframework.boot.autoconfigure.web.servlet` package. The end result is that an app trying to use both spring boot 2.0.0.M3 and logbook 1.4.0 fails to start with
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authorizedLogbookFilter' defined in class path resource [org/zalando/logbook/spring/LogbookAutoConfiguration$ServletFilterConfiguration.class]: Unsatisfied dependency expressed through method 'authorizedLogbookFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.zalando.logbook.spring.LogbookAutoConfiguration': Bean instantiation via constructor failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
```

Obviously this is a backwards-incompatible change. How do you guys suggest to handle it? Is there a separate branch of logbook aligned with spring boot 2.0.0?

**Comment by whiskeysierra** [comment]
I have to double check, but I believe one can declare a dependency to other auto configurations based on name. So this could work:

```java
@AutoConfigureAfter(name={
    "org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration",
    "org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration"
})
```

**Comment by whiskeysierra** [comment]
@eric239 Can you take a look at #178?
