### ISSUE TITLE
URI in request log is missing slash character before path

### ISSUE THREAD

**Issue by grassehh** [zalando/logbook#1793]
## Description
If the path of a request does not start with a `/` character, the resulting URI in the request log will be missing the `/`.
For example, if the path base uri is `http://localhost:8080/` and the path is `test` the log will show `http://localhost:8080test`.

## Expected Behavior
The URI in the request log should be correct

## Actual Behavior
The URI in the request log is correct

## Possible Fix
From what I've been able to debug, the issue seems to reside in the way the URI is reconstructed in the [RequestURI.reconstruct](https://github.com/zalando/logbook/blob/b4b660cb4e8e4052e1d220325788e93ce1376845/logbook-api/src/main/java/org/zalando/logbook/RequestURI.java#L68). 
It simply adds the `PATH` without checking if it actually contains a `/` or not. So maybe the fix could be to prepend a `/` if it does not contain it.
_Possible workaround_: As of using Ktor, a workaround seems to be to explicity prepend a slash in the path of each client calls.

## Steps to Reproduce
It is simple to reproduce for example when using Ktor as it allows to make requests without specifying a `/` when you configure a default request URI.
Simply run the following test class: [https://github.com/grassehh/issues/blob/main/zalando-logbook-1793/src/test/kotlin/com/grassehh/ClientTest.kt](https://github.com/grassehh/issues/blob/main/zalando-logbook-1793/src/test/kotlin/com/grassehh/ClientTest.kt).
Then in the logs you will see `POST http://localhost:61361test` instead of `POST http://localhost:61361/test`

## Context
It make the log very confusing as you think your URI is incorrect while it is actually correct.

## Your Environment
* Version used: 3.7.2

**Comment by kasmarian** [comment]
@grassehh thank you for the thorough investigation for this issue. Indeed, there was a bug in the way `RequestURI.reconstruct` worked. The fix will be available in the next version.
