### ISSUE TITLE
Not able to remove headers

### ISSUE THREAD

**Issue by yvandecn** [zalando/logbook#181]
Hi! Can someone help me configuring logbook to remove the `X-Application-Context` from logs ? I tried the following but it still appears:
```
    private Logbook getHttpClientLogbook() {
        return Logbook
                .builder()
                .formatter(new JsonHttpLogFormatter())
                .headerFilter(authorization())
                .headerFilter(removeHeaders("X-Application-Context"::equalsIgnoreCase))
                .build();
```
Thanks!

**Comment by whiskeysierra** [comment]
Your code looks correct and should indeed remove the header completely from the log output. We have [a test](https://github.com/zalando/logbook/blob/master/logbook-core/src/test/java/org/zalando/logbook/HeaderFiltersTest.java#L79) that verifies that `removeHeaders` is working correctly.

Are you trying to remove the headers from requests or responses? That could help me to pinpoint the issue.

**Comment by whiskeysierra** [comment]
One possible workaround would be to instruct spring to no include this header into responses at all. See [Appendix A. Common application properties](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) for details:

```yaml
management.add-application-context-header: false
```

**Comment by yvandecn** [comment]
I'm trying to remove from both requests and responses. Thank you for the hint, I will try the spring configuration property.
