### ISSUE TITLE
[logbook-ktor-client] removes Content-Type request header

### ISSUE THREAD

**Issue by grassehh** [zalando/logbook#1821]
## Description
When sending requests using Ktor client with the `LogbookClient` plugin from `logbook-ktor-client` installed, the `Content-Type` header is removed from the request.
Another side effect of this issue is that `JacksonJsonFieldBodyFilter` does not work properly as it checks [the content type](https://github.com/zalando/logbook/blob/f29dad2ca372dffa389d296bd0acf8ed352a3da9/logbook-json/src/main/java/org/zalando/logbook/json/JacksonJsonFieldBodyFilter.java#L45).

## Expected Behavior
The `Content-Type` header should be preserved when sending the request.

## Actual Behavior
The `Content-Type`header is removed from the request.

## Possible Fix
There are two places to fix.
- The first is in the `LogbookClient` class itself. [This line](https://github.com/zalando/logbook/blob/f29dad2ca372dffa389d296bd0acf8ed352a3da9/logbook-ktor-client/src/main/kotlin/org/zalando/logbook/client/LogbookClient.kt#L49) should return
```kotlin
it
```
- The second place is in the [ClientRequest](https://github.com/zalando/logbook/blob/main/logbook-ktor-client/src/main/kotlin/org/zalando/logbook/client/ClientRequest.kt) class.
The `getHeaders()` and `getContentType()` method should try to respectively append and retrieve the `Content-Type` header from the [OutgoingContent.contentType](https://github.com/ktorio/ktor/blob/d5ae8e5641dea582fbe5ebb52577e7bdad2f5ad8/ktor-http/common/src/io/ktor/http/content/OutgoingContent.kt#L25) property when applicable (this one is necessary in order for features like `JacksonJsonFieldBodyFilter` to work properly).
Example: 
```kotlin
override fun getHeaders(): HttpHeaders = HttpHeaders.of(request.headers.build().toMap())
        .also {
            if (it.contains(ContentType).not() && request.body is OutgoingContent) return it.update(
                ContentType,
                (request.body as OutgoingContent).contentType.toString()
            )
        }

override fun getContentType(): String? =
        request.contentType()?.toString()?.substringBefore(";") ?: (request.body as? OutgoingContent)?.contentType?.toString()

```

**Explainations:**  For some reasons, Ktor [removes](https://github.com/ktorio/ktor/blob/e789b015bd5169505df1c59ced0d2690026af523/ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/DefaultTransform.kt#L55) the `Content-Type` header from the `request` object and pushes it into the `OutgoingContent`.
Thus the `Content-Type` is lost when Logbook replaces the content with a fresh new one by using `ByteArrayContent(content)`, and the `ClientRequest` needs to retrieve the information from the `OutgoingContent` instead of the `headers` object.

## Steps to Reproduce
- Checkout this repository: [https://github.com/grassehh/issues](https://github.com/grassehh/issues)
- Run the `ClientTest` test inside the **zalando-logbook-1821** folder

The test will fail. If you uninstall `LogbookClient`, the test will pass.

## Context
I was writing integration tests that check that my request contained the `Content-Type: application/json` header and it failed.

## Your Environment
Ktor 2.3.10
Logbook 3.8.0

**Comment by kasmarian** [comment]
@grassehh please see https://github.com/zalando/logbook/pull/1833 with the fix that you suggested. And thank you very much for the detailed explanation of the issue and your investigation.

**Comment by kasmarian** [comment]
The fix will be in the next release, thank you for the detailed issue
