### ISSUE TITLE
Do not log response

### ISSUE THREAD

**Issue by thenovacreator** [zalando/logbook#186]
Is there a way to skip the response Logging? I am using a Spring Boot App and want to skip the response generated since its not needed in uses a lot of space sometimes.

**Comment by whiskeysierra** [comment]
Do you want to skip logging of the body or skip the whole log message for the response?

**Comment by thenovacreator** [comment]
Both should be ok. Depending on what is easier to implement.

**Comment by whiskeysierra** [comment]
This should do the trick (skip logging of response body). 

```java
Logbook.builder()
    .rawResponseFilter(replaceBody(response -> ""))
```

Completely skipping the logging of the response requires a custom `HttpLogWriter`. It's not rocket science, but a bit more work.

**Comment by cybuch** [comment]
https://github.com/zalando/logbook/blob/master/logbook-core/src/test/java/org/zalando/logbook/DelayedResponseLogWriter.java HttpLogWriter that does similar thing

**Comment by whiskeysierra** [comment]
Yes, true. That class is an example (it's part of the test sources), but it shows how you could solve your original requirement.
