### ISSUE TITLE
Question : is it possible to change the log level dynamically in spring apps

### ISSUE THREAD

**Issue by sgandon** [zalando/logbook#187]
Hello again, 
sorry to use this for a question but this is suggested in the the readme ;)
I was wondering if the logbook writer log level can be changed dynamically and ideally using the actuator */loggers* endpoint ?

**Comment by whiskeysierra** [comment]
The log level that you specify for the writer just defines which log level the writer will use to log the traffic. Let's say you use `INFO` there and the `org.zalando.logbook.Logbook` category (default). You are now able to use the actuator endpoint to enable/disable the logger for that level.

**Comment by sgandon** [comment]
indeed that works, I did the test before but it failed I don't know why. Thanks a lot for your quick answer.
