### ISSUE TITLE
Unable to use multiple custom attribute extractors defined through configuration

### ISSUE THREAD

**Issue by SiliconMind** [zalando/logbook#1950]
According to the documentation and samples I should be able to configure multiple attribute extractors. However when I do that the application will fail to start due to an exception from logbook.

## Description

According to the documentation I should be able to provide multiple attribute extractors: https://github.com/zalando/logbook?tab=readme-ov-file#configuration

Sample configuration
```yaml
logbook:
  attribute-extractors:
    - type: JwtFirstMatchingClaimExtractor
    - type: MyCustomExtractor
```

## Expected Behavior

When multiple attribute extractors are provided through parameters, the application runs and all of those extractors are applied.

## Actual Behavior

Exception is thrown and the app fails to start:

```
org.springframework.boot.web.embedded.tomcat.TomcatStarter: Error starting Tomcat context.
  Exception: org.springframework.beans.factory.UnsatisfiedDependencyException.
  Message: Error creating bean with name 'secureLogbookFilter' defined in class path resource [org/zalando/logbook/autoconfigure/LogbookAutoConfiguration$JavaxSecurityServletFilterConfiguration.class]:
      Unsatisfied dependency expressed through method 'secureLogbookFilter' parameter 0;
  nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException:
    Error creating bean with name 'logbook' defined in class path resource [org/zalando/logbook/autoconfigure/LogbookAutoConfiguration.class]:
        Unsatisfied dependency expressed through method 'logbook' parameter 9;
  nested exception is org.springframework.beans.factory.BeanCreationException:
    Error creating bean with name 'getAttributeExtractor' defined in class path resource [org/zalando/logbook/autoconfigure/LogbookAutoConfiguration.class]:
        Bean instantiation via factory method failed;
  nested exception is org.springframework.beans.BeanInstantiationException:
    Failed to instantiate [org.zalando.logbook.attributes.AttributeExtractor]:
        Factory method 'getAttributeExtractor' threw exception;
  nested exception is java.lang.IllegalArgumentException:
    Unknown AttributeExtractor type: MyCustomExtractor
```

This is happening because the implementation of [ExtractorProperty.toExtractor](https://github.com/zalando/logbook/blob/main/logbook-spring-boot-autoconfigure/src/main/java/org/zalando/logbook/autoconfigure/LogbookProperties.java#L66) method in logbook is hardcoded to handle only `JwtFirstMatchingClaimExtractor` and `JwtAllMatchingClaimsExtractor` - any other extractor will throw the exception.

Ironically the very same custom extractor would still work when defined through properties but only if used as a single extractor.

## Possible Fix
Adjust [ExtractorProperty.toExtractor](https://github.com/zalando/logbook/blob/main/logbook-spring-boot-autoconfigure/src/main/java/org/zalando/logbook/autoconfigure/LogbookProperties.java#L66) method to handle any AttributeExtrator interface implementation or at least update documentation to explicitly state that the ONLY way to use multiple custom attribute extractors is through `CompositeAttributeExtractor`

Current wording of documentation:
> If you require to incorporate multiple AttributeExtractors, you can use the class CompositeAttributeExtractor [...]

The word **CAN** implies that this is an **option** (one of many) and not a necessity.

**Comment by msdousti** [comment]
The documentation for `logbook.attribute-extractors` clearly states that the Spring Boot module **currently** supports two implementations:

![image](https://github.com/user-attachments/assets/08561bd8-6f74-4251-903c-6812e8abfc34)

This is a known limitation on the Spring Boot Logbook module. As such, the documentation for `CompositeAttributeExtractor` is also correct: You are not forced to use it. You can write your custom attribute combiner.
