### ISSUE TITLE
Servlet 3 asynchronous requests not correctly handled

### ISSUE THREAD

**Issue by c0nscience** [zalando/logbook#2]
Hi,

we just tried your logging filter implementation, but it breaks all of our requests. Because we use exclusively servlet 3 async requests in our application, every request mapping method returns a callable.

Example method declaration:
```java
public Callable<ResponseEntity<Entity>> getEntity(@RequestBody final dto)
```

The response is always missing the content type and body, with the logging filter enabled.

Any suggestions how to fix this problem?

**Comment by lukasniemeier-zalando** [comment]
I haven't had the chance to look into a filter chain with async requests. Could you provide a failing test case?

**Comment by c0nscience** [comment]
Thanks @lukasniemeier-zalando for the quick response.

I just created a small example project with a simple rest endpoint and the logging filter configured.
Have a look at https://github.com/c0nscience/async-logging-test

The junit test though succeeds, but you can see in the logs that the httpLogger of the filter does not log a content type nor the body. If you run the example with the filter enabled the response is empty and if disabled the response is correct.

Sorry for the form of the example, I didn't know a faster and easier solution.
I hope it helps a bit.

**Comment by lukasniemeier-zalando** [comment]
Thank's for the test case. I think @whiskeysierra already tried out something promising :clock1:

**Comment by rzimmer** [comment]
Uh, that's great! Really looking forward to have async responses having logged! :+1:

**Comment by whiskeysierra** [comment]
@rzimmer @c0nscience Can you try with `org.zalando:logbook-servlet:0.1.0`? We completely refactored the library and added support for async dispatch in the meantime.

**Comment by rzimmer** [comment]
We had the chance to take a deeper look at the refactored library yesterday and so far, it looks really good. Async responses are logged correctly now with body messages. Until now, nothing seems broken.

Thanks for your effort, your quick reaction time and your greatly designed library, makes a lot of fun!

**Comment by whiskeysierra** [comment]
Glad to hear that it works for you.

We still have some TODOs on our wishlist for this, e.g. #17 (special setup for secure services) and I'm not 100% happy with the current separation of formatting and writing, but nothing concrete, more like a gut feeling.
