### ISSUE TITLE
Add custom request info

### ISSUE THREAD

**Issue by Djaler** [zalando/logbook#207]
For example, in requests I recieve some secret token, and I don't want it to be in logs. So I obfuscate it. But by token I get some not-secret internal ID. It is stored in Spring Authentication. Can I somehow add it to log output?

**Comment by whiskeysierra** [comment]
https://github.com/zalando/logbook#filtering is primarily designed for obfuscation, but you can modify the request in any way you like. You could write your own (raw) request filter that sets that ID as a fake header, for example.

**Comment by Djaler** [comment]
This is solve my problem, thank you!
