### ISSUE TITLE
Can "Incoming Request" log under info-level and "Outgoing Request" log under debug-level

### ISSUE THREAD

**Issue by wyzssw** [zalando/logbook#212]
It is a limitation of that logbook use one level in all type http-request scene，and it  is also confused for user to config logbook  level in properties meantime coordinate with log4j2.xml or logback.xml

**Comment by whiskeysierra** [comment]
> Can "Incoming Request" log under info-level and "Outing Request" log under debug-level

It's possible if you configure two different logbook instances and register one in a filter (incoming requests) and the other one within your client interceptor (outgoing request). You can even change the logger name for both.

> and it is also confused for user to config logbook level in properties meantime coordinate with log4j2.xml or logback.xml

Agreed, it's confusing. What you configure in logback/log4j2 is which level is enabled and where the output goes to. Logbook allows you to configure which log level to use. Some people prefer something other than TRACE (the default).

**Comment by whiskeysierra** [comment]
> It's possible if you configure two different logbook instances

Please note that this setup is not support by the spring boot starter. You'd need to set it up yourself.

**Comment by wyzssw** [comment]
Yes，i use  spring boot starter，i just want separate “Incoming Request” and “Outgoing Request”，
finally i custom the following code: logbook，httplogwriter，logbookAutoConfiguration，logbookproperties

**Comment by whiskeysierra** [comment]
@wyzssw I created #214 which will allow you to implement your own, see https://github.com/zalando/logbook/pull/214/files#diff-4b36d92a0056ed406ca149c6283fcf10

**Comment by whiskeysierra** [comment]
In short, you just need to implement `HttpLogWriter` and register it using Spring, that should be enough.

**Comment by wyzssw** [comment]
ok，it's good, thanks you very much，i will try it

**Comment by whiskeysierra** [comment]
@wyzssw I released the fix as 1.7.0 to central.
