### ISSUE TITLE
SecurityStrategy supporting 403

### ISSUE THREAD

**Issue by predragstefanovic** [zalando/logbook#219]
Hey, using Logbook with Spring Boot and found that request/response is not logged in case of 403, while 401 is logged. How about extending [SecurityStrategy](https://github.com/zalando/logbook/blob/master/logbook-servlet/src/main/java/org/zalando/logbook/servlet/SecurityStrategy.java) to support 403 as well?

**Comment by whiskeysierra** [comment]
Which layer generates the 403? Spring Security?

**Comment by whiskeysierra** [comment]
@lukasniemeier-zalando Do you remember why we have special support for 401 here and not 403?

**Comment by predragstefanovic** [comment]
Yes in this case it is coming from Spring Security layer, same one where 401s are generated.

**Comment by whiskeysierra** [comment]
@predragstefanovic I don't have a lot of time at my hands right now. If you'd be willing to open a pull request that adds support for 403 incl. a test, I'd be more than willing to get this merged and deployed quickly.

**Comment by whiskeysierra** [comment]
Released as 1.7.2.
