### ISSUE TITLE
Delayed logging

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/logbook#227]
Right now logbook makes two decisions by default:
1. Requests and responses are logged the moment they are happening
2. Either both, request and response, are logged nor none of them

A common use case would be to deviate from decision 1 and allow users to delay logging of request until response is available. This is show cased in https://github.com/zalando/logbook/blob/0fd12f2fe8a30147fee2e77cfc60c206929c31f3/logbook-core/src/test/java/org/zalando/logbook/DelayedResponseLogWriter.java. This should be supported more easily.

**Comment by shourien** [comment]
I see the code performing delayed logging where status code is at least 400. But does this mean all the 200 responses are ignored from logging? 

For example, the most common scenario in an industry would be to log every status code but also additionally log error responses for analysis purpose and mask success responses. Typically success responses tend to be large in number and hence logging them consumes a lot of system resources if logged with their body

This could also be helpful to collect metrics for indicating the total count of success & failure responses grouped by status codes and could be investigated further in case of failure responses if need be. These logs could help feed log analytics engines. 

Can this be achieved with logbook?

**Comment by whiskeysierra** [comment]
Closing in favor of #296
