### ISSUE TITLE
Extract specific fields to put into database

### ISSUE THREAD

**Issue by weiyang0** [zalando/logbook#229]
Hi,

I need to extract out certain fields from the requests/responses to put into a database.
For example if I want to have columns for "type", "method", "body" in the database and insert the respective fields from the logged requests/responses. Is that possible?

I was thinking of setting the values for these fields in a java object to be used for inserting the data to the database, but I first need a way to get these individual values from the logs. Or maybe there is another way of doing it?

**Comment by whiskeysierra** [comment]
You need to write a custom `HttpLogWriter`. The `Precorrelation`/`Correlation` parameters give you access to the original request/response from where you can derive stuff like type, method and body. If you completely ignore the formatted string (produced by a `HttpLogFormatter`) then you may implement a special one that just returns an empty string so you don't waste time producing a string that you don't need in the end.

**Comment by whiskeysierra** [comment]
> What does each one do? And which one gets called first?

https://github.com/zalando/logbook#formatting
https://github.com/zalando/logbook#writing
