### ISSUE TITLE
Enable HTTP Response Logging only for Error responses

### ISSUE THREAD

**Issue by shourien** [zalando/logbook#231]
Is it possible to log HTTP responses only for status codes other than 2xx? 
I would like the HTTP responses to be filtered for status codes 2xx and only log in case of 4xx/5xx etc. 

Is there a way, we can configure this in the spring boot application.yaml file under logbook properties?

**Comment by AlexanderYastrebov** [comment]
See https://github.com/zalando/logbook/issues/227

**Comment by whiskeysierra** [comment]
Closing as duplicate.
