### ISSUE TITLE
How to forward logbook logs to a different file?

### ISSUE THREAD

**Issue by fake230** [zalando/logbook#235]
I'm using logback with logbook and it's working, but i need to write logbook logs in one file and other application logs in the other. Any idea how to do this?
```
application.properties: 
logbook.write.level=INFO
logbook.write.category=http.wire-log
logbook.format.style=json
logging.level.http.wire-log=INFO
logging.level.=INFO
```

**Comment by whiskeysierra** [comment]
This is not specific to logbook. Depending on what you're using, I'd
suggest to look up how to do this in logback or log4j2.

**Comment by fake230** [comment]
Right, I solved this with logback and janino EvaluatorFilter. Thanks :)

**Comment by whiskeysierra** [comment]
There should be no need to use any filter. See https://stackoverflow.com/a/2489569/232539
