### ISSUE TITLE
How to log spring principal in request?

### ISSUE THREAD

**Issue by fake230** [zalando/logbook#236]
Is there any way to implement this?

**Comment by whiskeysierra** [comment]
This should work:

```java
final class PrincipalHttpLogFormatter implements HttpLogFormatter {

    private final JsonHttpLogFormatter delegate;

    PrincipalHttpLogFormatter(final JsonHttpLogFormatter delegate) {
        this.delegate = delegate;
    }

    @Override
    public String format(final Precorrelation<HttpRequest> precorrelation) throws IOException {
        final Map<String, Object> content = delegate.prepare(precorrelation);
        content.put("principal", getPrincipal());
        return delegate.format(content);
    }

    @Override
    public String format(final Correlation<HttpRequest, HttpResponse> correlation) throws IOException {
        final Map<String, Object> content = delegate.prepare(correlation);
        content.put("principal", getPrincipal());
        return delegate.format(content);
    }

    private String getPrincipal() {
        final Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        @Nullable final String principal = authentication.getName();
        return principal == null ? "anonymous" : principal;
    }

}
```

**Comment by whiskeysierra** [comment]
The only place to add this within logbook would be the spring-boot-starter, but I'm hesitant to do it, since it doesn't feel right to only support this for the json format.

**Comment by fake230** [comment]
Thank you but i don't understand where can i configure my logbook?
```
Logbook logbook = Logbook.builder()
    .condition(new CustomCondition())
    .rawRequestFilter(new CustomRawRequestFilter())
    .rawResponseFilter(new CustomRawResponseFilter())
    .queryFilter(new CustomQueryFilter())
    .headerFilter(new CustomHeaderFilter())
    .bodyFilter(new CustomBodyFilter())
    .requestFilter(new CustomRequestFilter())
    .responseFilter(new CustomResponseFilter())
    .formatter(new CustomHttpLogFormatter())
    .writer(new CustomHttpLogWriter())
    .build();
```
In which class i can do that, to apply my PrincipalHttpLogFormatter?

**Comment by whiskeysierra** [comment]
>     .formatter(new CustomHttpLogFormatter())

    .formatter(new PrincipalHttpLogFormatter(new JsonHttpLogFormatter())

**Comment by fake230** [comment]
I understood that, but where should i put that configuration in which class?

**Comment by whiskeysierra** [comment]
If you're using the spring boot starter, then you can just override that part of the auto configuration:

- https://github.com/zalando/logbook#spring-boot-starter
- https://github.com/zalando/logbook/blob/master/logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookAutoConfiguration.java#L204

```java
@Bean
public HttpLogFormatter httpLogFormatter(final ObjectMapper mapper) {
    return new PrincipalHttpLogFormatter(new JsonHttpLogFormatter(mapper));
}
```

**Comment by mariusstaicu** [comment]
@whiskeysierra how about in a webflux application ? 
it seems this does not work for a ReactiveSecurityContextHolder.

**Comment by thumatiramesh** [comment]
Hello folks,

I am banging my head from last today as I can't able to print the JSON log in the beautified format in the IntelliJ console rather it is printing the whole JSON in a single line. Can anyone please help me with this?

`{"type":"REQUEST","correlation":"d8d965d73ba59297","method":"POST","uri":"http://localhost:8080/students","host":"localhost","path":"/students","scheme":"http","port":"8080","headers":{"content-length":["714"],"content-type":["application/json"],"host":["localhost:8080"],"postman-token":["ed949fad-61cb-4ff9-8353-8b97046c0ed6"]},"body":{"type":"REQUEST","correlation":"9f85d3d4c9ca43d9","protocol":"HTTP/1.1","remote":"0:0:0:0:0:0:0:1","method":"POST","uri":"http://localhost:8080/students","host":"localhost","path":"/students","scheme":"http","port":"8080","headers":{"content-length":["82"],"content-type":["application/json"],"host":["localhost:8080"],"postman-token":["9c4454db-9905-4c68-bf21-deb44ecb2f62"]},"body":{"studentName":"Ramesh","studentAge":50,"address":"Nellore"},"principal":"ramesh"}}`

mail: rameshrathnat@gmail.com
