### ISSUE TITLE
How to log access token?

### ISSUE THREAD

**Issue by fake230** [zalando/logbook#266]
I need to log my access token, how do I remove obfuscate on it?
Tried this didn't work:
```
logbook.obfuscate.parameters=[]
```

**Comment by whiskeysierra** [comment]
An empty array is what we take as an indicator to fall back to the default. You either need to register your own query filter or alternatively you can just configure some bullshit parameter name that you never use, just so the array is not empty.

**Comment by fake230** [comment]
I think the problem is that I'm writing my logs in DB using custom Writer, so that's why logbook properties don't work for me anymore or at least don't apply for logs in DB...

**Comment by whiskeysierra** [comment]
Obfuscation/Filtering is independent of your writer. The logbook properties like `logbook.obfuscate.parameters` should still apply.

**Comment by whiskeysierra** [comment]
Is your access token a query parameter or a header?

**Comment by fake230** [comment]
I guess this is right way to do it:
```
@Bean
    public BodyFilter bodyFilter() {
        Set<String> properties = new HashSet<>();
        properties.add("refresh_token");
        return BodyFilters.replaceJsonStringProperty(properties, "XXX");
    }
```

**Comment by whiskeysierra** [comment]
This will obfuscate. I thought you wanted to disable it?

**Comment by fake230** [comment]
Actually I wanted exactly this, to obfuscate refresh and save access token. Ty for help :)

**Comment by whiskeysierra** [comment]
In that case your code is correct.
