### ISSUE TITLE
Add correlationId as configurable HTTP header in request and response

### ISSUE THREAD

**Issue by atrujillofalcon** [zalando/logbook#271]
## Detailed Description
Would be useful for some projects have the possibility of getting the correlationId in some way.

## Context

In applications with high log volume, it would be useful in case of receiving an error response to be able to search for the logs related to that request using grep, elastic, etc.

## Possible Implementation

Maybe add header in write method of Logbook instance.

## Your Environment

* Version used: 1.8.0
* Link to your project: NA

**Comment by whiskeysierra** [comment]
That's actually out of scope for logbook. What you're looking for is covered by zalando/tracer.
