### ISSUE TITLE
How to log request body instead of <multipart>?

### ISSUE THREAD

**Issue by fake230** [zalando/logbook#273]
I need to log my request body, but it keeps printing <multipart>. Body form is "form-data".

**Comment by whiskeysierra** [comment]
The default [`RawRequestFilter`](https://github.com/zalando/logbook/blob/master/logbook-core/src/main/java/org/zalando/logbook/RawRequestFilters.java#L18) delegates to the default [`BodyReplacer`](https://github.com/zalando/logbook/blob/master/logbook-core/src/main/java/org/zalando/logbook/BodyReplacers.java#L19) which in turn replaces multi part bodies with the string `<multi-part>`. If you need to override the default behaviour you need to configure your own `RawRequestFilter`.

**Comment by fake230** [comment]
Can you give me an example how to make @Bean RawRequestFilter cause I'm not sure how to use replaceBody when I need to save that body not replace it with some string. I'm using logbook-spring-boot-starter.

**Comment by whiskeysierra** [comment]
That should do the trick.

```java
@Bean
public RawRequestFilter rawRequestFilter() {
    return RawRequestFilter.none();
}
```

**Comment by fake230** [comment]
Yeah, that's first thing I tried but it shows nothing in log form body.
