### ISSUE TITLE
JSON formatted logs with truncated body are not valid JSON anymore

### ISSUE THREAD

**Issue by musiKk** [zalando/logbook#279]
## Description

By default the body of a request that is not authenticated is replaced with `<skipped>`. This is currently formatted in the logs as `{..., "headers":{...},"body":<skipped>}` which is not valid JSON.

This is an issue when you attempt to parse the lines as JSON in order to get structured details about the content.

## Expected Behavior

The line with a skipped body should be formatted as `{...,"body":"<skipped>"}`.

## Actual Behavior

See above.

## Possible Fix

I had a look at `JsonHttpLogFormatter`'s `tryParseBodyAsJson`. The issue seems to be that the string should be considered invalid JSON and the method should simply return the string as is. However, the `compactJson` method terminates early because `isAlreadyCompacted` only looks for the existence of new lines but not whether it is valid JSON at all. The string is then simply returned and later serialized as a raw value via `JsonBody` which foregoes adding the quotes.

I guess a fix could be to also check for valid JSON syntax in `tryParseBodyAsJson` or similar but I'm not sure what the best approach would be. Maybe the `isAlreadyCompacted` check can be removed; I don't know how much performance it saves. Parsing the content beforehand for syntactical validity might lead to duplicate parsing. Not sure.

## Steps to Reproduce

1. configure application to use `JsonHttpLogFormatter`
2. send unauthenticated request with payload

## Your Environment

* Version used: 1.8.0
* Link to your project:

**Comment by whiskeysierra** [comment]
You're absolutely correct. I identified this issue during #267, but I didn't fully understand the impact or scope. 

> I guess a fix could be to also check for valid JSON syntax in tryParseBodyAsJson or similar but I'm not sure what the best approach would be. Maybe the isAlreadyCompacted check can be removed

That would be a quick fix that would work.

> I don't know how much performance it saves.

Me neither, but from gut feeling I'd expect a lot, since we never produce pretty-printed JSON.

> Parsing the content beforehand for syntactical validity might lead to duplicate parsing. Not sure.

Even parsing it once, just to compact it already feels too much.

Long term I feel like the most robust solution would be to allow request and response filters to specify whether they are *destructive* or not, i.e. whether they modify the body in a way that it no longer conforms to the media type or not.

**Comment by whiskeysierra** [comment]
@musiKk Thanks for the thorough analysis! :tada:

**Comment by musiKk** [comment]
One other very simple idea (not taking the possible fix into account): There would also be the possibility of simply checking whether the body equals "<skipped>" and if yes, just returning it. This sounds like a hack at first but that could be alleviated bei either making that specific token part of the specification or make it configurable and use that configured value in the comparison. The latter sounds a bit like overkill to me though and would only be necessary if users create their own strategies.

**Comment by whiskeysierra** [comment]
The replacement string is pretty dynamic. We have a set of pre-defined one, but users are free to use their own: https://github.com/zalando/logbook/blob/master/logbook-core/src/main/java/org/zalando/logbook/BodyReplacers.java#L46

**Comment by whiskeysierra** [comment]
@musiKk I release the fix as 1.8.1 to central. Should be available soon. Thanks for raising the issue!
