### ISSUE TITLE
Introduce strategy pattern

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/logbook#296]
## Detailed Description

Right now the hard-coded default behavior consists of the following:
- log requests immediately
- log responses immediately
- log both, request and response, or neither of them

Being a bit more flexible in this regard would allow users to use different patterns/strategies, e.g.:
1. Log requests, but don't log responses
2. Log responses, but don't log requests
3. Only log requests if response status is not 2xx
4. Log requests without body, as long as response status is 2xx
5. Log some requests without body

## Context

#227, #231, #186, #183, #165, #336

## Your Environment

* Version used:
* Link to your project:

**Comment by emyphan** [comment]
@whiskeysierra 
regardings of the point 3:
"Only log requests if response status is not 2xx"

Is it possible now to filter to log only such requests?

**Comment by whiskeysierra** [comment]
No, because filtering only gives you the request, but not the response.

**Comment by FatihErdem** [comment]
Hi,

This feature will be awesome for us. We need `Only log requests if response status is not 2xx` this.
We build XML exporter which is export via API and our responses are too big, like 20 MB.

We don't want to log the response if we didn't get any error.

**Comment by whiskeysierra** [comment]
That's a primary use case for this. I have a draft on my machine and I might be able to push the branch so you can take a look. But it definitely needs some more polishing.

**Comment by FatihErdem** [comment]
@whiskeysierra hey, is there any progress for this feature?

**Comment by whiskeysierra** [comment]
> hey, is there any progress for this feature?

I dedicating time, but you shouldn't expect any release before christmas.

**Comment by whiskeysierra** [comment]
@FatihErdem You can take a sneak peek at https://github.com/zalando/logbook/tree/feature/2.x-redesign. It's not fully covered with tests nor is the documentation up to date, but you might be able to see where things are going.

**Comment by ranarula** [comment]
@whiskeysierra Quite keenly watching this feature to see the light of the day. 
With Christmas round the corner, any timelines around the release of this will be really helpful. 

In the meantime is there any recommendation (apart from something similar to #227) around doing specifically (1) and (2)
