### ISSUE TITLE
Add classifier to JSON formatted messages

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/logbook#31]
{
        "type": "request",
        "correlationId": "..."
    }

Possible values: `request` and `response`
Should be the very first property in the object to make it easier to read in scalyr

**Comment by lukasniemeier-zalando** [comment]
+1

**Comment by lukasniemeier-zalando** [comment]
Should this also be added to the HTTPLogger? First line?

**Comment by whiskeysierra** [comment]
> Should this also be added to the HTTPLogger? First line?

I updated pull request #33 for this. Output now looks like this:

```http
Request: 60cd7a7c-9acc-11e5-84a6-8b5eb91c6fbf
GET / HTTP/1.1
```

and a response:

```http
Response: 60cd7a7c-9acc-11e5-84a6-8b5eb91c6fbf
HTTP/1.1 200 OK
```
