### ISSUE TITLE
Getting going with Spring Boot 2

### ISSUE THREAD

**Issue by softwaregravy** [zalando/logbook#316]
Very possible I'm making a n00b mistake. Would appreciate any help you can provide. I'm trying to get this working with Logback, Tomcat, SpringBoot 2. I have created a trivial sample app that is not recording requests. 

https://github.com/softwaregravy/spring_boot_demo/

I'd really appreciate any help you can provide. Hopefully it's just a config or property that I'm missing. 

Thanks in advance.

**Comment by whiskeysierra** [comment]
You need to enable trace for logbook's logger. The other issue discusses this in detail, I believe.

**Comment by softwaregravy** [comment]
Sorry if I'm being dense. Can you spell it out for me a bit more? What do I need to put in my application.properties to get this working? Is there a logbook class that needs a logback configuration set?

https://github.com/softwaregravy/spring_boot_demo/blob/master/src/main/resources/application.properties

**Comment by whiskeysierra** [comment]
Logbook uses TRACE as a log level by default. Your config sets the root logger to DEBUG which does not include TRACE. Your options, depending on your preference:

1. Set logbook.write.level to DEBUG
2. Enable TRACE on the root logger
3. Enable TRACE on the org.zalando.logbook.Logbook logger

**Comment by softwaregravy** [comment]
Thank you, it was step #3 that is required to get this working.
