### ISSUE TITLE
Logging unauthorized request (error chain)

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/logbook#32]
Imagine the following filter chain configuration:

	Mapping filter: 'tracerFilter' to: [/*]
	Mapping filter: 'unauthorizedLogbookFilter' to: [/*]
	Mapping filter: 'springSecurityFilterChain' to: [/*]
	Mapping filter: 'authorizedLogbookFilter' to: [/*]

Let's say during the _springSecurityFilterChain_ execution an exception occures (internal server error). Sending an unauthorized request to a non-existing resource will result in a log output similar to the following:

	[org.zalando.security.filter] Getting token info from: https://secure.example.org/oauth2/tokeninfo
	[org.zalando.logbook.Logbook] {"correlation":"26004c4a-972a-42d9-8963-b61e237d7b67","remote":"127.0.1.1","method":"GET","uri":"/oauth2/tokeninfo?access_token=XXX","headers":{"Accept":["application/json, application/*+json"],"X-Flow-ID":["RET07vhrT32gzFPnAr3GaQ"],"Host":["secure.example.org"]}}
	[org.zalando.security.filter] Exception getting token info --> status 500
	[org.zalando.logbook.Logbook] {"correlation":"4cd11e6b-0ceb-4392-b607-c61114001e2e","remote":"0:0:0:0:0:0:0:1","method":"POST","uri":"/error","headers":{"Authorization":["XXX"],"Accept":["*/*"],"Host":["localhost:8080"],"Content-Length":["4"],"Content-Type":["text/plain;charset=UTF-8"]},"body":"abcd"}
	[org.zalando.logbook.Logbook] {"correlation":"4cd11e6b-0ceb-4392-b607-c61114001e2e","status":500,"headers":{"Content-Type":["application/json;charset=UTF-8"]},"body":{"status":500,"message":"Error in security filter.","path":"/lala"}}

As you can see

1. The real request is never logged
2. Since logbook was registered in error chain it has consumed the body of the request that was never authorized

Is there a way to detect during error chain execution that the request was never authenticated? Is there a way to still log the initial request (using the security strategy)?

**Comment by lukasniemeier-zalando** [comment]
Maybe we just add a note in the README that error dispatch should not be used in such cases (or "must be handled by the dev").

We should still do the logging in a `try-finally`.

**Comment by whiskeysierra** [comment]
- [ ] discourage use of ERROR dispatch in README
- [ ] remove ERROR dispatch from examples
- [ ] remove ERROR dispatch from Auto Configuration
- [ ] log responses in authorized filter in a `try-finally` block
- [ ] treat exceptions during chain execution in unauthorized filter as unauthorized requests (as long as the second filter didn't log them already? @lukasniemeier)

**Comment by lukasniemeier** [comment]
> as long as the second filter didn't log them already?

I am trying to identify the scenario: something after the authorized filter throws an exception, the authorized filter logs the response (bullet point 4), now the unauthorized filter would log the response again (due to the exception-as-unauthorized semantic). Correct?

If we would want to prevent such scenario the two filters would need to be _linked_ somehow, so that the unauthorized filter knows to be silent. Is this something special for this two-filter-security setup?

**Comment by whiskeysierra** [comment]
> I am trying to identify the scenario: something after the authorized filter throws an exception, the authorized filter logs the response (bullet point 4), now the unauthorized filter would log the response again (due to the exception-as-unauthorized semantic). Correct?

Correct.

> If we would want to prevent such scenario the two filters would need to be linked somehow, so that the unauthorized filter knows to be silent.

Exactly.

> Is this something special for this two-filter-security setup?

Yes, I think it would only apply in that case.

Communication between the filters can be done using request attributes.

**Comment by lukasniemeier-zalando** [comment]
Working on 
- [ ] log responses in authorized filter in a `try-finally` block
- [ ] treat exceptions during chain execution in unauthorized filter as unauthorized requests (as long as the second filter didn't log them already)

in https://github.com/lukasniemeier-zalando/logbook/tree/log-despite-exception

**Comment by lukasniemeier-zalando** [comment]
After looking into this again I think we should not continue with the proposed change to always log responses in the authorized filter. 

If there is a chain exception the state of the response that the filter will capture may not represent what is actually returned to the client. Other filters or the servlet container may decide to output something else. This is for example the case if you use Undertow and deactivate the error chain completely. `Logbook` would log an empty `200` response despite the client would actually receive a `500` (written by Undertow itself).

* If there is an exception after the authorized filter `Logbook` would log the request but no response. In the end users would need to leverage the logging of the container to see what is going on.
* If there is an exception before the authorized filter we could stick with the change of the unauthorized filter (exception as unauthorized) - `Logbook` would log a partial log.
* If there is an exception before the unauthorized filter... :wink: 

Therefore I am proposing to just implement the exception-as-unauthorized semantic.

**Comment by whiskeysierra** [comment]
> Therefore I am proposing to just implement the exception-as-unauthorized semantic.

Agreed.
