### ISSUE TITLE
Use org.slf4j.event.Level

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/logbook#321]
## Detailed Description

Instead of our custom level enum, we should rely on the public API of slf4j.

## Context

Reduce coupling for clients to our API.

**Comment by MALPI** [comment]
Hey @whiskeysierra I'd like to work on this if you are fine with that?

**Comment by whiskeysierra** [comment]
Yes, please. Just make sure you target `release/2.0.0` instead of `master`.
