### ISSUE TITLE
Support to Spring Webflux (reactive handlers)

### ISSUE THREAD

**Issue by atrujillofalcon** [zalando/logbook#331]
Logbook already has Spring support to traditional controllers model. In Spring Boot 2.X was introduced the reactive programming model with spring-webflux. Would be nice have Logbook support to this approach

See more details of Webflux here: https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#spring-webflux

## Context
I use Logbook for many micro-services in my job. We need to integrate Logbook in some reactive webflux services.

## Possible Implementation
By  WebHandler API? -> https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-web-handler-api

Thanks for your attention.
Greetings!

**Comment by whiskeysierra** [comment]
The traditional, blocking approach is supported via a Servlet Filter, which has the nice benefit of not being tied to Spring directly, i.e. it's useful for other frameworks as well.

Is there a usable, standardized API for nio that Spring is using?

**Comment by whiskeysierra** [comment]
https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-httphandler sounds like a good start. But also looks like there is no common API.

**Comment by atrujillofalcon** [comment]
I see your point. Spring Webflux is built on Project Reactor so we can built the reactive Filter using a common API like CompletableFuture's or RxJava because this libraries are compatible with Project Reactor. Could you give me more details on how the current Logbook integration with Spring works?

**Comment by whiskeysierra** [comment]
It's basically just a servlet filter, see https://github.com/zalando/logbook/tree/master/logbook-servlet, that we register using Spring's `FilterRegistrationBean`.

**Comment by atrujillofalcon** [comment]
Let me think of an approach, and I'll let you know if I can come up with a standard solution.

**Comment by atrujillofalcon** [comment]
A question, the logbook-core module is not tied to the servlet API? In this case, would it be possible to create a new module called spring-webflux or something similar?

**Comment by whiskeysierra** [comment]
> the logbook-core module is not tied to the servlet API

True.

> In this case, would it be possible to create a new module called spring-webflux or something similar?

Possible, yes. But I'd prefer a solution that is not tied to spring.

**Comment by fragonib** [comment]
+1

**Comment by gmariotti** [comment]
Not sure if this feature is still under consideration, but creating a Netty module would make this library easy to use also for Vert.x and Quarkus.

**Comment by whiskeysierra** [comment]
> Not sure if this feature is still under consideration, but creating a Netty module would make this library easy to use also for Vert.x and Quarkus.

That sounds promising then. Normally I'm opposed to bind myself to an implementation, but in this case it seems that Netty is pretty much the NIO framework of choice and we would cover the following application frameworks:

- Spring WebFlux
- Micronaut
- Vert.x
- Quarkus

**Comment by whiskeysierra** [comment]
Anyone here who has experience customizing the netty setup (preferably adding custom channel handlers) for Vert.x, Quarkus and/or Micronaut?

**Comment by whiskeysierra** [comment]
Turns out registering a custom ChannelHandler in using Spring WebFlux + Netty is easy. But for the others that seems to be hard:

- Micronaut: #629 
- Vert.x: https://stackoverflow.com/questions/59987216/how-can-i-add-a-custom-netty-channell-handler-in-vert-x/59989085#59989085
- Quarkus: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Adding.20a.20custom.20Netty.20ChannelHandler (no answer yet)

**Comment by gmariotti** [comment]
I think Quarkus is running on top of Vert.x so, it might have the same problem. If Micronaut is planning to support it, I would still go for a Netty module, otherwise doing a Spring WebFlux specific one is easier.

**Comment by whiskeysierra** [comment]
I already have a working Netty-based solution locally. I wanted to add tests for each framework. Spring works, but I stumpled for the other three.

**Comment by gmariotti** [comment]
That's great!! Is it something you can share already? I would be interested to see if I can create a similar module for Vert.x

**Comment by gmariotti** [comment]
That's great!! Is it something you can share already? I would be interested to see if I can create a similar module for Vert.x

**Comment by whiskeysierra** [comment]
I pushed my current branch here: https://github.com/zalando/logbook/tree/feature/netty/logbook-netty/src/main/java/org/zalando/logbook/netty

Maybe the existing API for vert.x already allows enough to register it? See http://www.julienviet.com/advanced-vertx-guide/#integrating-netty
