### ISSUE TITLE
SecurityStrategy logs twice

### ISSUE THREAD

**Issue by JanWaller** [zalando/logbook#334]
If I add a second LogBook Filter with Strategy.SECURITY, my calls resulting in 401 get logged twice. Once unfiltered with the whole body by the normal filter and once by the security filter.

I use Spring Boot without Spring Security.
What am I missing?

**Comment by whiskeysierra** [comment]
Can you try to remove spring-security from your classpath? That should fix it.

Proper fix within Logbook would be to not rely on `@ConditionalOnClass`:

https://github.com/zalando/logbook/blob/b2c5cc3edc92bdc2b17cc31d04927d05a4420879/logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookAutoConfiguration.java#L281

We should rather use `@ConditionalOnBean`.

**Comment by whiskeysierra** [comment]
> To clarify, I had an error with filter ordering. So my filter causing the 401 response was to low of precedence.

Our setup assumes that the security filter runs in between our two logbook filters, iirc. If your application logic or a filter further down the chain causes 401 then you will see the output twice. There is no easy fix that I can think of right now.

**Comment by JanWaller** [comment]
I actually have no Spring Security, so I added 
		@Bean
		@ConditionalOnProperty(name = "logbook.filter.enabled", havingValue = "true", matchIfMissing = true)
		@ConditionalOnMissingBean(name = "unauthorizedLogbookFilter")
		public FilterRegistrationBean<Filter> unauthorizedLogbookFilter(final Logbook logbook) {
			final Filter filter = new LogbookFilter(logbook, Strategy.SECURITY);
			final FilterRegistrationBean<Filter> registration = new FilterRegistrationBean<>(filter);
			registration.setName("unauthorizedLogbookFilter");
			registration.setDispatcherTypes(REQUEST, ASYNC, ERROR);
			registration.setOrder(100); // higher number then spring security (0)
			return registration;
		}
to my own configuration.

I like the idea of the security strategy to skip the body for 401 responses.
So my custom security filter causes 401 with the same precedence as spring security would.
For the actual request everything looks fine. However, the 401 causes a redirect to /error, which is again logged by logbook. This final logging happens twice. Once by both strategies.

**Comment by whiskeysierra** [comment]
> However, the 401 causes a redirect to /error, which is again logged by logbook. This final logging happens twice.

Error dispatch isn't really properly supported in logbook. You try to remove the ERROR dispatcher type from your customized version. That may help.

**Comment by JanWaller** [comment]
If I register both filter beans without the error dispatcher, I get the desired result

**Comment by sideisra** [comment]
I have a similar problem. Would it be a proper solution that the `authorizedLogbookFilter` (configured via logbook-spring-boot-starter) doesn't log any requests/responses where the response status is 401 or 403? Similar to `unauthorizedLogbookFilter` which only logs requests/responses with response status 401 or 403.

**Comment by whiskeysierra** [comment]
@sideisra That requires to delay the logging of the request until the response is available. #296 would support this as a custom strategy.

**Comment by whiskeysierra** [comment]
> For the actual request everything looks fine. However, the 401 causes a redirect to /error, which is again logged by logbook.

@JanWaller Maybe you can just exclude the `/error` url from Logbook?

**Comment by whiskeysierra** [comment]
> If I register both filter beans without the error dispatcher, I get the desired result

This will become the default as of #437
