### ISSUE TITLE
How to disable not OK request?

### ISSUE THREAD

**Issue by andbul** [zalando/logbook#336]
I am using logbook spring boot starter. The question is: how to disable logging of 404 request and others that have no status OK?

**Comment by whiskeysierra** [comment]
Sample, custom solution is show cases here https://github.com/zalando/logbook/blob/0fd12f2fe8a30147fee2e77cfc60c206929c31f3/logbook-core/src/test/java/org/zalando/logbook/DelayedResponseLogWriter.java.

Follow-up issue already in progress is #296.
