### ISSUE TITLE
Consider having a consistent naming of http headers

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/logbook#35]
Would probably make it easier to access them in an environment that doesn't honor the case-insensitive semantics of HTTP headers by default, e.g. scalyr log parsers?

**Comment by lukasniemeier-zalando** [comment]
I am bit conflicted. We already "fake" the request URI but it would be nice to stick to what we got from the header.

**Comment by whiskeysierra** [comment]
I think I agree. I basically prefer the upper title case variant, i.e. `If-Modified-Since` rather than the lower case version `if-modified-since`. But it's impossible to reliably transform lower case to upper e.g. `x-flow-id` could be `X-Flow-Id` or `X-Flow-ID`.

I guess we just drop this one.
