### ISSUE TITLE
Unable to print body of application/json post request 

### ISSUE THREAD

**Issue by arjunsawhney** [zalando/logbook#353]
I need to print the json body of my POST request.

But as of now I am only getting "body":"<multipart>" in my logs

 

My header type is "headers":{"accept":["application/json, text/plain, */*"]

 

I tried setting the logbook.servlet.form-request: OFF to PARAMETER, BODY and OFF, but still no change

 

I am using version 1.9.0 of logbook-spring-boot-starter

 

I read a few posts but I am still not able to fix the issue.

Please help me immediately thank you.

**Comment by whiskeysierra** [comment]
Are you talking about incoming requests? Are you using the servlet integration?

**Comment by arjunsawhney** [comment]
Yes I am talking about incoming POST requests. I am getting body:<multipart> in my zalando logs.

No I am not talking about servlet integration. 

When I post using a form on the front end, I face this issue.

**Comment by arjunsawhney** [comment]
My content type is multipart/form-data. Please help me with the fix for this issue. I need to log my raw request.

**Comment by whiskeysierra** [comment]
`multipart/*` content types are skipped by default. See 

https://github.com/zalando/logbook/blob/936deddc73ef6e82908a5db137480cbd6f952ee8/logbook-core/src/main/java/org/zalando/logbook/BodyReplacers.java#L32

You should actually see `"<multipart>"`. You can play around and register a custom `RawRequestFilter`.

**Comment by arjunsawhney** [comment]
Is there anyway I can turn off this BodyReplacer in my java code?

**Comment by arjunsawhney** [comment]
I understand that I have to create a custom RawRequestFilter.

Can you please give me a starting point of how to go about that? I have a Spring Boot project.

**Comment by whiskeysierra** [comment]
You can take a look how the default is constructed. Just start at the raw request filter class which should have a default value method.
