### ISSUE TITLE
logbook.include and logbook.exclude not working

### ISSUE THREAD

**Issue by ravidesai47** [zalando/logbook#370]
Using Spring Boot 1.5.12
With Logbook 1.10.0 Autoconfiguration

Setting values
logbook.include=/api/**
or
logbook.exclude=/actuator/**

have no effect on request response logging.

Somehow irrespective of what is setup on include and exclude property, library is logging all the request and responses to the log file.

**Comment by ravidesai47** [comment]
I tried to debug the flow but had no lucks to identify why its not working.

**Comment by whiskeysierra** [comment]
Both need to be a list, rather than a single string value.

**Comment by ravidesai47** [comment]
Thanks for the help.
After making it array, it is working as expected.
My bad here to provide list instead of single value to those properties.

**Comment by whiskeysierra** [comment]
Glad to see that it helped
