### ISSUE TITLE
Pretty-print json body

### ISSUE THREAD

**Issue by molexx** [zalando/logbook#372]
## Detailed Description
This is separate/additional to the log format. 'http' format works for me for showing headers, but when a body comprised of json is logged it's all in one line with no line breaks or indentation.
This would apply to the 'json' log format too, I'm not sure if in this case the entire output should be pretty-printed or just the body.

## Context
I work with a Spring Boot webservice which returns large bodies of deeply nested json, currently it is output as one long line so to make sense of it I need to copy/paste it into some editor and use its formatting tool.

**Comment by molexx** [comment]
Thanks.

I prefer the http output rather than json. It would be quite easy to add formatting to application/json bodies using Jackson at the point you linked to in `DefaultHttpLogFormatter` but I'm not sure that all users would want that.

I could subclass it for my own personal use - if you'd consider making the class non-final and some of the methods non-private - but that's not a contributable solution.

How about adding pluggable body formatters? A new interface `BodyFormatter`, property `Map<mime type, BodyFormatter>` and accompanying method `addBodyFormatter()` might be enough.

At a later date, if it's used enough, add a config property to provide the Map.

**Comment by whiskeysierra** [comment]
> if you'd consider making the class non-final and some of the methods non-private

I'm not a big fan of implementation inheritance. For now the pattern for *extending* formatters is to compose them and use the `prepare` methods directly (which are exposed). In order to allow a custom body formatting, we would need to expose some more of those internals.

**Comment by molexx** [comment]
Actually this was relatively easy to do by adding a BodyFilter. I'm using Spring Boot so I override the default BodyFilter bean with one that merges with it.

https://gist.github.com/molexx/0ef227a7f7299a6aacb04f9d44559af8

Feedback welcome :-)

**Comment by whiskeysierra** [comment]
That's a pretty good use of a `BodyFilter`. @nsmolenskii actually contributed a body filter that implements compacting, see #357. Might be even worth adding your pretty-print filter as a built-in filter, but that requires that we fully extract the compacting from the formatter, see https://github.com/zalando/logbook/pull/357#issuecomment-427754680.

**Comment by whiskeysierra** [comment]
See also #361.

**Comment by whiskeysierra** [comment]
> Are you intending on making the compacting body filter part of the default?

Yes.

> If so then I should probably not merge with the default otherwise the body will be compacted and then pretty-printed which is inefficient.

Yes, that's true.

> but I would want the max length filter which is currently set in `LogbookAutoConfiguration.java`.

I'd go with a pure programmatic configuration in that case:

```java
merge(prettyPrintJson(), truncate(80));
```

> Maybe an array of BodyFilters could be added to the config yaml?

I'd limit the configuration to a really small use case and let users go crazy with a programmatic configuration.

**Comment by whiskeysierra** [comment]
@molexx Would you care contributing your pretty print filter to the 2.x release?

**Comment by molexx** [comment]
Sure, but I'll be a few days. Feel free to copy/paste from my gist in the meantime.

**Comment by whiskeysierra** [comment]
No pressure, take your time.
