### ISSUE TITLE
JsonHttpLogFormatter should be resilient against malformed JSON

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/logbook#38]
Right now `JsonHttpLogFormatter#compactJson` tries to parse the request body based on the content-type. If you pass a malformed body (e.g. syntax error) an exception is thrown and the request will not be handled (and logged).

**Comment by whiskeysierra** [comment]
What is your expected behaviour? Don't include the body as json but rather escape it, like we do it with other content types?
