### ISSUE TITLE
Configurable location for .log files.

### ISSUE THREAD

**Issue by sameer-gupta** [zalando/logbook#380]
There is no option for specifying the location of the .log file

1). Currently logging happens only in Catalina.out file.

**Comment by whiskeysierra** [comment]
Logbook doesn't dictate the use of any particular logging framework but rather leaves it up to the users of the library to plugin any framework of their choice. See https://www.slf4j.org/. You'd need to configure either java-util-logging, log4j, log4j2, logback or any other.
