### ISSUE TITLE
Please add simple example with restTemplate

### ISSUE THREAD

**Issue by storytime** [zalando/logbook#383]
Please add simple example with restTemplate

**Comment by whiskeysierra** [comment]
Create an `HttpClient` as described in https://github.com/zalando/logbook#http-client. Pass that client instance to [`HttpComponentsClientHttpRequestFactory`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/client/HttpComponentsClientHttpRequestFactory.html#HttpComponentsClientHttpRequestFactory-org.apache.http.client.HttpClient-) which in turn you pass to the constructor of [`RestTemplate`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html#RestTemplate-org.springframework.http.client.ClientHttpRequestFactory-).

Feel free to propose a pull request for the README if you consider this to be missing.
