### ISSUE TITLE
logbook-okhttp: Unzip gziped responses before logging?

### ISSUE THREAD

**Issue by PascalSchumacher** [zalando/logbook#384]
I'm using logbook-okhttp version `1.11.1` and noticed that gziped json responses are logged as binary.

It would be great if responses would be logged unziped.

Not sure if this feature is in scope of logbook.

Thank you very much for providing this great libary! :+1:

**Comment by whiskeysierra** [comment]
How does OkHttp implement gzip decompression? As an interceptor? Can we somehow register the interceptor at a later phase after decompression?

**Comment by whiskeysierra** [comment]
Have you tried registering the interceptor as an application interceptor rather than a network interceptor?

**Comment by whiskeysierra** [comment]
I took a look at OkHttp and they register interceptors in a specify, pre-defined way:

https://github.com/square/okhttp/blob/af07e023f8d141d4a0cc165962b5f5cc997cff9c/okhttp/src/main/java/okhttp3/RealCall.java#L239-L248

The transparent handling of gzip is done within the `BridgeInterceptor`:

https://github.com/square/okhttp/blob/5b37cda9e00626f43acf354df145fd452c3031f1/okhttp/src/main/java/okhttp3/internal/http/BridgeInterceptor.java#L93-L111

But as you can see all network interceptors are running before, as part of the `chain.proceed` call.

https://github.com/square/okhttp/wiki/Interceptors describes the concept of application and network interceptors. So registering the interceptor as an application interceptor will workaround the problem you're facing.

If you care you can propose a pull request that mimics what OkHttp's own LoggingInterceptor provides which includes gzip decompression: https://github.com/square/okhttp/blob/master/okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java#L261

**Comment by PascalSchumacher** [comment]
Thank you for the information! I will look into it and try create a pull request.

**Comment by whiskeysierra** [comment]
I had some time at my hands and created a pull request. Fee free to take a look at #386.

It's missing some documentation though.

**Comment by PascalSchumacher** [comment]
Thank you very much for implementing this! 👍 😃

**Comment by PascalSchumacher** [comment]
I updated to 1.11.2 and it works like a charm. Thank you very much!
