### ISSUE TITLE
Log Request/Response after Filter

### ISSUE THREAD

**Issue by sameer-gupta** [zalando/logbook#385]
i have a filter configured in spring application to enrich a request with some additional information. I want to the logbook to log them also. right now it log the exact request which come to the server. i need to log request after it has passed for filter.

**Comment by whiskeysierra** [comment]
Is it a servlet filter?

**Comment by sameer-gupta** [comment]
yes, its a servlet filter (javax.servlet.Filter)

**Comment by whiskeysierra** [comment]
You need to make sure that the logbook filter is running after yours. We have a similar setup with Tracer (distributed tracing, adding headers) and Logbook:

https://github.com/zalando/tracer/blob/master/tracer-spring-boot-starter/src/main/java/org/zalando/tracer/spring/TracerAutoConfiguration.java#L222

https://github.com/zalando/logbook/blob/master/logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookAutoConfiguration.java#L292
