### ISSUE TITLE
Log request/response  not showing up

### ISSUE THREAD

**Issue by IBlasterus** [zalando/logbook#393]
Hi! :)

According to the README, I wrote dependency in pom.xml:
```
<dependency>
    <groupId>org.zalando</groupId>
    <artifactId>logbook-core</artifactId>
    <version>1.11.2</version>
</dependency>
```
Also wrote in application.properties:
```
logging.file=log/rest-sample.log
logging.level.org.springframework.web=DEBUG
logging.level.org.zalando.logbook: TRACE
```
But in my log-file request/response  not showing up.

My demo project (tree "filter"):
https://github.com/IBlasterus/rest-sample/tree/filter

Best regards, Alexandr.

**Comment by whiskeysierra** [comment]
You need the logbook-spring-boot-starter for your example.
