### ISSUE TITLE
logbook-spring-boot-starter missing in maven-central

### ISSUE THREAD

**Issue by matosf** [zalando/logbook#40]
Missing artifact here: http://repo1.maven.org/maven2/org/zalando/

Can you please deploy it there?

**Comment by whiskeysierra** [comment]
The current master is not (yet) deployed to central. We are currently working on two pull-requests and the (my) idea was to finish them first. If you can't wait that long, I'd suggest you deploy the current master to your local repo and check if it would suit your needs. I'd deploy it to central then.

**Comment by matosf** [comment]
ok, thanks.
