### ISSUE TITLE
Exclude request/response body 

### ISSUE THREAD

**Issue by ranarula** [zalando/logbook#400]
I am looking for suggestions and ideas to configure logbook to exclude request and/or response body.

Appreciate any pointers around the same.

**Comment by ranarula** [comment]
Implemented `PreparedHttpLogFormatter` wrapping `JsonHttpLogFormatter` to accomplish the same.

https://gist.github.com/ranarula/12ff9000012b168b152467a266809822

### Usage
```
 @Bean
 public HttpLogFormatter jsonFormatter(final ObjectMapper mapper) {
    return new CustomHttpLogFormatter(mapper, properties.logBody);
  }
```

**Comment by ranarula** [comment]
Thanks @whiskeysierra for your suggestion.

Not sure I am entirely sure how to accomplish that. Please provide some pointers around how to accomplish the same.

As a background - 
I am  struggling with getting to have the same performance metrics (from our Gatling test bench) as compared to a basic request/response filter I am trying to replace with Logbook. Logbook is consistently performing ~7% slower than the custom request/response filter.

The only difference I see is that the custom filter doesn't log request/response body. Even after adding the above formatter change there is no significant performance improvement. 

I am using a the defaults as per `LogbookAutoconfiguration` with a couple of overrides as below
```
  public static final Set<String> DEFAULT_REQUESTS =ImmutableSet.of("/actuator/**", "/**/ping", "/favicon.ico");
  public static final Set<String> DEFAULT_HEADERS =ImmutableSet.of("Authorization","x-gw-email",
        "x-gw-display-name", "x-gw-first-name", "x-gw-last-name", "x-gw-user-id");
   
   @Bean 
   public HeaderFilter headerFilter() {
    Set<String> headers = new HashSet<>(DEFAULT_HEADERS);
    headers.addAll(properties.getObfuscate().getHeaders());
    return headers.stream()
            .map(header -> HeaderFilters.replaceHeaders(header::equalsIgnoreCase, "XXX"))
            .collect(toList()).stream()
            .reduce(HeaderFilter::merge)
            .orElseGet(HeaderFilter::none);
  }

  @Bean
  public Predicate<RawHttpRequest> defaultCondition() {
    Predicate<RawHttpRequest> predicate = r -> true;

    DEFAULT_REQUESTS.stream()
        .map(Conditions::<RawHttpRequest>requestTo)
        .reduce(predicate, Predicate::and);
    return predicate;
  }

```

Profiling the app is not of great help as of now. 

Any suggestion to improve throughput will be helpful.

**Comment by whiskeysierra** [comment]
That should do the trick:

```java
@Bean
public RawRequestFilter rawRequestFilter() {
    return RawRequestFilters.replaceBody(request -> "");
}

@Bean
public RawResponseFilter rawResponseFilter() {
    return RawResponseFilter.replaceBody(response -> "");
}
```

Those two filters will actually disable the copying of all request/response bodies and hopefully it should give you some performance benefits.

**Comment by ranarula** [comment]
Thanks @whiskeysierra -

Earlier today I tried implementing a custom `Logbook` implementation which completely eliminated the `RawHttpRequest` & `RawHttpResponse` (and its corresponding filters) but it didn't helped.

Profiling the application was pointing to `HeadersBuilder` as it has lot of invocations for converting/filtering request/response headers (from `HttpServletRequest`/`HttpServletResponse`).
 This is not the case for the custom filter, as it simply iterates over the `HttpServletRequest/HttpServletResponse` and adds it to the StringBuilder. 

Snippet from the custom filter
```
private StringBuilder logHeaders(StringBuilder log, HttpServletRequest httpServletRequest,
      HttpServletResponse httpServletResponse, String prefix,
      List<String> headers, Integer requestNumber) {
    String header;
    boolean isLastHeader = false;

    if (headers == null) {
      return log;
    }

    Collections.sort(headers);
    ListIterator iterator = headers.listIterator();
    while (iterator.hasNext()) {
      header = (String) iterator.next();

      if(!iterator.hasNext()){
        isLastHeader = true;
      }

      log.append(requestNumber)
          .append(prefix)
          .append(header)
          .append(":")
          .append(" ");

      if (prefix.equals(REQUEST_PREFIX)) {
        log = logHeader(log, httpServletRequest.getHeader(header), isLastHeader);
      } else {
        log = logHeader(log, httpServletResponse.getHeader(header), isLastHeader);
      }
    }
    return log;
  }

  StringBuilder logHeader(StringBuilder log, String header, boolean isLastHeader){
    if(isLastHeader){
      return log.append(header);
    }
    else {
      return log.append(header).append(System.lineSeparator());
    }
}
```

Its surely not the best implementation (and hence the reason to rewrite along with logging in JSON) but it conveys my point.

**Comment by whiskeysierra** [comment]
Follow-up issue with performance improvements: #425
