### ISSUE TITLE
Why cannot merge request and response to one log record?

### ISSUE THREAD

**Issue by cnfn** [zalando/logbook#403]
Provide a solution that can merge request and response to one log record.
 
## Detailed Description

Now, the request and response log are separate two records. The `correlation` can correlate requests and responses. But it is not easy filter with special request URI and special response body at one time.

current example:
```
{"origin":"remote","type":"request","correlation":"fc8be625bbd4988e","protocol":"HTTP/1.1","remote":"0:0:0:0:0:0:0:1","method":"GET","uri":"http://localhost:8080/get?name=123","headers":{"accept":["*/*"],"host":["localhost:8080"],"user-agent":["curl/7.54.0"]}}
{"origin":"local","type":"response","correlation":"fc8be625bbd4988e","duration":1,"protocol":"HTTP/1.1","status":200,"headers":{"Content-Type":["application/json;charset=UTF-8"],"Date":["Mon, 31 Dec 2018 04:06:49 GMT"],"Transfer-Encoding":["chunked"]},"body":{"name":"123"}}
```

expect example: 
```
{"protocol":"HTTP/1.1","remote":"0:0:0:0:0:0:0:1","method":"GET","uri":"http://localhost:8080/get?name=123","duration":1,"status":200,"request":{"headers":{"accept":["*/*"],"host":["localhost:8080"],"user-agent":["curl/7.54.0"]}},"response":{"headers":{"Content-Type":["application/json;charset=UTF-8"],"Date":["Mon, 31 Dec 2018 04:06:49 GMT"],"Transfer-Encoding":["chunked"]},"body":{"name":"123"}}}
```

## Your Environment

* Version used: 1.11.2

**Comment by whiskeysierra** [comment]
You need to implement your own HttpLogWriter (https://github.com/zalando/logbook/blob/master/logbook-api/src/main/java/org/zalando/logbook/HttpLogWriter.java). Leave `writeRequest` empty and combine both within `writeResponse`. 

#295 and #296 will touch this topic and will make it easier to achieve.

**Comment by gmariotti** [comment]
Hi @whiskeysierra, apologies for commenting on an old closed issue, but could you share what would be the best way with the current version of logbook to log both request and response in a single entry?

**Comment by whiskeysierra** [comment]
You'd need to supply your own implementation of a Sink to do that. It has a
write method that accepts both the request and response. That's where you
can decide whether and how to log it as a single record.

**Comment by gmariotti** [comment]
Is that enough 🤔? I was looking into rewriting the https://github.com/zalando/logbook/blob/master/logbook-logstash/src/main/java/org/zalando/logbook/logstash/LogstashLogbackSink.java, would that mean that the first `write` can be empty and have the second `write` adding a `request` marker and `response` marker? Or do I also need to extend the `HttpLogFormatter`?

**Comment by whiskeysierra** [comment]
> Is that enough 🤔?

Yes, it is.

> I was looking into rewriting the https://github.com/zalando/logbook/blob/master/logbook-logstash/src/main/java/org/zalando/logbook/logstash/LogstashLogbackSink.java

Do you need logstash support? How exactly (in detail) do you want to log both, request and response?

> would that mean that the first `write` can be empty

Correct.

> and have the second `write` adding a `request` marker and `response` marker?

Markers are a completely different topic. Now we're getting into your concrete requirements in terms of log output etc. In terms of which methods you need to implement:

https://github.com/zalando/logbook/blob/79cd28a2af44ceca7199bc405c68ee4347e30cc2/logbook-api/src/main/java/org/zalando/logbook/Sink.java#L5-L20

Both `write` methods need to be implemented (since they're abstract), but you can just leave them empty. What you want is the `writeBoth` method. That gives you all interesting parameters directly.

**Comment by gmariotti** [comment]
What I'm trying to end up with is a single log entry with these fields
```json
{
  "request": { /* the request logged by logbook */ },
  "response": { /* the response logged by logbook */ },
  "message": "probably the logbook default",
  "context": { /* a json object added by me coming from a global variable */ }
}
```

So, my guess is that I can do something like
```kotlin
fun writeBoth(...) {
  val requestMarker = AutodetectPrettyPrintingMarker("request", formatter.format(correlation, request));
  val responseMarker = AutodetectPrettyPrintingMarker("response", formatter.format(correlation, response));

  log.trace(
    requestMarker, 
    responseMarker, 
    responseMessage(request, response), 
    StructuredArguments.value("context", Context.currentContext()
  )
}
```

is it something you think can be achieved by just implementing the `Sink.writeBoth` method?

**Comment by whiskeysierra** [comment]
Yes, that's the kind of pattern I had in mind when designing the API.

**Comment by gmariotti** [comment]
Thanks @whiskeysierra, I just tried it and it worked perfectly

**Comment by ukarlsson** [comment]
This is a full example in Kotlin

```
    class LogstashLogbackSink(private val formatter: HttpLogFormatter) : Sink {
        override fun isActive(): Boolean {
            return log.isTraceEnabled
        }

        override fun writeBoth(correlation: Correlation, request: HttpRequest, response: HttpResponse) {
            val requestMarker = RawJsonAppendingMarker("request", formatter.format(correlation, request));
            val responseMarker = RawJsonAppendingMarker("response", formatter.format(correlation, response));

            log.trace(
                responseMessage(request, response),
                requestMarker,
                responseMarker
            )
        }

        @Throws(IOException::class)
        override fun write(
            precorrelation: Precorrelation,
            request: HttpRequest
        ) {
            throw NotImplementedError()
        }

        @Throws(IOException::class)
        override fun write(
            correlation: Correlation,
            request: HttpRequest,
            response: HttpResponse
        ) {
            throw NotImplementedError()
        }

        private fun responseMessage(
            request: HttpRequest,
            response: HttpResponse
        ): String {
            val requestUri = request.requestUri
            val messageBuilder = StringBuilder(64 + requestUri.length)
            messageBuilder.append(response.status)
            val reasonPhrase = response.reasonPhrase
            if (reasonPhrase != null) {
                messageBuilder.append(' ')
                messageBuilder.append(reasonPhrase)
            }
            messageBuilder.append(' ')
            messageBuilder.append(request.method)
            messageBuilder.append(' ')
            messageBuilder.append(requestUri)
            return messageBuilder.toString()
        }

        companion object {
            private val log = LoggerFactory.getLogger(Logbook::class.java)
        }
    }
```
