### ISSUE TITLE
Provide SPI to body embedding

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/logbook#41]
Right now JSON bodies are embedded directly. Does it make sense to offer extensibility to this via a SPI?

**Comment by jhorstmann** [comment]
I don't think we need to expose this as an SPI at the moment. If someone wants special formatting it's possible to create a separate implementation of `HttpLogFormatter`. Our existing implementation is already highly opiniated.

**Comment by whiskeysierra** [comment]
I guess you're right.
