### ISSUE TITLE
is it possible to enable /disable filter dynamically

### ISSUE THREAD

**Issue by rahulsingh336** [zalando/logbook#436]
Hello,
I am using spring boot and I want to log request/response depending on time means to say If I want to debug further then I should be able to enable it and else it should be off.
How can I toggle between filter on/off at runtime without restarting app itself?

**Comment by whiskeysierra** [comment]
The filter is ultimately controlled by the underlying logger. So you if enable/disable the level that Logbook uses for logging it will start/stop buffering request/response bodies.

**Comment by whiskeysierra** [comment]
https://stackoverflow.com/questions/23434252/programmatically-change-log-level-in-log4j2

This should give you enough hints how to change the log level at runtime.

**Comment by rahulsingh336** [comment]
yes, It worked, Thanks a lot.
