### ISSUE TITLE
Obfuscation, inclue, exlude properties couldn't set from configuration

### ISSUE THREAD

**Issue by ilkin** [zalando/logbook#445]
logbook-spring-boot-starter doesn't work correct due to some properties doesn't set.

## Description

Obfuscate, inclue, exlude properties couldn't set from configuration due to LogbookProperties hasn't any setter methods for these properties. So LogbookAutoConfiguration  gets empty configuration from LogbookProperties for obfuscate, include, exclude

## Possible Fix
Add setter methods for obfuscate, include, exclude in LogbookProperties .

## Context

Couldn't set logbook.obfuscate.headers, logbook.obfuscate.parameters, logbook.include, logbook.exclude from application.properties in Spring Boot project. Manually added logbook bean configured with java api.

## Your Environment

* Version used: 1.13.0
* Spring Boot version: 1.5.2.RELEASE

**Comment by whiskeysierra** [comment]
Can you show your `application.properties` ?

**Comment by whiskeysierra** [comment]
I'm assuming you're running into the same issue as #282 and #370.

**Comment by ilkin** [comment]
> Can you show your `application.properties` ?

```
logbook.format.style=http
logbook.write.max-body-size=300
logbook.include=[/demo/**]
logbook.exclude=[/demo/monitor/**,/v2/api-docs,/configuration/ui,/swagger-resources,/configuration/security,/swagger-ui.html,/webjars/**]
logbook.filter.enabled=true
logbook.secure-filter.enabled=true
logbook.obfuscate.headers=[Authorization,x-auth-password,x-auth-token,X-Secret]
logbook.obfuscate.parameters=[access_token,password]
```

**Comment by whiskeysierra** [comment]
As I assumed, the problem is not with logbook but how spring represents lists in flat properties files. Either you use yaml or follow the suggestion in #282.
https://stackoverflow.com/a/47586180

**Comment by vineetgupta1991** [comment]
Can you try with the below format (without brackets)  : 

logbook.exclude=/demo/monitor/**,/v2/api-docs,/configuration/ui,/swagger-resources,/configuration/security,/swagger-ui.html,/webjars/**

It's working for me

**Comment by whiskeysierra** [comment]
I believe that depends on the Spring version.

**Comment by kedarjavalkar** [comment]
I had to do add to my application.properties
```
logbook.exclude[0]=**/v2/api-docs
logbook.exclude[1]=**/swagger-ui.html
logbook.exclude[2]=**/webjars/**
logbook.exclude[3]=**/swagger-resources/**
logbook.exclude[4]=**/csrf
logbook.exclude[5]=**/
```
I am using 

```
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.3.1.RELEASE</version>
```

Tip: Use `logbook.write.max-body-size=10` until you are able to exclude needed urls
