### ISSUE TITLE
Provide fast alternative for JSON compacting

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/logbook#446]
## Detailed Description

The compacting support we have is achieved by parsing and rewriting the whole body using a proper JSON parser. We are primarily interested in keeping the JSON output contained on a single line, so a faster option might be nice to have.

## Context

Performance overhead of the current solution.

## Possible Implementation

`json.replace("\n", "")`

**Comment by skjolber** [comment]
https://blog.jooq.org/2017/10/11/benchmarking-jdk-string-replace-vs-apache-commons-stringutils-replace/
