### ISSUE TITLE
Is it possible to Log downstream calls made by the application

### ISSUE THREAD

**Issue by SaiVishwas** [zalando/logbook#448]
We have a SpringBoot application which makes downstream calls to external services, would be possible to log these external calls as well?
## Detailed Description

We would like to log the downstream calls made to the external services. And later use those to mock the downstream calls. Would it be possible to achieve this using Logbook?
## Context

It would greatly help in running tests quickly, if the ability to mock downstream services is available.
## Your Environment

* Version used:
* Link to your project:

**Comment by whiskeysierra** [comment]
Yes, that's already built-in, but it depends on your client technology. What do you use to make requests? RestTemplate? Which HTTP library do you use under the hood?

**Comment by whiskeysierra** [comment]
Logbook has support for several client technologies:

- Apache HTTP Client: https://github.com/zalando/logbook#http-client
  - this can be used with Spring's RestTemplate in combination with HttpComponentsClientHttpRequestFactory
- JAX-RS: https://github.com/zalando/logbook#jax-rs
- OkHttp: https://github.com/zalando/logbook#okhttp-v3x

**Comment by SaiVishwas** [comment]
Hi, thanks a lot for your quick response.

I have two more queries :
1. Is it to also possible to mock the downstream calls (similar to how WireMock works)
2. Could you please provide any metrics related to the latency/performance degradation introduced by logbook

Thank you.

**Comment by whiskeysierra** [comment]
> 1. Is it to also possible to mock the downstream calls (similar to how WireMock works)

This is not related to Logbook anymore. Why not just use WireMock? https://github.com/rest-driver/rest-driver would also work. 

> 2\. Could you please provide any metrics related to the latency/performance degradation introduced by logbook

There is pending issue #99 to do this. One bottleneck was already identified, see #425. The next 2.x release should give you a lot more control to not buffer the request/response body in the first place. But it's not there yet and even then we still don't have any hard numbers. We use it at Zalando and the penalty is not noticeable or at least not significant enough.
