### ISSUE TITLE
replaceJsonStringProperty BodyFilter not working for values with quotation marks

### ISSUE THREAD

**Issue by gkonupek** [zalando/logbook#462]
## Description
I do the following:

> BodyFilter bodyFilter = BodyFilters.replaceJsonStringProperty(Collections.singleton("password"), "\<secret\>");

With this config, when I have a password which contains a quotation mark in it, e.g.: 

> abc"!?$123

 and I try to hide it, the filter will fail to do so, at least partially. So, when I do the following:

> bodyFilter.filter("application/json", "{\\"password\\": \\"abc\\\\\\"!?$123\\"}");

the output is the following:

> {"password": "\<secret\>"!?$123"}

So, most of the password is still visible - the whole part after the quotation mark. I'd expect the whole value to be hidden, i.e.:

>  {"password": "\<secret\>"}

## Expected Behavior

I'd expect the whole value to be hidden, i.e.:

>  {"password": "\<secret\>"}

## Actual Behavior

The output is the following:

> {"password": "\<secret\>"!?$123"}

## Possible Fix

The regex used for finding the property looks like this:

> final String regex = properties.stream().map(Pattern::quote).collect(joining("|"));
final Pattern pattern = Pattern.compile("(\"(?:" + regex + ")\"\\s*:\\s*)\".*?\"");

I think it might have to be improved somehow.

## Steps to Reproduce

Use the following code:
> BodyFilter bodyFilter = BodyFilters.replaceJsonStringProperty(Collections.singleton("password"), "\<secret\>");
bodyFilter.filter("application/json", "{\\"password\\": \\"abc\\\\\\"!?$123\\"}");

## Context

I wanted to hide sensitive data in logs which might contain special characters, like quotation marks.

## Your Environment

* Version used: logbook-core-1.13.0

**Comment by whiskeysierra** [comment]
This should fix it: https://regex101.com/r/Oi7Pe1/2

**Comment by whiskeysierra** [comment]
Maybe worth combining this with #304

**Comment by whiskeysierra** [comment]
https://github.com/zalando/logbook/pull/463#discussion_r266435503
