### ISSUE TITLE
Use UTF-8 in logbook-servlet

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/logbook#48]
[TeeRequest ](https://github.com/zalando/logbook/blob/d6b54b31b496e01e96c07411097563ae5f5e48a4/logbook-servlet/src/main/java/org/zalando/logbook/servlet/TeeRequest.java#L95 )and TeeResponse are using _ISO-8859-1_ if no charset is specified. Should we switch to the more widely used UTF-8? 

The HTTP 1.1 standard does not specify any default charset anymore (see [here](http://tools.ietf.org/html/rfc7231#appendix-B)) but refers to the media type's specific charset specifications (e.g. [UTF-8 for application/json](https://tools.ietf.org/html/rfc7159)).

**Comment by jhorstmann** [comment]
We should default the application/json mediatypes to utf-8, but I think in general iso-8859-1 is still the right fallback. The main reason beeing that it allows passthrough of binary data without decoding errors.

**Comment by whiskeysierra** [comment]
Isn't UTF-8 the default for json anyway?

**Comment by lukasniemeier-zalando** [comment]
Yes see my link :smirk:

**Comment by whiskeysierra** [comment]
Ok, so what exactly do we need to change?

**Comment by lukasniemeier-zalando** [comment]
As each [content-type](https://www.rfc-editor.org/rfc/rfc6657.txt) has its own rules for its charset (and determining the default one) I'd vote to just handle **application/json** as UTF-8 for now. If we want to go crazy we could open up and allow users to specify the charset heuristic.

**Comment by whiskeysierra** [comment]
I just checked the source code and realized that the request/response implementation for the `http-client` module actually fall back to UTF-8. Should we solve this in the core with a default method once and for all? (Only the application/json -> UTF-8 for now, not the generic heuristic).

**Comment by whiskeysierra** [comment]
> The HTTP 1.1 standard does not specify any default charset anymore (see here) but refers to the media type's specific charset specifications (e.g. UTF-8 for application/json).

The Servlet API has some strong opinion though https://wiki.apache.org/tomcat/FAQ/CharacterEncoding

**Comment by jhorstmann** [comment]
Let's take a step bake, why do we care about the charset at all? It's mainly used in `getBodyAsString`, which might be the wrong abstraction, instead we should try to do as much as possible either with Readers/InputStreams or byte arrays. The body as string is then used in two places as far as I can see:

 - By the BodyObfuscator. Maybe the responsibility of decoding should be in the Obfuscator itself, it could use a proper parser or a regular expression implementation optimized for byte arrays.

- For the actual logging. For the json case we could directly parse the byte array, again saving the decoding. With `text/*` content types we'd actually need the charset, which I think should still default to ISO-8859-1. That leaves other `application/*` or `image/*` content types, which I'm not really sure how to handle. I would not want arbitrary binary data in my logfiles.

**Comment by whiskeysierra** [comment]
> With text/* content types we'd actually need the charset, which I think should still default to ISO-8859-1.

What if the media type actually specifies a different one? We somehow need to transport that information to the one who is actually doing the decoding.

**Comment by jhorstmann** [comment]
> What if the media type actually specifies a different one?

I was just talking about the default. The BodyObfuscator interface would need to include the charset and maybe also the contenttype.

**Comment by whiskeysierra** [comment]
> The BodyObfuscator interface would need to include the charset and maybe also the contenttype.

[It does](https://github.com/zalando/logbook/blob/0edf155d69cc8017157c674d96ce202733337b79/logbook-core/src/main/java/org/zalando/logbook/BodyObfuscator.java#L26):

```java
@FunctionalInterface
public interface BodyObfuscator {

    String obfuscate(final String contentType, final String body);

    ...
```

**Comment by lukasniemeier-zalando** [comment]
I like #130 :tada: - but why now? Because (most of the) binary formats should be filtered out by default leaving (mostly) `UTF-8` content-types?

**Comment by whiskeysierra** [comment]
> but why now?

Because I want to get rid of issues :stuck_out_tongue_winking_eye: We used UTF-8 in the http client integration already. And I think UTF-8 has taken over, a long time ago.
