### ISSUE TITLE
SecurityStrategy collects response even if path is filtered

### ISSUE THREAD

**Issue by jayguidos** [zalando/logbook#480]
## Description
We have a few paths that are in the exclude list because they return large binary files and we do not want them logged in any way. The app runs with restricted heap  and we avoid OOM errors by returning the binary in chunks, and never try to cache the entire file in server memory.  This all appears to work properly, at least when the binary files are small enough to fit into heap memory. The excludes work and no logs are produced by logbook. 

Using the spring boot starter, the installed security filter (via the SecurityStrategy) wraps the request and the response unconditionally, and then initiates a logging action after the response is generated if the request was unauthorized.  For responses that generate a large body we run into OOM problems as the wrapped response is cached in memory, even though the request is authorized and no log output will be produced.

## Expected Behavior
The SecurityStrategy should pay attention to active excludes, and not attempt to wrap requests/responses if the path is in the exclude list.

## Actual Behavior
The response is wrapped unconditionally in a LocalResponse, and we hit OOM errors as LocalResponse tries to cache the entire body in memory.

## Steps to Reproduce
1. start test app with a very small heap
2. exclude a REST endpoint that will download a binary file larger than the configured heap
3. hit the REST endpoint to download the huge file
4. observe OOM stack traces in the console output

## Context
Get OOM errors when running an application with logbook enabled

## Your Environment
* Version used: 1.13.0

**Comment by jayguidos** [comment]
Now that I think on it, this problem is also a very good attack vector for a Denial Of Service attack.  An attacker could do an unauthorized request and issue a GET with a huge request body.  The SecurityStrategy would dutifully attempt to cache the request since there is no body size limit, and potentially force the process into an OOM situation even though the request would eventually be blocked.

**Comment by whiskeysierra** [comment]
> Now that I think on it, this problem is also a very good attack vector for a Denial Of Service attack. An attacker could do an unauthorized request and issue a GET with a huge request body. The SecurityStrategy would dutifully attempt to cache the request since there is no body size limit, and potentially force the process into an OOM situation even though the request would eventually be blocked.

That's actually the single purpose of the security strategy to prevent that attack vector, because it discards requests bodies. See https://github.com/zalando/logbook/blob/1.13.0/logbook-servlet/src/main/java/org/zalando/logbook/servlet/Strategy.java#L20

You issue is a duplicate but I can't find the other one right now. Can you try to run it with the latest master (install locally) and see whether it's already fixed? I'm planning on releasing a RC soon.

**Comment by jayguidos** [comment]
Yes it does discard the request, I was mistaken there, sorry about that. But my original problem remains in that responses are cached regardless of whether the URLs have been excluded.

I will try out master and see if my problem goes away.  I hate asking developers 'when is the release' because I hate being asked that myself :) but I am looking forward to an RC, the stuff on master looks very nice!

**Comment by whiskeysierra** [comment]
> But my original problem remains in that responses are cached regardless of whether the URLs have been excluded.

That's right.

> I will try out master and see if my problem goes away. I hate asking developers 'when is the release' because I hate being asked that myself :) but I am looking forward to an RC, the stuff on master looks very nice!

I just need to fix #484. I'd create the first RC then.

**Comment by jayguidos** [comment]
Ok I have tried out master on my project.  Glad to hear an RC is on its way :)

First, the upgrade to 2.0.0 was a little rocky, I think you should have some kind of 'how to migrate to 2.0' document, especially for SpringBoot users.  There are a number of changes in the spring boot starter auto config (which I think are good changes, you have made a lot of excellent improvements) and these changes break my build.  

The main one was that you changed logbook-spring-boot-starter from a JAR to a POM.  Since the 1.X is a JAR it is a valid dependency, but I had to change my POM to stop including it as a JAR.  I am not as up on SB  starter architecture as I should be, but I couldn't get the starter POM to work at all, even when I added it to my <dependencyManagement> section.  Don't you have to have at least a JAR with META-INF defined in it for a starter jar to work?  Anyway, switching to using logbook-spring-boot-autoconfigure instead seemed to work ok. 

The original problem of being forced to cache the response of URLs that are in the excluded list remains.  Is that your designed architecture?  I hope not, because the cached responses of the excluded URLs are blowing up my docker containers.  Is there some kind of work around I can try to stop this from happening?

**Comment by whiskeysierra** [comment]
> First, the upgrade to 2.0.0 was a little rocky, I think you should have some kind of 'how to migrate to 2.0' document, especially for SpringBoot users. There are a number of changes in the spring boot starter auto config (which I think are good changes, you have made a lot of excellent improvements) and these changes break my build.

Absolutely. I did that for [zalando/tracer](https://github.com/zalando/tracer/releases/tag/2.0.0-RC.0) and you can expect something close to that once 2.0.0-RC.0 drops.

> The main one was that you changed logbook-spring-boot-starter from a JAR to a POM. Since the 1.X is a JAR it is a valid dependency, but I had to change my POM to stop including it as a JAR. I am not as up on SB starter architecture as I should be, but I couldn't get the starter POM to work at all, even when I added it to my <dependencyManagement> section. Don't you have to have at least a JAR with META-INF defined in it for a starter jar to work?

Yeah, not exactly sure how that slipped in there. It has to be a jar to work, afaik.

> The original problem of being forced to cache the response of URLs that are in the excluded list remains. Is that your designed architecture? I hope not, because the cached responses of the excluded URLs are blowing up my docker containers. Is there some kind of work around I can try to stop this from happening?

That's odd. The `SecureLogbookFilter` is implemented as a special `Strategy` now.

https://github.com/zalando/logbook/blob/eb15e9adb829ec840dcc93358236b1d2c98dee3d/logbook-servlet/src/main/java/org/zalando/logbook/servlet/SecureLogbookFilter.java#L25

https://github.com/zalando/logbook/blob/eb15e9adb829ec840dcc93358236b1d2c98dee3d/logbook-servlet/src/main/java/org/zalando/logbook/servlet/LogbookFilter.java#L73-L77

In the end the `predicate` should decide whether to even call the strategy at all (first line):

https://github.com/zalando/logbook/blob/eb15e9adb829ec840dcc93358236b1d2c98dee3d/logbook-core/src/main/java/org/zalando/logbook/DefaultLogbook.java#L29-L40

I added a test for this right now. See #486. Can you share your configuration with the exclusion?

**Comment by jayguidos** [comment]
I *think* I tested it correctly, although your test looks valid, maybe I boo-booed.  But just to be sure, here is an example URL I want ignored:

```GET http://127.0.0.1:7072/c2s/v1/download/f1f5a217-66ee-455d-8a01-6802d7b60cfd/installer.sh```

And here are my exclusions: 

```
logbook:
  filter.enabled: true
  write.level: INFO
  exclude:
    - "/actuator/public/info"
    - "/c2s/*/clop/next/**"
    - "/c2s/*/clop/complete/**"
    - "/c2s/*/zones/**"
    - "/c2s/*/download/**"
    - "/server/v1/files/*/*"
```

Does that look reasonable?

**Comment by whiskeysierra** [comment]
> Does that look reasonable?

Absolutely! `/c2s/*/download/**` matches you URL. The double quotes are not necessary, but they shouldn't hurt either, I believe. Can you put a breakpoint in DefaultLogbook and see whether the predicate evaluates incorrectly or might even be constructed incorrectly?

**Comment by jayguidos** [comment]
Hi Willi, 

Ok I pulled your branch that had the springboot starter fix and ran a full test suite of my app.  I can confirm that the code works exactly as you say above, and my problem with meaty ignored responses blowing up my docker container is gone.

Looking forward to 2.0, keep up the good work.

Jay
