### ISSUE TITLE
Documentation for setting up body filter with Spring Boot Auto-configuration

### ISSUE THREAD

**Issue by mindhaq** [zalando/logbook#489]
The information of #298 should be part of the README, including necessary imports. It's possible to find it in closed issues, but that's not ideal.

A link to [LogbookAutoConfiguration](https://github.com/zalando/logbook/blob/master/logbook-spring-boot-autoconfigure/src/main/java/org/zalando/logbook/autoconfigure/LogbookAutoConfiguration.java) is also helpful to see what's possible outside `application.yml`.

**Comment by whiskeysierra** [comment]
https://github.com/zalando/logbook#spring-boot-starter already contains most pieces but should be extended.
