### ISSUE TITLE
Optimize body filters

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/logbook#493]
## Detailed Description

Registering multiple body filters of the same type, e.g. `replaceJsonStringProperty` works but is inefficient because they run sequentially. Optimizing those filters by merging them into one would be useful.

## Context

Improve performance by reducing raw body processing to the bare minimum.

## Possible Implementation

- [ ] New interface `MergeableBodyFilter` (extends `BodyFilter`)
- [ ] Make `replaceJsonStringProperty` a proper class, implementing `MergeableBodyFilter`
- [ ] Check for `instanceof ReplaceJsonStringProperty` and create a new instance using properties from this and the other filter
- [ ] Optimize mergeable body filters within `BodyFilter.merge(..)`

**Comment by skjolber** [comment]
So why the String part of replaceJson**String**Property, surely replacing other property types or even array and objects would be desirable? We're using a filter just like that (which parses and writes) now, not just for removing values we don't want to log, but also to reduce the size of the log statement (there is a max size).

**Comment by whiskeysierra** [comment]
> So why the String part of replaceJson**String**Property, surely replacing other property types or even array and objects would be desirable?

Replacing whole structures requires to properly parse the string. String properties can be detected and replaced quite easily and quickly using regular expressions. It's a simple trade-off between power and speed. Replacing string properties was solving the majority of cases without introducing a full second parsing of the body.
