### ISSUE TITLE
Support for filtering path

### ISSUE THREAD

**Issue by skjolber** [zalando/logbook#499]
Add hooks so that the path part of an URI can be filtered 

/a/b/c

prints as

/a/xxx/b

## Detailed Description
Something like the QueryFilter, but just for the path instead. 

## Context
Some of our legacy systems are passing values which we would like to filter out as part of the URI path.

## Possible Implementation
Something like the QueryFilter, but just for the path instead. We currently have an implementation which uses RequestFilter and a PathFilterHttpRequest (with delegate HttpRequest). The first attempt was using RawRequestFilter but that did not pan out.

## Your Environment
Mostly Spring with Java, Kotlin and Scala.

**Comment by whiskeysierra** [comment]
> We currently have an implementation which uses RequestFilter and a PathFilterHttpRequest (with delegate HttpRequest).

Sounds like a good approach. What's your issue with it? Too much custom code? Can you share/contribute it?

**Comment by skjolber** [comment]
A bit much custom code, and should fit in the project. I'll come up with a PR.

**Comment by skjolber** [comment]
See https://github.com/zalando/logbook/pull/513
