### ISSUE TITLE
Split up formatting and writing

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/logbook#5]
Right now the `HttpLogger` implementations do both, formatting the request/response data into some kind of text format and they also choose a concrete target for the data, usually a Slf4j Logger.

If we split those responsibilities up into two interfaces we could more easily add support for one of those concerns without changing the other.

As correctly mentioned by @lukasniemeier-zalando this could also mean we extract the condition (`shouldLog`) from the interface.

**Comment by lukasniemeier-zalando** [comment]
:+1: maybe we should take the chance and easen the creation of the creation of a fully configured ``LoggingFilter``
