### ISSUE TITLE
BOM missing logbook-logstash for 2.0.0-RC.1

### ISSUE THREAD

**Issue by binkley** [zalando/logbook#502]
## Description

When using the BOM in Gradle, the `logbook-logstash` dependency is not provided with a version number.  Gradle did, however, resolve the version as "2.0.0-RC.1" for `logbook-spring-boot-starter`.

## Expected Behavior
Using `logbook-logstash` dependency in Gradle with the BOM should not require an explicit version number.

## Actual Behavior
I needed to specify the version number explicitly in `build.gradle` for `logbook-logstash`.

## Possible Fix
Visual inspection confirms that `pom.xml` for `logbook-bom` does not mention `logbook-logstash`.  The fix should be simple, and add `logbook-logstash` to that `pom.xml`.

## Steps to Reproduce
In my Gradle (I expect a Maven `pom.xml` to work the same way):
```
ext {
    logbookVersion = "2.0.0-RC.1"
}

dependencyManagement {
    imports {
        mavenBom "org.zalando:logbook-bom:${logbookVersion}"
    }
}

dependencies {
    implementation "org.zalando:logbook-spring-boot-starter"

    // To reproduce, remove the version part:
    runtimeOnly "org.zalando:logbook-logstash:${logbookVersion}"
}
```

## Your Environment
* Version used: 2.0.0-RC.1
* Link to your project: https://github.com/binkley/spikes/tree/master/spring-boot-logging

**Comment by whiskeysierra** [comment]
Thanks for raising this. I opened PR #503 to fix it.
