### ISSUE TITLE
Logstash format produces unparseable JSON when strategy is body-only-if-status-at-least

### ISSUE THREAD

**Issue by binkley** [zalando/logbook#505]
## Description
Using `logbook-logstash` produces unparseable JSON, to wit:
```
{"origin":"local","type":"response","correlation":"914fb98fb08221ca","duration":63,"protocol":"HTTP/1.1","status":200,"headers":{"Cache-Control":["no-cache, no-store, max-age=0, must-revalidate"],"Content-Type":["application/json;charset=UTF-8"],"Date":["Wed, 15 May 2019 11:34:46 GMT"],"Expires":["0"],"Pragma":["no-cache"],"Transfer-Encoding":["chunked"],"X-B3-ParentSpanId":["abcdef0987654321"],"X-B3-Sampled":["0"],"X-B3-SpanId":["abcdef0987654321"],"X-B3-TraceId":["abcdef0987654321"],"X-Content-Type-Options":["nosniff"],"X-Frame-Options":["DENY"],"X-XSS-Protection":["1; mode=block"]},"body":}
```
Note the trailing "body" property at the end with no value after the colon.  This seems to be a byproduct of using "body-only-if-status-at-least" strategy with logstash output.

## Expected Behavior
There should be no "body" property on the emitted JSON when using "body-only-if-status-at-least" with logstash unless 4xx/5xx status code.

## Actual Behavior
There is a trailing "body" property without a value for 2xx status codes.

## Possible Fix
Offhand, perhaps `JsonHttpLogFormatter` should check in `prepareBody(HttpMessage)` if the strategy supports bodies, and if not, return `Optional.empty()`.  (There may be a cleaner way to do this, and I would need to check if the empty optional is enough to suppress generation of the "body" property in the emitted JSON.)

## Your Environment
* Version used: 2.0.0-RC.1

**Comment by whiskeysierra** [comment]
@skjolber Interested in investigating this?

**Comment by whiskeysierra** [comment]
@binkley Can you provide a minimal setup or test case?

**Comment by skjolber** [comment]
@whiskeysierra sure, probably tomorrow.

**Comment by skjolber** [comment]
The empty body vs no body (filtered or a HTTP method without a method) is kind of lost in translation when an empty byte-array is returned for null body. 

Validation and/or compacting of the JSON body should be done before logging it as raw JSON, so perhaps CompactingJsonBodyFilter could be integrated in the JsonHttpLogFormatter somehow?

**Comment by whiskeysierra** [comment]
> The empty body vs no body (filtered or a HTTP method without a method) is kind of lost in translation when an empty byte-array is returned for null body.

But neither of those two cases should produce incorrect JSON.

> before logging it as raw JSON

Where exactly is our issue right now? In `JsonHttpLogFormatter`?

**Comment by whiskeysierra** [comment]
We detect JSON based on content type and leave already compacted bodies as they are without further inspection. That leaves a known corner case if the content type is actually incorrect or rather not in line with the actual body. E.g. `application/json` with an empty body produces the missing JSON value in the output. We even have a test for that (disregard the name):

https://github.com/zalando/logbook/blob/f6321b4fcf3a726bb0135c6a1945350dcad9db2d/logbook-json/src/test/java/org/zalando/logbook/json/JsonHttpLogFormatterTest.java#L228

**Comment by skjolber** [comment]
Yes, in JsonHttpLogFormatter. Have a fix ready soon.

**Comment by skjolber** [comment]
See https://github.com/zalando/logbook/pull/508

**Comment by whiskeysierra** [comment]
The `JsonHttpLogFormatter` is embedding JSON bodies *as is*. It detects JSON based on the `Content-Type`. With the new strategies we may have no body but still the JSON content type. :boom:

**Comment by skjolber** [comment]
It will be possible to fake parts of or even full log statements with a bit of misconfiguration (no compactor / removal of newlines) when appending raw JSON.

**Comment by mindhaq** [comment]
Just here to leave a "me too".

```JSON
{
  "http": {
    "origin": "local",
    "type": "response",
    "correlation": "bf3095ae0aced15a",
    "duration": 3,
    "protocol": "HTTP/1.1",
    "status": 200,
    "headers": {
      "Connection": [
        "close"
      ],
      "Content-Type": [
        "application/vnd.spring-boot.actuator.v2+json;charset=UTF-8"
      ],
      "Date": [
        "Thu, 23 May 2019 12:27:15 GMT"
      ],
      "Transfer-Encoding": [
        "chunked"
      ]
    },
    "body":
  }
}
```
