### ISSUE TITLE
Travis build fails on Oracle JDK

### ISSUE THREAD

**Issue by skjolber** [zalando/logbook#514]
Build fails due to oracle JDK8 support has ended.

## Description

```
Installing oraclejdk8
$ export JAVA_HOME=~/oraclejdk8
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
install-jdk.sh 2019-05-02
Expected feature release number in range of 9 to 13, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
Your build has been stopped.
```
[Link](https://travis-ci.org/zalando/logbook/jobs/535738496)

## Expected Behavior
Builds

## Actual Behavior
Does not build

## Possible Fix
Change JDK - move on to AdoptOpenJDK 8?

## Steps to Reproduce
Run travis-ci build.

## Context
Submit PR.

## Your Environment
Build server / CI.

**Comment by whiskeysierra** [comment]
Had to switch to OpenJDK in other projects already because of this:

https://github.com/whiskeysierra/http-toolbox/blob/master/.travis.yml

**Comment by skjolber** [comment]
Ok, if switching to OpenJDK is acceptable, that is a minor change. Is this build of OpenJDK maintained though?
