### ISSUE TITLE
response is not logged if http status is 200/ok

### ISSUE THREAD

**Issue by andrasip** [zalando/logbook#531]
Response is not logged if http status is 200/ok 

## Description
Everything is logged properly except http responses with status code 200.

Most likely the problem is with the servlet 3.0 async support, that is enabled by default in spring boot autoconfiguration. It is not clear how status:200 is related to async.

As I see LogbookFilter skips writing log:

line 50:
{code} 
if (!request.isAsyncStarted()) {
            response.flushBuffer();
            stage.write();
        }
{code}

If async support of servletRegistrationBean is disabled manually, then all responses are logged properly. Of course, it might introduce performance degradation.

Do you think if it is possible to log all responses (included 200/OK) without disabling async support?

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment
logbook: v2.0.0-RC.1
Spring-boot: 2.1.3.RELEASE
* Version used:
* Link to your project:

**Comment by whiskeysierra** [comment]
Testing support for async dispatch is a bit tricky to be honest.

From my understanding an asynchronous request is dispatched twice and therefore runs through our filter twice:

1. dispatcher type REQUEST, async started = true
2. dispatcher type ASYNC, async started = false

We log the request in 1 and the response in 2. Would be nice if you contribute a test and/or preferably even a fix for this.

**Comment by andrasip** [comment]
The problem was related to obsolate servlet implementation (com.sun.xml.ws.transport.http.servlet.WSSpringServlet) used in our application.

After upgraded to org.springframework.ws.transport.http.MessageDispatcherServlet, the Logbook response logging works like a charm.
There is nothing to fix in Logbbok.

Please close this ticket.
Thank you.
