### ISSUE TITLE
Can we save logs into the DB?

### ISSUE THREAD

**Issue by RahulSDeshpande** [zalando/logbook#539]
Is there any facility in this library to save the logs into the desired database in a custom table format?

**Comment by whiskeysierra** [comment]
You can implement a custom `Sink`, but since requirements around databases are si different from one user to the next we don't provide a default implementation for that

**Comment by whiskeysierra** [comment]
Depending on whether you want to persist requests and responses individually or together in a single row, you may want to implement either:

https://github.com/zalando/logbook/blob/eb15e9adb829ec840dcc93358236b1d2c98dee3d/logbook-api/src/main/java/org/zalando/logbook/Sink.java#L11-L12

or 

https://github.com/zalando/logbook/blob/eb15e9adb829ec840dcc93358236b1d2c98dee3d/logbook-api/src/main/java/org/zalando/logbook/Sink.java#L14

**Comment by RahulSDeshpande** [comment]
Thanks, @whiskeysierra for the info!!
I will surely try.
