### ISSUE TITLE
Release Version 2.0

### ISSUE THREAD

**Issue by cch0** [zalando/logbook#549]
Would like to know the timeline for releasing 2.0.0 GA.

## Detailed Description

Current latest version is 2.0.0-RC.1

## Context

GA version is desired and needed.

**Comment by whiskeysierra** [comment]
We have some PRs in the pipeline that I'd still like to get into, e.g. #541

**Comment by julius-d** [comment]
I would also be very happy if you could release 2.0.0 GA! 🙂

**Comment by whiskeysierra** [comment]
Done! :tada: https://github.com/zalando/logbook/releases/tag/2.0.0
