### ISSUE TITLE
Logbook.strategy property is not defined in spring-configuration-metadata.json

### ISSUE THREAD

**Issue by Vity01** [zalando/logbook#552]
At this time (2.0 RC1) the new property `logbook.strategy` and its possible values is not defined in logbook-spring-boot-autoconfigure-2.0.0-RC.1.jar!/META-INF/spring-configuration-metadata.json  
This avoids hinting and proper validation in Intellij IDEA in the app configuration file.

## Expected Behavior
Property should be added and described

## Actual Behavior
Definition is missing.

## Possible Fix
Declare new property and its possible values.

**Comment by whiskeysierra** [comment]
Thanks for the issue. :handshake: 

I just opened #554 with a fix.
