### ISSUE TITLE
Noob example springboot

### ISSUE THREAD

**Issue by paul-eeoc** [zalando/logbook#557]
I read the issue https://github.com/zalando/logbook/issues/316 and I am just not getting it.  In the issue #316, it has a very [plain springboot project](https://github.com/softwaregravy/spring_boot_demo) with logbook entries in application.properties.  I am more interested in configuring via Java.

My springboot project has successfully use logbook 2.0.0-RC.1 and I see logbook entries in my log.  But  I am unable to understand how customize logbook using LogbookAutoConfiguration via Java.  

Consider this springboot java code:
```
@Configuration
public class LogbookConfig {
	@Bean
	LogbookAutoConfiguration logbook( ) {
		LogbookAutoConfiguration lac = new LogbookAutoConfiguration(null);
		//...more code here...
		return lac;
	}
}
```
Is this the correct approach?  Or am I to replace `LogbookAutoConfiguration` with `Logbook` as the bean?

Also, in your README.md, you have this code:
```
Logbook logbook = Logbook.builder()
    .requestFilter(replaceBody(contentType("audio/*"), "mmh mmh mmh mmh"))
    .responseFilter(replaceBody(contentType("*/*-stream"), "It just keeps going and going..."))
    .queryFilter(accessToken())
    .queryFilter(replaceQuery("password", "<secret>"))
    .headerFilter(authorization()) 
    .headerFilter(eachHeader("X-Secret"::equalsIgnoreCase, "<secret>"))
    .build();
```
the `contentType()` is undefined in 2.0.0-RC.1.  I am interested in the contentType part for responses.  I have responses that are either binary, xml or json.
This is what I want to do:   For the response, if the response is binary, just log the file size; if it is anything else (xml or json in this case), output the response to the log.

**Comment by whiskeysierra** [comment]
> But I am unable to understand how customize logbook using LogbookAutoConfiguration via Java.

Customization of the auto configuration is primary done via configuration (properties or yaml).

The `LogbookAutoConfiguration` is picked up by Spring automatically. If you don't want that you need to remove the `logbook-spring-boot-autoconfigure` artifact from your classpath.

If you want to configure Logbook manually in code, this should do the trick:

```java
@Configuration
public class LogbookConfig {
	@Bean
	Logbook logbook( ) {
	    return Logbook logbook = Logbook.builder()
	        .requestFilter(replaceBody(contentType("audio/*"), "mmh mmh mmh mmh"))
	        .responseFilter(replaceBody(contentType("*/*-stream"), "It just keeps going and going..."))
	        .queryFilter(accessToken())
	        .queryFilter(replaceQuery("password", "<secret>"))
	        .headerFilter(authorization()) 
	        .headerFilter(eachHeader("X-Secret"::equalsIgnoreCase, "<secret>"))
	        .build();
	}
}
```

> the `contentType()` is undefined in 2.0.0-RC.1.

https://github.com/zalando/logbook/blob/2.0.0-RC.1/logbook-core/src/main/java/org/zalando/logbook/Conditions.java#L52

> if the response is binary, just log the file size

What binary content types are you using?

Default values might already be good enough:

https://github.com/zalando/logbook/blob/60234b73689a0a174a107dd348d67d47d7718ae0/logbook-core/src/main/java/org/zalando/logbook/BodyReplacers.java#L18-L28

**Comment by paul-eeoc** [comment]
Your example code has this snippet:
```
 .responseFilter(replaceBody(contentType("*/*-stream"), "It just keeps going and going..."))
```
gives me an error in my IDE, however, if I replace `contentType` with `Conditions.contentType`, then it no longer complains that there is an error with contentType.
Regardless, the example is helpful.  Thank you.

**Comment by whiskeysierra** [comment]
> however, if I replace `contentType` with `Conditions.contentType`, then it no longer complains that there is an error with contentType.

You need a static import for the method.
