### ISSUE TITLE
Learning as I go with springboot

### ISSUE THREAD

**Issue by paul-eeoc** [zalando/logbook#560]
In your readme.MD, you have this code
```
@Bean
public BodyFilter bodyFilter() {
    return merge(
            defaultValue(), 
            replaceJsonStringProperty(singleton("secret"), "XXX"));
}
```
Where you can replace JSON values in the body with another.
I tried to 'play detective' with your source code to see if there is a XML replacer (I failed), so instead I am trying to take advantage of BodyReplacers instead.  I have requests AND responses with XML where the XML has snippets like this:
```
...
<attachments>
 <key>verybigfile.xlsx</key>
 <value>HLItgGURJRIlEA0iiieCsRRARs5rUSxRBaiGMppppzR5IwiiiQyEUVQTiPlNJBTT6Qj4kTMOWRttAsctzbZj1mb7f+G/g44CvwLvn/C9y3wDfA18BX8/wC+RNoXsD8HPgM+BY7A/wnwd6R9DPtvwEfAX4G/xLba/xzbZv8Q+BPwR+AD+A6D3wfeA96F/Qf</value>  
 <key>anotherfile.docx>
 <value>xxxxxx</value>
</attachments>
...
```
Where `<value>` can be very large.  So, based on my limited understanding of logbook, I think you would suggest,since this is in both request and response, to use BodyFilter like this:
```
	@Bean
	public BodyFilter bodyFilter() {
		
		final Pattern pattern = Pattern.compile("<value>.*</value>");		
		return BodyFilter.merge(
			BodyFilters.defaultValue(), ???);
	}
```
But I don't have a clue how to code the `???` part.

Finally, I have this bean in my project:
```
	@Bean
	Logbook logbook() {
		ResponseFilter doNotShowBinary = ResponseFilters.replaceBody(BodyReplacers.binary());
		HeaderFilter hfst = HeaderFilters.replaceHeaders("security_token"::equalsIgnoreCase, "xxx");
		Logbook logbook = Logbook.builder()
					.responseFilter(doNotShowBinary)
					.condition(Conditions.exclude(Conditions.requestTo("/sendmail/openimg/**")))
					.headerFilter(hfst)
				.build();
		return logbook;
	}
```
when I send a multipart form request, it gets logged as `<multipart>`.  I am assume that is a default that I can override.  But before I override it (where is the override?), can logbook show multipart request in a human-readable format? Multipart formdata can also have binaries so I would need to filter out too.

**Comment by whiskeysierra** [comment]
> But I don't have a clue how to code the `???` part.

This should do the trick. You may want to have something more sophisticated than this for XML incl. namespace awareness, etc. Using XSLT would properly be the better approach.

```java
private static BodyFilter replaceXmlValue(final String element, final String replacement) {
    final String tag = Pattern.quote(element);
    // TODO regex properly is too 
    final Pattern pattern = Pattern.compile("<" + tag + ">.*</" + tag + ">");greedy!
    final UnaryOperator<String> delegate = body -> ;

    return (contentType, body) -> {
        // TODO there are multiple well-known media types for XML and they might have parameters
        // TODO implement isXml as sophisticated as you need it
        if (isXml(contentType)) {
            return pattern.matcher(body)
                    .replaceAll("<" + tag + ">" +replacement + "</" + tag + ">")
        }

        return body;
    }
}
```

```java
@Bean
public BodyFilter bodyFilter() {
	return BodyFilter.merge(
		BodyFilters.defaultValue(), replaceXmlValue("value"));
}
```

> I am assume that is a default that I can override. But before I override it (where is the override?)

Yes. Register a custom `RequestFilter` bean.

> can logbook show multipart request in a human-readable format? Multipart formdata can also have binaries so I would need to filter out too.

Not out of the box, no. You'd need to parse the multipart body to treat parts differently. The underlying model of Logbook is pretty simplistic and treats the whole body as a `byte[]`. We don't use multipart bodies, hence we have no first-class support for it.

**Comment by whiskeysierra** [comment]
Feel free to re-open and continue commenting.

**Comment by paul-eeoc** [comment]
I think this issue is due to my lack of understanding springboot than logbok.  Consider this pseudo-code:
```
@Configuration
public class LogbookConfig {

@Bean
Logbook logbook() {
	ResponseFilter doNotShowBinary = ResponseFilters.replaceBody(BodyReplacers.binary());
	HeaderFilter hfst = HeaderFilters.replaceHeaders("security_token"::equalsIgnoreCase, "xxx");
	Logbook logbook = Logbook.builder()
				.responseFilter(doNotShowBinary)
				.condition(Conditions.exclude(Conditions.requestTo("/sendmail/openimg/**")))
				.headerFilter(hfst)
			.build();
	return logbook;
}

@Bean
public BodyFilter fileFilter() {
	return BodyFilter.merge(
			BodyFilters.defaultValue(), replaceXmlValue("value"));
}

private static BodyFilter replaceXmlValue(final String element) {
	...code...
}
```
where I have two beans.   I was led to believe that this is good coding practice to have multiple small beans. I thought that would work, since I didn't try to override the bodyfilter in my logbook() method.   Instead I had to have just one bean and integrate fileFilter() into the first bean.  So it's like this:
```
@Configuration
public class LogbookConfig {

@Bean
Logbook logbook() {
	ResponseFilter doNotShowBinary = ResponseFilters.replaceBody(BodyReplacers.binary());
	HeaderFilter hfst = HeaderFilters.replaceHeaders("security_token"::equalsIgnoreCase, "xxx");
	Logbook logbook = Logbook.builder()
				.responseFilter(doNotShowBinary)
				.condition(Conditions.exclude(Conditions.requestTo("/sendmail/openimg/**")))
				.headerFilter(hfst)
				.bodyFilter(fileFilter())
			.build();
	return logbook;
}

private BodyFilter fileFilter() {
	return BodyFilter.merge(
			BodyFilters.defaultValue(), replaceXmlValue("value"));
}

private static BodyFilter replaceXmlValue(final String element) {
	...code...
}
```
Is this good programming practice or noob programming practice?

**Comment by whiskeysierra** [comment]
Having multiple beans registered in your spring application context would make sense if you would let the `LogbookAutoConfiguration` create the `Logbook` instance for you. Since you're creating the instance yourself it's actually better to not register filters as beans since they just pollute your application context without the need. Your private methods that you just call from your `logbook` method in your 2nd example is fine.

**Comment by paul-eeoc** [comment]
Thank you for your patience.  I am humbled by it.  With my project, I either respond as json or XML. With your previous help, I prettified the xml responses.  Now I am trying to prettify json responses. I try to re-use what you have (`PrettyPrintingJsonBodyFilter`):
```
	@Bean
	Logbook logbook() {
		ResponseFilter doNotShowBinary = ResponseFilters.replaceBody(BodyReplacers.binary());
		HeaderFilter hfst = HeaderFilters.replaceHeaders("security_token"::equalsIgnoreCase, "xxx");
		Logbook logbook = Logbook.builder()
					.responseFilter(doNotShowBinary)
					.condition(Conditions.exclude(Conditions.requestTo("/sendmail/openimg/**")))
					.headerFilter(hfst)
					.bodyFilter(fileFilter())
					.bodyFilter(prettyXmlFilter())
					.bodyFilter(prettyJsonFilter())
				.build();
		return logbook;
	}

	public BodyFilter prettyXmlFilter() {
		return BodyFilter.merge(
				BodyFilters.defaultValue(),prettyXml());
	}

	private BodyFilter prettyJsonFilter() {
		return BodyFilter.merge(
				BodyFilters.defaultValue(), prettyJson());
	}

	final static BodyFilter json = new PrettyPrintingJsonBodyFilter();

	private BodyFilter prettyJson() {
		return (contentType, body) -> {
			//no need to check contentType, the json filter checks it.
			String body1 = json.filter(contentType, body);
			return body1;
		};
	}
```
I checked the variable `body1` and it does have linefeeds and indenting but the log still show it as one line.

**Comment by whiskeysierra** [comment]
> Thank you for your patience. I am humbled by it.

My pleasure.

> I checked the variable `body` after the filter; it does have linefeeds and indenting but the log still show it as one line.

You have two issues in your remaining setup:

1. You're combining body filters in a sub-optimal way
   - `prettyXmlFilter` and `prettyJsonFilter` both merge in the [*default* filters](https://github.com/zalando/logbook/blob/master/logbook-json/src/main/resources/META-INF/services/org.zalando.logbook.BodyFilter), so you have them twice in your chain
   - you don't need to use `merge` at all, you could just name them one after another
2. You're using the default body filters which actually compact json

This should do what you want:

```java
@Bean
Logbook logbook() {
	return Logbook.builder()
			.responseFilter(replaceBody(binary()))
			.condition(exclude(requestTo("/sendmail/openimg/**")))
			.headerFilter(replaceHeaders("security_token"::equalsIgnoreCase, "xxx"))
			.bodyFilter(fileFilter())
			.bodyFilter(prettyXml())
			.bodyFilter(prettyJson())
			.build();
	}
```

None of the private methods is needed in this version.

**Comment by paul-eeoc** [comment]
I made the change, and it still outputs as one line.  Here is the full code:
https://gist.github.com/paul-eeoc/f41f79349dcffd2b0c1ec873e1f0f0f4

And here is the full output of a multipart request with a json response:
https://gist.github.com/paul-eeoc/c7c0c51b0410871027bd45726e6a6d38

**Comment by whiskeysierra** [comment]
> I made the change, and it still outputs as one line. Here is the full code:

https://gist.github.com/paul-eeoc/f41f79349dcffd2b0c1ec873e1f0f0f4#file-logbookconfig-java-L62

Still uses the default value

**Comment by paul-eeoc** [comment]
By changing
```
	.bodyFilter(fileFilter)
```
to 
```
	.bodyFilter(replaceXmlValue("value"))
```
did the trick.  Thanks!
