### ISSUE TITLE
Logbook BOM is forcing Spring version in a project using it

### ISSUE THREAD

**Issue by fragonib** [zalando/logbook#562]
## Description
When a project imports LogBook BOM version 1.13.0 in a `dependencyManagement` section like this:

```xml
<dependencyManagement>
      <dependency>
          <groupId>org.zalando</groupId>
          <artifactId>logbook-bom</artifactId>
          <version>1.13.0</version>
          <type>pom</type>
          <scope>import</scope>
      </dependency>
</dependencyManagement>
```
Then Spring version downgrades from 5.1.8 to 5.1.4

Is this by design? Is it a bug?

## Expected Behavior
Spring version is kept on same version as defined by SpringBoot parent pom (5.1.8)

## Actual Behavior
Downgrade of Spring version from 5.1.8 to 5.1.4

## Possible Fix
Maybe Logbook BOM shouldn't inherit from Logbook parent POM, because it contains a _dependencyManagement_ section and will be imported too. In that case this ends up redefining Spring version.

## Steps to Reproduce
1. Start with a project with a main POM that sets Spring version to 5.1.8, for instance this one that uses SpringBoot:
```
     <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.6.RELEASE</version>
    </parent>
```

2. Import LogBook BOM: 
```
    <dependency>
           <groupId>org.zalando</groupId>
           <artifactId>logbook-bom</artifactId>
           <version>1.13.0</version>
           <type>pom</type>
          <scope>import</scope>
    </dependency>
```

3. Launch `mvn dependency:tree`

3. Console output shows project it's using wrong version of Spring:
``` 
INFO] |  |  \- org.springframework:spring-context:jar:5.1.4.RELEASE:compile
```

**Comment by whiskeysierra** [comment]
> Maybe Logbook BOM shouldn't inherit from Logbook parent POM, because it contains a _dependencyManagement_ section and will be imported too. In that case this ends up redefining Spring version.

Interesting. I wouldn't expect that this takes precedence over your own import, but I guess Maven's rules about priorities are not the same for imports.

Would you mind creating a PR for this?

**Comment by millgi** [comment]
It also set spring-webmvc scope to test (at least). So adding spring-boot-starter-web does not work as expected without explicitly adding spring-webmvc to the compile classpath.

**Comment by whiskeysierra** [comment]
If two dependencies are in conflict because they both have the same transitive dependency in the same depth (of the dependency tree) but they differ in version or scope then the conflict is resolved by picking the one that came first in your pom. Maybe that helps.
