### ISSUE TITLE
Add Spring Boot support for predicate

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/logbook#57]

**Comment by matosf** [comment]
There should be possibility to, on top of a predicate bean definition, it would be nice to be able to configure simpler cases of "ignore the endpoints", something like this:

logbook:
    ...
    ignore:
      - /health
      - /info

**Comment by whiskeysierra** [comment]
What would be your exception in regards to query parameters? If you list `/health` as ignored, would you assume the following URL to be ignored or not? `/health?check`

**Comment by whiskeysierra** [comment]
Other question, let's say we look for a bean of a specific type or name to use a predicate. If the config in addition contains the `ignore` section, would you expect to combine them?

**Comment by matosf** [comment]
@whiskeysierra 
I think it would be enough if we could use ant-style patterns (i.e. AntPathRequestMatcher), like Spring Security.

I would expect that the final configuration would be a combination of both.

**Comment by whiskeysierra** [comment]
> I think it would be enough if we could use ant-style patterns

That's a great idea!
