### ISSUE TITLE
Enable log request body and not log response body when status < 400

### ISSUE THREAD

**Issue by dragontree101** [zalando/logbook#577]
i want to print request body and don't print response body when status < 400, but when i choose BodyOnlyIfStatusAtLeastStrategy only both print  request/response body or both not print request/response body

## Detailed Description

when i set properties 
```
logbook:
  strategy: body-only-if-status-at-least
  minimum-status: 400
```
when i response status is 200, logbook both not print request body param and response body
and when i response status is 500, logbook both print request body param and response body

i want set when response status is 200 , logbook print request body param and not print response body

## Your Environment

* Version used:
2.0.0-RC1
* Link to your project:

**Comment by whiskeysierra** [comment]
There is no default strategy built-in that can do that. But three while idea behind strategies is that you can easily define your own ones. You just need to implement the Strategy interface yourself and register it as a bean.

**Comment by dragontree101** [comment]
thanks
does logbook official plan support this strategy(request log and response log use different strategy) in future？

**Comment by whiskeysierra** [comment]
Not yet
