### ISSUE TITLE
Obfuscation not working on okhttpclient request with strategy

### ISSUE THREAD

**Issue by hcapitaine** [zalando/logbook#581]
Cannot obfuscate header when using BodyOnlyIfStatusAtLeastStrategy on OkHttpClient
## Description
When setting up logbook on a OkHttpClient with strategy, BodyOnlyIfStatusAtLeastStrategy, it calls request.withoutBody() to write the messages. 
The problem is the obfuscation has been made previously on the current request headers but not on the cloned request returned by request.withoutBody(). 

BodyOnlyIfStatusAtLeastStrategy:28 method write()

## Expected Behavior
If I set up header Authorization to be obfuscate for example, obfsucation should appear in the written log.

## Actual Behavior
Obfuscation is not taken into account on OkHttpClient

**Comment by whiskeysierra** [comment]
Does this affect `logbook-okhttp` or `logbook-okhttp2`? Can you prepare a test?

**Comment by hcapitaine** [comment]
Here it is:
https://gist.github.com/hcapitaine/61c59cc92615d6e6a7974c7af5a889fc

And it affects logbook-okhttp.

**Comment by whiskeysierra** [comment]
Thanks a lot! I'll take a look

**Comment by hcapitaine** [comment]
Thank you for correcting so quickly. Do you plan any release? even in RC?

**Comment by whiskeysierra** [comment]
Just finished it: https://github.com/zalando/logbook/releases/tag/2.0.0-RC.2

Thanks for raising the issue and contributing the test!

**Comment by hcapitaine** [comment]
Will it be published to maven central? I could test it further.

**Comment by whiskeysierra** [comment]
Yes, but usually that takes up to a couple of hours until sonatype properly distributes it.
