### ISSUE TITLE
PUT method with no body

### ISSUE THREAD

**Issue by hcapitaine** [zalando/logbook#585]
When a PUT request has no body set, logbook throw an error

## Description
In module logbook httpclient, when a PUT request is logged, it expects a body to be present. But in some cases, a PUT request can have no body (especially true when creating indices on elasticsearch)

  

## Expected Behavior
Just treat a PUT request with no body set as a request without body

## Possible Fix
https://gist.github.com/hcapitaine/0e92994ceb1706a166c2a7db5df9332c

Method withBody:134, add conditional test and treat it as withoutBody when no body set.

## Steps to Reproduce
See this test as an example:
https://gist.github.com/hcapitaine/f05a522dce89fa9d961a3610df19db86

**Comment by whiskeysierra** [comment]
Good catch!

**Comment by whiskeysierra** [comment]
I just released a fix as [2.0.0-RC.3](https://github.com/zalando/logbook/releases/tag/2.0.0-RC.3)

**Comment by whiskeysierra** [comment]
Thanks for the issue and the test! :tada:

**Comment by hcapitaine** [comment]
Thanks for the release. I'm going to test it.

Le ven. 23 août 2019 à 20:35, Willi Schönborn <notifications@github.com> a
écrit :
