### ISSUE TITLE
Logbook removes body from response

### ISSUE THREAD

**Issue by Breeki32** [zalando/logbook#603]
I encountered an issue in combination with CXF and Spring Security where the body of an response vanishes (=is null) when using Logbook.

## Description
In Logbook version 1.13.0 the body of the response vanishes when the Writer Level is set to something that would lead to requests not getting logged (=INFO).

Using Logbook version 2.0.0-RC.33 the behaviour is inverted, e. g. the body disappears when the level would actually log it (=TRACE).

The Logbook Writer Level setting influences this behaviour. 

The setup is very simple:

The Spring Boot App exposes a CXF service list under /services. This resource is accessible for everyone (permitAll).

GET requests to /services do not yield any body when logging is turned _off_ by changing the log level of Logbook. When I turn the logging _on_, the body is contained in the response as it would be without Logbook.

## Expected Behavior
The response should contain the original body.

## Actual Behavior
The body of the response is null.

## Possible Fix
I have no idea, sadly.

## Steps to Reproduce
Reproduce erroneus behaviour :
1. Check out https://github.com/Breeki32/logbooktest113
2. Start app and send GET request to /services
or simply run the tests

Reproduce correct behaviour :
1. Check out https://github.com/Breeki32/logbooktest113
2. set logging.level.org.zalando property to TRACE
2. Start app and send GET request to /services
or simply run the tests

Reproduce erroneus behaviour with **2.0.0-RC.3**:
1. Check out https://github.com/Breeki32/logbooktest113
2. set Logbook version to 2.0.0-RC.3 in pom.xml
2. set logging.level.org.zalando property to TRACE
or simply run the tests with given version

## Context
I´ve noticed that certain things did not work in an web application when the log level was set to INFO. I tracked it down to the combination of CXF, Spring Security and Logbook (the minimal setup in the example project). The use case was logging the traffic to and from SOAP services for development purposes - but I noticed missing data in the service list servlet. 

## Your Environment

* Version used: Logbook 1.13.0 - 2.0.0-RC3
* Spring Boot 2.1.6 - 2.1.8
* CXF 3.3.2 - 3.3.3
* Link to your project: https://github.com/Breeki32/logbooktest113

Thank you for looking into this!

**Comment by Breeki32** [comment]
Thank you for taking a look & have a pleasant vacation! 

For a broader look, I´ve added another test case into the test project. This time it impacts the camunda ui, which suffers from the same behaviour (body gets 'eaten') and is therefore redered useless.

The setup is equally simple, it´s just the camunda starter and inclusion of the camunda context into the Logbook logging and Spring Security. Tests demonstrating erroneus and correct behaviour were also added.

Again, thank you for any help with getting rid of this behaviour and have a great day!

**Comment by whiskeysierra** [comment]
I did a quick lock and I don't know if it's related but when I'm debugging it I can see that the Logbook filter is registered and running twice.

**Comment by Breeki32** [comment]
I work around this by deactivating the default filter (logbook.filter.enabled=false) and by defining an own filter with Strategy.NORMAL. This works for v 1.13.0 but unfortunately not for 2.0+. I _assume_ it has to do with the unauthorized filter (since the behaviour changes with the addition of Spring Security) but I was not able to pin it down clearly in any means.

**Comment by whiskeysierra** [comment]
Took me a couple of hours but after numerous debugging sessions I finally figured it out: #617

**Comment by whiskeysierra** [comment]
The ingredients that are needed to experience this bug right now:

- usage of `ServletRequest.getWriter()` (most frameworks seem to use `getOutputStream`)
- no explicit `PrintWriter.close()` call
- no explicit `PrintWriter.flush()` call

@Breeki32 In your demo project it was cxf that was using a writer in that particular way that was revealing the issue. I do in fact have a test that was using a writer, but since it was using a try-with-resources block it was closing and therefore implicitly flushing it, hence hiding the issue.

**Comment by whiskeysierra** [comment]
I released the fix as 2.0.0-RC.5 just now. Thanks for the issue and the test case! :tada:
