### ISSUE TITLE
Response is not getting logged for Jax-RS async apis

### ISSUE THREAD

**Issue by rohanarya** [zalando/logbook#620]
I am using jax-rx async to expose rest api's. I use the @Suspended annotation to get hold of the AsyncResponse object and call AsyncResponse#resume to submit the response. Logbook is logging the request by not logging the response. On debugging I realize "isLastRequest()"  in the below code snippet from NormalStratergy.java always returns false.

I am using spring boot 2 auto-configuration to configure logback with defaults. 

NormalStrategy.java 
--------------------- 
`    private void logResponse(final Correlator correlator, final RemoteRequest request,
            final LocalResponse response) throws IOException {
        if (isLastRequest(request)) {
            response.getWriter().flush();
            correlator.write(response)
        }
 }`

**Comment by whiskeysierra** [comment]
Can you share some demo or contribute a test case that highlights and reproduces the issue?

**Comment by rohanarya** [comment]
@whiskeysierra sure, ill create a demo project, with instructions to reproduce on README and share it here

**Comment by rohanarya** [comment]
@whiskeysierra Can you look at this project and try to follow the README to see/debug the issue https://github.com/rohanarya/logbook-jersey-async/

**Comment by rohanarya** [comment]
Accidentally closed the issue. Reopening as - https://github.com/zalando/logbook/issues/621
