### ISSUE TITLE
Response is not getting logged for Jax-RS async apis

### ISSUE THREAD

**Issue by rohanarya** [zalando/logbook#621]
I am using jax-rx async to expose rest api's. I use the @Suspended annotation to get hold of the AsyncResponse object and call AsyncResponse#resume to submit the response. Logbook is logging the request by not logging the response. On debugging I realize "isLastRequest()"  in the below code snippet from NormalStratergy.java always returns false.

I am using spring boot 2 auto-configuration to configure logback with defaults. 

NormalStrategy.java 
--------------------- 
`    private void logResponse(final Correlator correlator, final RemoteRequest request,
            final LocalResponse response) throws IOException {
        if (isLastRequest(request)) {
            response.getWriter().flush();
            correlator.write(response)
        }
 }`

Demo Project : https://github.com/rohanarya/logbook-jersey-async/

Original Issue : https://github.com/zalando/logbook/issues/620

**Comment by whiskeysierra** [comment]
See #624

**Comment by rohanarya** [comment]
@whiskeysierra when can I expect the fix to be merged and released?

**Comment by whiskeysierra** [comment]
I can't properly test that right now.

**Comment by rohanarya** [comment]
I have added your fix to my demo project. I feel it looks OK, you can try it in case it helps to test.

**Comment by rohanarya** [comment]
@whiskeysierra any update on this?

**Comment by whiskeysierra** [comment]
Still struggling to write a proper test for this using Spring MVC.

**Comment by whiskeysierra** [comment]
I finally found some time digging into this and rewrote the existing test to use a real web server instead of `MockMvc`. The filter now works with tomcat and undertow. See #624

**Comment by whiskeysierra** [comment]
Fix has been released as 2.0.0-RC.7. Thanks for raising the issue! :tada:
