### ISSUE TITLE
Enable JDK9+ module-info

### ISSUE THREAD

**Issue by skjolber** [zalando/logbook#625]
Add module info OR default module name in manifest, so that it is possible to use this project as a dependency in a project using modules (JDK9+).

## Detailed Description
It should be possible to use this project as a dependency in a JDK 9+ project, in other words, at a minimum the module package name must be specified. For the module info case, creating a multi-release jar using the 'usual suspects' of maven plugins is currently quite hard / painful. So staying on JDK 8 and supporting 9+ via some plugins seems like the best use of time.

## Possible Implementation
Use moditect-maven-plugin with 

```
<plugin>
    <groupId>org.moditect</groupId>
    <artifactId>moditect-maven-plugin</artifactId>
    <version>1.0.0.Beta2</version>
    <executions>
        <execution>
            <id>add-module-infos</id>
            <phase>package</phase>
            <goals>
                <goal>add-module-info</goal>
            </goals>
            <configuration>
                <jvmVersion>${java.module.version}</jvmVersion>
                <overwriteExistingFiles>true</overwriteExistingFiles>
                <module>
                    <moduleInfoFile>src/main/moditech/module-info.java</moduleInfoFile>
                </module>
            </configuration>
        </execution>
    </executions>
</plugin>
```

or maven-jar-plugin with

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-jar-plugin</artifactId>
	<version>3.1.2</version>
	<configuration>
		<archive>
			<manifestEntries>
			    <Automatic-Module-Name>x.y.z</Automatic-Module-Name>
			</manifestEntries>
		</archive>
	</configuration>
</plugin>
```

## Your Environment
Java 8.

**Comment by whiskeysierra** [comment]
Does that approach have issues with the fact that our package names are not unique across jars?

**Comment by skjolber** [comment]
Yes, pretty sure it will. A package must be found in one and only one module ([link](https://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html)).

**Comment by whiskeysierra** [comment]
So can we deliver on this right now without re-defining package names/structures?

**Comment by skjolber** [comment]
Yes and no, most of the job is already done with defining maven artifacts (maven submodules). I only see api and core packages overlapping (?).

**Comment by whiskeysierra** [comment]
> I only see api and core packages overlapping

That fits my memory. There is no way to fix that without introducing a breaking change, is there?

**Comment by skjolber** [comment]
No, I guess the question is whether doing this later is any better? 2.0 is breaking for us anyways.

**Comment by whiskeysierra** [comment]
Right, since 2.0 is breaking anyway, it's now or never (i.e. later). I'd like to use `org.zalando.logbook` for the api. Probably would go with `org.zalando.logbook.core` then for `logbook-core`.

**Comment by whiskeysierra** [comment]
I kinda missed that for 2.0 :open_mouth:

**Comment by skjolber** [comment]
There is always a next version, glad that 2.0 is finally out! :1st_place_medal:

**Comment by damien-swarm** [comment]
Bump - I see this is added to the 3.0.0 milestone; is there a planned release date for that version?

**Comment by whiskeysierra** [comment]
No, not yet.
