### ISSUE TITLE
Request parameters not obtained in springboot2.2.0

### ISSUE THREAD

**Issue by star4j** [zalando/logbook#627]
When content-type is x-www-form-urlencoded,springboot2.2.0.RELEASE,logbook-spring-boot-starter1.13.0, request parameters could not be obtained.

**Comment by whiskeysierra** [comment]
Have you read this at https://github.com/zalando/logbook#servlet?

> The `LogbookFilter` will, by default, treat requests with a `application/x-www-form-urlencoded` body not different from
any other request, i.e you will see the request body in the logs. The downside of this approach is that you won't be
able to use any of the `HttpServletRequest.getParameter*(..)` methods. See issue [#94](../../issues/94) for some more
details.
>
> As of Logbook 1.5.0, you can now specify one of three strategies that define how Logbook deals with this situation by
using the `logbook.servlet.form-request` system property:
> 
> | Value            | Pros                                                                              | Cons                                               |
> |------------------|-----------------------------------------------------------------------------------|----------------------------------------------------|
> | `body` (default) | Body is logged                                                                    | Downstream code can **not use `getParameter*()`**  |
> | `parameter`      | Body is logged (but it's reconstructed from parameters)                           | Downstream code can **not use `getInputStream()`** |
> | `off`            | Downstream code can decide whether to use `getInputStream()` or `getParameter*()` | Body is **not logged**                             |

**Comment by star4j** [comment]
sorry,it's my problem
