### ISSUE TITLE
Micronaut configuration

### ISSUE THREAD

**Issue by marceloverdijk** [zalando/logbook#629]
Would you consider adding a `logbook-micronaut-configuration` module similar as `logbook-spring-boot-starter`? Or accepting a PR for this?

**Comment by marceloverdijk** [comment]
Probably not that easy as the http logging is tight to the servlet api, which Micronaut is not using.
It is similar as https://github.com/zalando/logbook/issues/331.

**Comment by whiskeysierra** [comment]
What is micronaut using? Netty directly?

**Comment by marceloverdijk** [comment]
@whiskeysierra Under the hood yes, but not directly. But exposed in the framework they have their own classes like Micronaut's [HttpRequest](https://docs.micronaut.io/latest/api/io/micronaut/http/HttpRequest.html) similar as Spring  WebFlux has [ServerRequest](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/function/server/ServerRequest.html) That's why I made the second comment that it might not be that easy.

**Comment by whiskeysierra** [comment]
If we could build a module for Netty than that could cover #331 as well

**Comment by whiskeysierra** [comment]
@marceloverdijk Do you happen to have experience with micronaut in terms of a customized netty setup by any chance?

**Comment by marceloverdijk** [comment]
@whiskeysierra unfortunately not, maybe good to reach out to @graemerocher or discuss it on https://gitter.im/micronautfw/questions

**Comment by graemerocher** [comment]
What is it you want to achieve?

**Comment by whiskeysierra** [comment]
I want to register a custom ChannelHandler which does http-specific traffic logging.

**Comment by graemerocher** [comment]
Seems currently we only allow injection of instances of `ChannelOutboundHandler` if your instance is a `ChannelOutboundHandler` then you can do:

```
@javax.inject.Singleton
class MyHandler implements ChannelOutboundHandler {
  // your impl
}
```

And it will be registered automatically

**Comment by whiskeysierra** [comment]
@graemerocher Can I control the position within the pipeline?

**Comment by graemerocher** [comment]
You can implemented `Ordered` but that doesn't seem to provide full control at the moment. Where does it need to go in the pipeline?

**Comment by whiskeysierra** [comment]
After the http codec. I need to observe Netty's `HttpRequest` and `HttpResponse` objects as messages in my handler.

**Comment by graemerocher** [comment]
Seems like we need a better API for that. Can you report an issue https://github.com/micronaut-projects/micronaut-core/issues

**Comment by whiskeysierra** [comment]
#708 introduces support for Netty. Now it's up to Micronaut users to lobby for the change on Micronaut side to get the ability to register those handlers into Micronaut itself: https://github.com/micronaut-projects/micronaut-core/issues/2719

**Comment by dstepanov** [comment]
@whiskeysierra Is there a way to try netty support for logbook? 'https://oss.sonatype.org/content/repositories/snapshots' and 2.1.0-SNAPSHOT doesn't work.
