### ISSUE TITLE
Can not handle multipart/form-data

### ISSUE THREAD

**Issue by radovans** [zalando/logbook#637]
Hello, I have problem with logbook. When I create endpoint where I am able to upload the file everything works correctly. After adding logbook dependency I am not able to work with the uploaded file. 

## Steps to Reproduce
For better understanding I have created minimal example with bug: https://github.com/radovans/logbook-problem

when I call the endpoint with postman:
`curl -X POST \
  http://localhost:8888/upload/file \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 15001' \
  -H 'Content-Type: multipart/form-data; boundary=--------------------------606195755734019197267982' \
  -H 'Host: localhost:8888' \
  -H 'User-Agent: PostmanRuntime/7.19.0' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F file=@resume.pdf`

![postman](https://user-images.githubusercontent.com/3687019/68772676-7c2df080-062a-11ea-9055-6a52203c4cd5.png)

I get error

`{
    "timestamp": "2019-11-13T14:23:42.887+0000",
    "status": 400,
    "error": "Bad Request",
    "message": "Required request part 'file' is not present",
    "path": "/upload/file"
}`

so I am not able to handle the file and store it for example. When i remove all logbook dependencies I have no problem with that.

**Comment by whiskeysierra** [comment]
How did you configure logbook? `multipart/*` bodies are skipped by default.

**Comment by radovans** [comment]
`@Bean
public Logbook logbook() {
	return Logbook.builder().build();
}`

You can reproduce it easily with attached project.

I can see request logged by logbook... body:<multipart> but i can not work with the uploaded file itself.

**Comment by whiskeysierra** [comment]
Found the issue. I'm working on a fix.
