### ISSUE TITLE
Can't get unauthorized requests to filter out

### ISSUE THREAD

**Issue by SledgeHammer01** [zalando/logbook#640]
POM:

		<dependency>
			<groupId>org.zalando</groupId>
			<artifactId>logbook-spring-boot-starter</artifactId>
			<version>2.0.0-RC.5</version>
		</dependency>

Application class:

	@Autowired
	private ServletContext context;

	@Bean
	public Logbook logbook() {
		Logbook logbook = Logbook.builder().condition(exclude(requestTo("/"),
												   			  requestTo("/csrf"),
												   			  requestTo("/oauth/**"),
												   			  requestTo("/swagger-resources/**"),
												   			  requestTo("/swagger-ui.html"),
												   			  requestTo("/v2/**"),
												   			  requestTo("/v3/**"),
												   			  requestTo("/webjars/**")))
								.build();

		context.addFilter("SecureLogbookFilter", new SecureLogbookFilter(logbook))
	    .addMappingForUrlPatterns(EnumSet.of(REQUEST, ASYNC), true, "/*");
	
		return logbook;
	}

Am I missing something else? Unauthorized requests are still logged.

**Comment by whiskeysierra** [comment]
The starter is already registering two logbook filters. Are you sure yours is actually used?

**Comment by SledgeHammer01** [comment]
Hi,
I am sure this instance is being used. When I comment out the requestTo filters, it shows all the various requests & responses from Swagger and web jars, etc. I removed any filter registration, as yes, I read it is supposed to filter out unauthorized requests out of the box?

	@Bean
	public Logbook logbook() {
		return Logbook.builder().condition(exclude(requestTo("/"),
									   			   requestTo("/csrf"),
												   requestTo("/oauth/**"),
												   requestTo("/swagger-resources/**"),
												   requestTo("/swagger-ui.html"),
												   requestTo("/v2/**"),
												   requestTo("/v3/**"),
												   requestTo("/webjars/**")))
								.build();
	}

**Comment by whiskeysierra** [comment]
So the logbook starter registers two filters: 1) secure logbook filter (running very early, before spring security) and 2) *normal* logbook filter (running after spring security).

Normal requests (authorized/authenticated) will be logged exclusively by the second one. The secure logbook filter is there to log a minimal version (without body) of unauthorized requests so that one can see them.

If you don't need that feature at all and you don't want to see those requests at all, then disabling the secure logbook filter is the easiest way to get there:

```yaml
logbook.secure-filter.enabled: false
```

**Comment by SledgeHammer01** [comment]
Right now I get Incoming Request and Outgoing Response. When I add logbook.secure-filter.enabled=false, I get still get Incoming Request, but Outgoing Response goes away. From your response, I assume its supposed to remove the requests too?

I'm using Spring 2.2.1 and OAuth / JWT in a rest api with spring-boot-starter-security, spring-security-oauth2-autoconfigure, spring-security-jwt.

**Comment by SledgeHammer01** [comment]
Hmm... I'm going to be using a Sink to log to a DB... seems write(Precorrelation precorrelation, HttpRequest request) gets called for both authorized & unauthorized and write(Correlation correlation, HttpRequest request, HttpResponse response) gets called only for authorized. So I guess that'll work... that was the end goal anyways :). To only log authorized request/responses to the DB.

**Comment by whiskeysierra** [comment]
> seems write(Precorrelation precorrelation, HttpRequest request) gets called for both authorized & unauthorized

So far so good.

> and write(Correlation correlation, HttpRequest request, HttpResponse response) gets called only for authorized

That's weird. The `SecureLogbookFilter` uses a `SecurityStrategy`:

https://github.com/zalando/logbook/blob/668344ee75937820f1f33640fd3df3d66d57065a/logbook-core/src/main/java/org/zalando/logbook/SecurityStrategy.java#L23-L35

The `Sink` should then call `write(Correlation, HttpRequest, HttpResponse)` also for unauthorized:

https://github.com/zalando/logbook/blob/79cd28a2af44ceca7199bc405c68ee4347e30cc2/logbook-api/src/main/java/org/zalando/logbook/Sink.java#L14-L18

**Comment by SledgeHammer01** [comment]
My sink just looks like this:

	@Override
	public void write(Precorrelation precorrelation, HttpRequest request) throws IOException {
		System.out.println("HERE1");
	}

	@Override
	public void write(Correlation correlation, HttpRequest request, HttpResponse response) throws IOException {
		System.out.println("HERE2");
	}

WithOUT the flag:

unauthorized:

HERE1
HERE1
HERE2

authorized:

HERE1
HERE2

WITH the flag:

unauth:

HERE1

auth:

HERE1
HERE2

**Comment by whiskeysierra** [comment]
> WITH the flag:
> 
> unauth:
> 
> HERE1
> 
> auth:
> 
> HERE1
> HERE2

That is fishy. With the secure logbook filter disabled you shouldn't be able to see any unauthorized reuqests at all, because the spring security filter is running before the logbook filter and unauthorized requests never reach the logbook filter.

> WithOUT the flag:
> 
> unauthorized:
> 
> HERE1
> HERE1
> HERE2
> 
> authorized:
> 
> HERE1
> HERE2

That's also incorrect behavior, because each request/response pair should be logged exactly once, so there should be HERE1 and HERE2 once each, never anything twice.

I'd suggest you put some breakpoints into the (secure) logbook filter and spring security filter and see how they are running.

**Comment by whiskeysierra** [comment]
Do you still have the setup running that you have outlined in the original comment?

**Comment by SledgeHammer01** [comment]
This behavior occurs with this setup:

	@Bean
	public Logbook logbook() {
		return Logbook.builder().condition(exclude(requestTo("/"),
												   requestTo("/csrf"),
												   requestTo("/oauth/**"),
												   requestTo("/swagger-resources/**"),
												   requestTo("/swagger-ui.html"),
												   requestTo("/v2/**"),
												   requestTo("/v3/**"),
												   requestTo("/webjars/**")))
								.sink(new TransactionLogSink())
								.build();
	}

By "WITH the flag", I mean WITH logbook.secure-filter.enabled=false, by "withOUT the flag", I mean that whole flag is removed and whatever default behavior is, use that.

With this in my properties:

logbook.secure-filter.enabled=false

I put a breakpoint on HERE1 which you are saying should never be called for unauthorized requests. Seems like there is an extra filter in there somewhere. I have removed the code that manually added a filter manually after you said the out of box should work.

Here is the top of the stack (I renamed MySink to TransactionLogSink):

TransactionLogSink.write(Precorrelation, HttpRequest) line: 16	
DefaultStrategy(Strategy).write(Precorrelation, HttpRequest, Sink) line: 69	
DefaultLogbook.lambda$process$2(HttpRequest, Strategy, Precorrelation, HttpRequest) line: 40	
2084714927.write() line: not available	
LogbookFilter.logRequest(RemoteRequest) line: 65	
LogbookFilter.doFilter(HttpServletRequest, HttpServletResponse, FilterChain) line: 49	
LogbookFilter(HttpFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 31	
ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 193	
ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 166	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 320	
FilterSecurityInterceptor.invoke(FilterInvocation) line: 126	
FilterSecurityInterceptor.doFilter(ServletRequest, ServletResponse, FilterChain) line: 90	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
ExceptionTranslationFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 118	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
SessionManagementFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 137	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
AnonymousAuthenticationFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 111	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
SecurityContextHolderAwareRequestFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 158	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
RequestCacheAwareFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 63	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
OAuth2AuthenticationProcessingFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 176	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
LogoutFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 116	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334	
HeaderWriterFilter.doHeadersAfter(HttpServletRequest, HttpServletResponse, FilterChain) line: 92	
HeaderWriterFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 77	
HeaderWriterFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 119	
FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 334

**Comment by SledgeHammer01** [comment]
Hmm... I commented out my bean and its still getting logged... so maybe the issue is really that the default instance of Logbook is running and my instance is really a second instance?

**Comment by whiskeysierra** [comment]
> so maybe the issue is really that the default instance of Logbook is running and my instance is really a second instance?

Your logbook bean should take over and the one provided by the auto configuration should step down. Looking at your setup, you don't actually need to configure it like that. You can specify exclude patterns in the application.yml and just register your custom sink as a bean. That should give you the same setup with less code.

The Logbook instance itself is not really doing anyting, so even if there were two, only the filter actually makes use of it. The issue is somehow related to a filter going rogue, so either a second filter still running somewhere or filters running out of order (logbook before security).

**Comment by whiskeysierra** [comment]
I'm closing this for now. Feel free to re-open with new information.
