### ISSUE TITLE
Make replaceJsonStringProperty regexp more general

### ISSUE THREAD

**Issue by Sam-Kruglov** [zalando/logbook#652]
Basically, what I want is here:
```
public static void main(String[] args) {
    val result = JsonBodyFilters.replaceJsonStringProperty(Set.of("url", "token"), "***").filter(MediaType.APPLICATION_JSON_UTF8_VALUE, "{\n" +
            "  \"blaUrl\": \"http:////\",\n" +
            "  \"url\": \"http:sasd\",\n" +
            "  \"myToken\": \"asdkjhadu89\",\n" +
            "  \"token\": \"q3adsd\",\n" +
            "  \"Token\": \"q3adsd\"\n" +
            "}");
    System.out.println(result);
}
```

This prints the following:
```
{
  "blaUrl": "http:////",
  "url": "***",
  "myToken": "asdkjhadu89",
  "token": "***",
  "Token": "q3adsd"
}
```

But I would like every field to have "***" value without me having to specify each field key explicitly

**Comment by whiskeysierra** [comment]
What kind of semantics would you expect? Case-insensitive, matching anywhere in the property name, i.e. something like `ILIKE` in SQL?

**Comment by whiskeysierra** [comment]
I'm not keen on changing the semantic of the existing functions, but I could imagine some alternatives:

1. `replaceJsonStringProperty(Predicate<String>, String)`
   - If predicate matches key, replace value
2. `replaceJsonStringProperty(BiPredicate<String, String>, String)`
  - if predicate matches key and current value, replace value
3. `replaceJsonStringProperty(BinaryOperator<String>)`
  - pass key and current value, use return value as replacement
4. `replaceJsonStringProperty(Pattern, String)`
  - if pattern matches key, replace value
5. `replaceJsonStringProperty(Collection<Pattern>, String)`
  - if any pattern matches key, replace value

Each of those would give you the ability to write something that fits the requirements. They differ in style and effort needed to get the work done. Any :+1::-1: ?

**Comment by whiskeysierra** [comment]
#655 implements option 1 from above. If needed it can be evolved into option 2 or 3. Option 4 and 5 can be implemented on top of the proposed solution now.

**Comment by Sam-Kruglov** [comment]
Thanks! Predicate should be enough 🙂
