### ISSUE TITLE
Unable to log HTTP Response for Multipart Requests

### ISSUE THREAD

**Issue by srknkbs** [zalando/logbook#657]
## Description
We have a REST API which requires a `MultipartFile` as a request parameter. When we are calling that API w/o providing a multipart file (negative scenario), we got the following exception:

`ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [{api-path}] threw exception [Request processing failed; nested exception is org.springframework.web.multipart.MultipartException: Current request is not a multipart request] with root cause`

The issue is after getting this error, we are not able to write logs for HTTP response.

The following scenarios we can log HTTP response:
* When we are calling API with bad request (except multipartfile)
* When we are calling API with incorrect path

## Expected Behavior
Able to log HTTP response

## Actual Behavior
No log for HTTP Response

## Possible Fix
N/A

## Steps to Reproduce
1. Create a REST API which requires multipart file as a request parameter.
2. Call that API w/o any multipart file.
3. Observe that there is a log for HTTP Request but not for HTTP Response.

## Context
We can not log HTTP response for Multipart requests.

**Comment by whiskeysierra** [comment]
Can you contribute a test case that reproduces this?

**Comment by whiskeysierra** [comment]
> ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [{api-path}] threw exception [Request processing failed; nested exception is org.springframework.web.multipart.MultipartException: Current request is not a multipart request] with root cause

Is this the default error handling of Tomcat? If it is that means it uses the `ERROR` dispatch which Logbook doesn't support. See https://github.com/zalando/logbook#servlet

**Comment by srknkbs** [comment]
Yes, you are right.
 
I checked the handling of multipartfile parameters in our APIs. 
Actually when I update the spring annotation from `@RequestParam` to `@RequestPart` for multipartfile type parameter, i can log the HTTP response properly.

I am closing this issue. 

Thanks for the quick response and explanation.

**Comment by Estefanos8080** [comment]
That was helpful. I was facing the same issue while. I changed the annotation and i was able to upload post in swagger and postman.
