### ISSUE TITLE
JsonBodyFilters doesn't read arrays

### ISSUE THREAD

**Issue by Sam-Kruglov** [zalando/logbook#659]
if I want to obfuscate "tokens" field, it will be ignored because it is an array
```
{
  "tokens": [
    {
       "payload": "bhaisdh8"
    }
  ],
}
```
should turn into something like this
```
{
  "tokens": "XXX",
}
```

**Comment by whiskeysierra** [comment]
That is correct and highlighted by the names of the factory methods:
- <code>replaceJson<strong>Number</strong>Property</code>
- <code>replaceJson<strong>String</strong>Property</code>
- <code>replace<strong>Primitive</strong>JsonProperty</code>

For some explanation see https://github.com/zalando/logbook/issues/493#issuecomment-496093593

**Comment by whiskeysierra** [comment]
In your example, why not just obfuscate `payload` directly. That would leave the structural information in place (array with object), but would remove the actual payload value.

**Comment by Sam-Kruglov** [comment]
Okay, fair enough! :)
