### ISSUE TITLE
Incorrect configuration for default Request and Response filters

### ISSUE THREAD

**Issue by srknkbs** [zalando/logbook#669]
When we look at the [spring boot starter](https://github.com/zalando/logbook#spring-boot-starter) section in logbook documentation it states that the default configuration for request and response filters are `none()`:

RequestFilter |   | RequestFilter.none()
-- | -- | --
ResponseFilter |   | ResponseFilter.none()

However, when i look at the [Logbook Auto Configuration](https://github.com/zalando/logbook/blob/master/logbook-spring-boot-autoconfigure/src/main/java/org/zalando/logbook/autoconfigure/LogbookAutoConfiguration.java) class , they are configured differently. 

    @API(status = INTERNAL)
    @Bean
    @ConditionalOnMissingBean(RequestFilter.class)
    public RequestFilter requestFilter() {
        return RequestFilters.defaultValue();
    }

    @API(status = INTERNAL)
    @Bean
    @ConditionalOnMissingBean(ResponseFilter.class)
    public ResponseFilter responseFilter() {
        return ResponseFilters.defaultValue();
    }

As a library user, i do not expect any filterfor the response and request object by default.

**Comment by whiskeysierra** [comment]
The code is actually correct. I opened #670 to fix it.

The default values make sense because they will either provide now additional benefit (logging binaries, multipart) or break applications (trying to log endless streams).

**Comment by srknkbs** [comment]
Logbook logs request/response to the log console by default. So it make sense to replace binaries or multipart files with static string valus (such as <multipart>, <binary>). But if i persist logs to the database i need to persist original binaries and multipart files. So i can write my own filters to eliminate those filters. 

Is my assumption correct?

**Comment by srknkbs** [comment]
I have another question. When i override RequestFilter with RequestFilter.none(), my requst body is null for multipart files. Before I had "multipart" string in the request body.

When i remove the default requestfilter, i expect original value in the request value.

How can i handle this situation?

**Comment by whiskeysierra** [comment]
> But if i persist logs to the database i need to persist original binaries and multipart files. So i can write my own filters to eliminate those filters.
> 
> Is my assumption correct?

That is correct. Configure/Register `RequestFilter.none()` and `ResponseFilter.none()` respectively instead of the default.

> When i remove the default requestfilter, i expect original value in the request value.

That's a reasonable expectation to have. Can you paste your request here or a minimal version of it? Maybe even produce a test case or demo project?

**Comment by srknkbs** [comment]
I am using postman form-data/file option to pass multipart bodies.

I debug the code and i found out that the issue is in [RemoteRequest](https://github.com/zalando/logbook/blob/eecb6d18e9dd75de5ba0b625b818e8900c3c1b0e/logbook-servlet/src/main/java/org/zalando/logbook/servlet/RemoteRequest.java) class.

The following line (line number 108) return empty byte array for multipart bodies.
new Buffering(toByteArray(request.getInputStream()));

When i use binary option (in postman) to pass one file (just to check the behaviour), i have proper byte array object.

**Comment by whiskeysierra** [comment]
The handling of multipart is always somewhat special. Is there any filter running before Logbook? Which component is actually parsing the multipart request body? The servlet container? Application framework?

**Comment by srknkbs** [comment]
>  Is there any filter running before Logbook? 
Yes, secure logbook filter. But in my opinion it is not a problem,since secure logbook filter delays handling the request log.

> Which component is actually parsing the multipart request body? The servlet container? Application framework?

It is application context.

When i call the request.getBody() in my Sink implementation, here is the stackstrace:

![image](https://user-images.githubusercontent.com/25503249/70990589-28e60c80-20c6-11ea-996c-db1c0355c53c.png)
