### ISSUE TITLE
"Required request body is missing" when POSTing form

### ISSUE THREAD

**Issue by jbonzowh** [zalando/logbook#701]
When POSTing to an endpoint with form content, "Required request body is missing" exception is thrown and a 400 error is returned.

## Expected Behavior
The request should be logged and a 200 returned

## Actual Behavior
An exception is thrown and a 400 is returned

## Possible Fix
It seems that setting the system property `logbook.servlet.form-request` to "PARAMETER" works around this issue, but an exception shouldn't be thrown with the default setup. Maybe calling getParameterMap before getInputStream in RemoteRequest would solve this.

It may also be better to read the `logbook.servlet.form-request` from application properties, similar to how `logbook.filter.enabled` is set.

## Steps to Reproduce
I've provided a minimal example to reproduce this issue at https://github.com/jbonzowh/logbook_bug

Run the project then run this curl command `curl http://localhost:8080/message -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' --data 'accountId=90240'`

## Your Environment
* Version used: logbook-spring-boot-starter 1.13.0, spring-boot 2.2.4.RELEASE, Java 8
* Link to your project: https://github.com/jbonzowh/logbook_bug

**Comment by whiskeysierra** [comment]
>  but an exception shouldn't be thrown with the default setup

The table at https://github.com/zalando/logbook#servlet shows the pros and cons of each option. There is no clear winner. I picked an option that prints the body by default but will fail with an obvious reason if someone tries to use getParameter.

> Maybe calling getParameterMap before getInputStream in RemoteRequest would solve this.

No, those two methods are mutually exclusive. The Servlet API only supports one or the other, effectlvely.

**Comment by whiskeysierra** [comment]
> It may also be better to read the `logbook.servlet.form-request` from application properties, similar to how `logbook.filter.enabled` is set.

That's a valid concern.
