### ISSUE TITLE
Obfuscating cookies?

### ISSUE THREAD

**Issue by benlei-gfm** [zalando/logbook#705]
Would be nice if individual request cookies and response set-cookies can be obfuscated

**Comment by whiskeysierra** [comment]
Makes total sense. Obvious workaround right now would be to obfuscate the whole header.

From a quick look I found [`java.net.HttpCookie`](https://docs.oracle.com/javase/8/docs/api/java/net/HttpCookie.html) but that only provides support for parsing `Set-Cookie` headers. Any clue how to parse `Cookie`?

**Comment by whiskeysierra** [comment]
The next issue is that `java.net.HttpCookie` can parse a `Set-Cookie` header but can only produce values for `Cookie`. I guess we would need to parse it by hand using regular expressions.

**Comment by benlei-gfm** [comment]
According to https://stackoverflow.com/a/15747956/12075726 it looks like that doesn't work for all `Set-Cookie` cases. Maybe it's sufficient, though?

As for plain old `Cookie`s, maybe it would be helpful to start reading:
`org.apache.tomcat.util.http.parser.Cookie`

from Apache Tomcat.
