### ISSUE TITLE
Spring boot starter for reactive web environments

### ISSUE THREAD

**Issue by jbellmann** [zalando/logbook#740]
The current [logbook-spring-boot-starter](https://github.com/zalando/logbook/tree/master/logbook-spring-boot-starter) / [logbook-spring-boot-autoconfigure](https://github.com/zalando/logbook/blob/master/logbook-spring-boot-autoconfigure) do not yet support reactive environments using Netty (eg. spring-cloud-gateway).

## Detailed Description
It would be nice if the same developer experience would be supported like currently available for servlet based web environments.

## Possible Implementation
Extend current autoconfigure module for configuration depending on [type of webapplication condition](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/condition/ConditionalOnWebApplication.Type.html).

Create two separate starter (eg. logbook-web-spring-boot-starter, logbook-netty-spring-boot-starter) to manage dependencies.

## Your Environment
* Version used: 2.1.0-SNAPSHOT

I could try to provide a PR, but I would like to disucuss it first (same starter to be used, different starters for clear dependency separation, ...).

**Comment by jbellmann** [comment]
I just realized there was a release 2 days ago. But version in pom.xml in master still shows 2.1.0-SNAPSHOT. I will try to validate this request against latest released version.

**Comment by whiskeysierra** [comment]
> I just realized there was a release 2 days ago. But version in pom.xml in master still shows 2.1.0-SNAPSHOT

#739 is not merged yet. I believe 2.1.0 only includes the netty module, but no specific Spring Boot Webflux support.

**Comment by whiskeysierra** [comment]
@jbellmann Have you solved this internally and could contribute back a webflux auto configuration?
