### ISSUE TITLE
What is ExcludeTest for?

### ISSUE THREAD

**Issue by Sam-Kruglov** [zalando/logbook#754]
Hi, was browsing the repository and found this test which doesn't seem to do anything.
https://github.com/zalando/logbook/blob/master/logbook-spring-boot-autoconfigure/src/test/java/org/zalando/logbook/autoconfigure/ExcludeTest.java

I couldn't find any place which would want `org.slf4j.Logger` as a Spring Bean, specifically, couldn't find the usages of `httpLogger` bean. This test only asserts that nobody is calling the bean, so, I think you can remove this file.

**Comment by whiskeysierra** [comment]
The test verifies that the exclude feature (setting a condition to prevent logging for certain requests) actually won't produce log entries.

**Comment by Sam-Kruglov** [comment]
I wanted to use the same in my custom tests but couldn't find where is this `httpLogger` bean goes. Was that removed? 
I also think there probably should be a test here to check is this logger IS called when it should be called, otherwise, this test suit may be broken and we won't notice

**Comment by whiskeysierra** [comment]
I just released 2.1.2 with a fix.
