### ISSUE TITLE
Partial masking

### ISSUE THREAD

**Issue by Sam-Kruglov** [zalando/logbook#755]
Given I have this body
```json
{
  "cardNumber": "1111-2222-3333-4444"
}
```

I want to turn it into this
```json
{
  "cardNumber": "****-****-****-4444"
}
```

I.e. I don't want to mask it completely, but I do want to mask it somehow to hide the sensitive data.

I suggest that `BodyFilters` and `QueryFilters` have this method:
```java

 public static *Filter replaceStringProperty(
    final BiFunction<String, String, String> replacement
) {
    return ...;
}
```

So that I can do this:
```java
*Filters.replaceStringProperty(
    (name, value) -> {
        if (shouldMaskPartiallyPredicate.test(name)){
            return maskPartially(value);
        }
        if (shouldMaskFullyPredicate.test(name)){
            return "***";
        }
        return value;
    };
);
```

**Comment by whiskeysierra** [comment]
Sounds like a useful extension. We have something like that for headers already, if I remember correctly. API looks also good. Do you care to implement it?

**Comment by Sam-Kruglov** [comment]
I probably will but not sure when

**Comment by Sam-Kruglov** [comment]
Switched jobs, now I most likely won't do this one

**Comment by dnandola-wyze** [comment]
Hey @whiskeysierra , this is something I can work on. I need this function especially in Json Body filter to replace body value to hash of that value rather than a generic replacement parameter. Adding a function here to do the replacement would be a helpful extension IMO. Will send out a pull request soon.

**Comment by whiskeysierra** [comment]
Follow up issue is #851
