### ISSUE TITLE
I can not find logs in console using spring boot app, I have just installed `logbook-spring-boot-starter` and add `logging.level.org.zalando.logbook.Logbook=TRACE` to my common.properties file

### ISSUE THREAD

**Issue by Doaa82** [zalando/logbook#768]
## Description

When I Installed the maven dependency and the logbook level tp TRACE, When I hit any endpoint in the application
## Expected Behavior

I am expecting the request and the response to be logged in the console 
## Actual Behavior

I got nothing log in the console
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Link to your project:

**Comment by whiskeysierra** [comment]
Can you prepare a sample project on GitHub to showcase this?

**Comment by Doaa82** [comment]
@whiskeysierra yes I will prepare a sample application and share it, but as a clarification could you please confirm the following:

1. in order to enable logging with logbook and spring boot, I need **only** to install `logbook-spring-boot-starter` dependency and set this configuration `logging.level.org.zalando.logbook.Logbook=TRACE`. [Please confirm]
2. if we do not need any extra customization, then the above two configurations in step #1 are enough to see logs in the console. [Please confirm]
3. Any endpoint defined in a class annotated with `@Controller` should be automatically logged in the console when executing the endpoint through postman. [Please confirm]
4. Please advise if the logs will be in a different place than console, so I can check.
5. Could you please advise and guide me to a real working example since I followed the steps in RAEDME but I still do not know what is missing so that log is not displayed in the console, is there any specific instructions or setup that I should apply? [Please advise]

**Comment by whiskeysierra** [comment]
> 1. in order to enable logging with logbook and spring boot, I need **only** to install `logbook-spring-boot-starter` dependency

Correct.

> and set this configuration `logging.level.org.zalando.logbook.Logbook=TRACE`

Logbook makes no hard requirement about the logging framework or how you configure it. I haven't used Spring's logging configuration personally yet, but that looks good to me.

> 2. if we do not need any extra customization, then the above two configurations in step #1 are enough to see logs in the console.

Whether something is logged to the console or a file depends on your logging framework and your configuration. I can't tell, really. Logbook's responsibility ends at the SLF4J level. Logbook's contract is as follows: It uses the `org.logbook.Logbook` logger with the level `TRACE` by default. It's up to the user to make sure the logging framework is setup correctly and that the particular logger is in fact active and connected to an appender.

>     3\. Any endpoint defined in a class annotated with `@Controller` should be automatically logged in the console when executing the endpoint through postman.

Confirmed.

>     4\. Please advise if the logs will be in a different place than console, so I can check.

See points above. The configuration of your logging framework is out of scope for Logbook.

>     5\. Could you please advise and guide me to a real working example since I followed the steps in RAEDME but I still do not know what is missing so that log is not displayed in the console, is there any specific instructions or setup that I should apply?

Your setup sounds good to me. It should work. The only thing I can offer is to take a look at an example. Once we get your example working, I'd be more than happy to incorporate it into logbook for future users.

**Comment by whiskeysierra** [comment]
@Doaa82 Feel free to create a sample project or a test to verify the behavior that you see. I'm more than happy to reopen this, if needed, but for the time being I don't think there is anything to do here.

**Comment by zhahaoyu** [comment]
I can confirm the issue still exists
