### ISSUE TITLE
Support for JDK 11

### ISSUE THREAD

**Issue by jeanabraham** [zalando/logbook#776]
I noticed that one of the dependencies for using this library is JDK 8. Is there a plan to have support for JDK 11+? Thanks!

**Comment by whiskeysierra** [comment]
That should be a minimum requirement, not a maximum. Have you tried running it with JDK 11 or higher? I'd expect it to work.

**Comment by whiskeysierra** [comment]
I successfully ran the build including tests locally using Java 11 and everything worked. I haven't tried to use the Java 8 binaries in a Java 11 application though. But my understanding is that it should just work.

Please let me know if I'm wrong.
