### ISSUE TITLE
PrimitiveJsonPropertyBodyFilter regexp is incorrect

### ISSUE THREAD

**Issue by EugenShablovsky** [zalando/logbook#780]
The pattern for [json parsing](https://github.com/zalando/logbook/blob/1f982887d7a975150eef8262b71af74da391bd56/logbook-json/src/main/java/org/zalando/logbook/json/PrimitiveJsonPropertyBodyFilter.java) doesn't capture the first property of a nested object. 

Pattern (PrimitiveJsonPropertyBodyFilter.STRING ) - **(?\<key\>"(?\<property\>.\*?)"\s\*:\s\*)((?:"(.*?[^\\\\])??((\\\\\\\\)+)?+")|null)** 
JSON - {"property1":"value2","property2":"value2","nestedObject":{"property3":"value3","property4":"value4"}}

So, when i use  JsonBodyFilters.replaceJsonStringProperty(Sets.newHashSet("property1", "property2", "property3", "property4"), "XXX"), property3 won't be replaced with XXX.

![изображение](https://user-images.githubusercontent.com/57913119/87584366-0cef2b80-c6e6-11ea-88df-539eb5b739c2.png)

Thanks,
Eugene

**Comment by whiskeysierra** [comment]
https://stackoverflow.com/a/32155765

Seems like a better set of regular expressions than what we have been using so far. I haven't tested against our existing test cases though.

**Comment by whiskeysierra** [comment]
Released the fix as 2.1.1
