### ISSUE TITLE
打印日志中文乱码 (Print log Chinese garbled)

### ISSUE THREAD

**Issue by wpt191** [zalando/logbook#800]
"name":"é¦æ¸¯ä¸å¡æµç¨"

**Comment by whiskeysierra** [comment]
Logbook falls back to UTF-8, unless the content type of the message specifies something different. Which charset are you using?

**Comment by wpt191** [comment]
my default charset  is utf-8
`<logger name="org.zalando.logbook" level="TRACE"/>我就配置了这一块，在logback-spring.xml`

**Comment by whiskeysierra** [comment]
And the request that you're sending? How does that look like? (Maybe you can copy&paste curl output?)

**Comment by wpt191** [comment]
**我的配置**
`logbook:
  format:
    style: json #这个值还可以是 http、json等`

**返回数据**
`2020-08-04 14:42:41.662|site|8081|TRACE|http-nio-8081-exec-1|org.zalando.logbook.Logbook|DefaultHttpLogWriter.java|write:26|{"origin":"local","type":"response","correlation":"af2e43f663f94507","duration":395,"protocol":"HTTP/1.1","status":200,"headers":{"Connection":["keep-alive"],"Content-Type":["application/json"],"Date":["Tue, 04 Aug 2020 06:42:41 GMT"],"Keep-Alive":["timeout=60"],"Transfer-Encoding":["chunked"]},"body":{"header":{"retCode":"1","retMessage":"æä½æå"},"body":[{"id":70,"seqId":"6689551097411014656","name":"123","type":"1233","source":"process_hk","property":"1","enabled":"1","deleteFlag":0,"createBy":null,"createTime":"2020-08-04T02:56:16.000+0000","updateBy":null,"updateTime":"2020-08-04T05:41:38.000+0000"},{"id":66,"seqId":"6689543600302329856","name":"111","type":"345","source":"process_hk","property":"0","enabled":"1","deleteFlag":0,"createBy":null,"createTime":"2020-08-04T02:26:26.000+0000","updateBy":null,"updateTime":"2020-08-04T02:26:26.000+0000"},{"id":65,"seqId":"6689543406173163520","name":"123","type":"456","source":"process_hk","property":"1","enabled":"1","deleteFlag":0,"createBy":null,"createTime":"2020-08-04T02:25:40.000+0000","updateBy":null,"updateTime":"2020-08-04T02:25:40.000+0000"},{"id":67,"seqId":"6689544221482946560","name":"345","type":"6567","source":"process_hk","property":"1","enabled":"1","deleteFlag":0,"createBy":null,"createTime":"2020-08-04T02:28:54.000+0000","updateBy":null,"updateTime":"2020-08-04T02:28:54.000+0000"},{"id":58,"seqId":"1285814170880708609","name":"é®å·è°æ¥","type":"äºå¡å±","source":"process_nd","property":"1","enabled":"1","deleteFlag":0,"createBy":null,"createTime":"2020-07-14T08:54:51.000+0000","updateBy":null,"updateTime":"2020-08-03T03:23:01.000+0000"},{"id":62,"seqId":"1285814170880708613","name":"æµè¯2","type":"ä¿å®å±","source":"process_hk","property":"1","enabled":"1","deleteFlag":0,"createBy":null,"createTime":"2020-08-03T05:49:11.000+0000","updateBy":null,"updateTime":"2020-08-03T05:49:17.000+0000"},{"id":59,"seqId":"1285814170880708610","name":"é®å·è°æ¥","type":"å¬å®å±","source":"process_hk","property":"1","enabled":"1","deleteFlag":0,"createBy":null,"createTime":"2020-07-14T08:55:00.000+0000","updateBy":null,"updateTime":"2020-08-03T03:22:49.000+0000"},{"id":68,"seqId":"6689545278267199488","name":"æ¢µèåçµé¥­é","type":"æ¯æåæ¯èè¬","source":"process_hk","property":"1","enabled":"1","deleteFlag":0,"createBy":null,"createTime":"2020-08-04T02:33:06.000+0000","updateBy":null,"updateTime":"2020-08-04T02:33:06.000+0000"},{"id":63,"seqId":"123","name":"æµè¯2","type":"æé«æ£","source":"process_hk","property":"1","enabled":"1","deleteFlag":0,"createBy":null,"createTime":"2020-08-03T05:56:24.000+0000","updateBy":null,"updateTime":"2020-08-03T07:27:46.000+0000"},{"id":57,"seqId":"1285814170880708608","name":"é®å·è°æ¥","type":"æä¸å±","source":"process_nd","property":"1","enabled":"1","deleteFlag":0,"createBy":null,"createTime":"2020-07-14T08:54:42.000+0000","updateBy":null,"updateTime":"2020-08-03T03:22:57.000+0000"},{"id":64,"seqId":"6689541664240963584","name":"111","type":"è°æ¥å±","source":"process_hk","property":"1","enabled":"1","deleteFlag":0,"createBy":null,"createTime":"2020-08-04T02:18:44.000+0000","updateBy":null,"updateTime":"2020-01-01T04:00:11.000+0000"}]}}
`

**Comment by whiskeysierra** [comment]
How do you produce that JSON? Spring application with Jackson? Standard settings? Where do those `name` and `type` properties come from? Feels like those strings are encoded in a different charset.

**Comment by whiskeysierra** [comment]
Can you post one of the garbled "name" or "type" values here in the original chinese, text? Maybe we can reverse-engineer which charset was used to encode that JSON.

**Comment by wpt191** [comment]
My setting is ok，i have checked.now i use aop to print request param




|
|
|
|
|
魏平涛 18391859179
神州数码融信软件有限公司
智能银行解决方案部




|
|
 联系我
|
|
|
|
|



在2020年08月07日 15:11，Willi Schönborn 写道：

Can you post one of the garbled "name" or "type" values here in the original chinese, text? Maybe we can reverse-engineer which charset was used to encode that JSON.

**Comment by whiskeysierra** [comment]
> now i use aop to print request param

AOP as in "aspect-oriented programming"? I don't get it.

**Comment by bro0k** [comment]
> "name":"é¦�æ¸¯ä¸�å�¡æµ�ç¨�"

JVM默认字符集不一定是UTF-8
Setting the default Java character encoding
```
-Dfile.encoding=UTF-8
//example    
java -Dfile.encoding=UTF-8 -jar example.jar
```

**Comment by whiskeysierra** [comment]
Can you paste the source code how you send that request? Spring RestTemplate?

**Comment by shangkuku** [comment]
I also encontered the problem with Apache HttpClient, and i have solved the problem by using addInterceptorLast rather than addInterceptorFirst.

**Comment by xudamiao-hub** [comment]
the same issue happend , my message is “messages":["执行成功"]”，but the log in console print "messages":["æ§è¡æå"]"

**Comment by whiskeysierra** [comment]
@xudamiao-hub Can you paste the source code how you send that request? Spring RestTemplate?

**Comment by whiskeysierra** [comment]
See #870
