### ISSUE TITLE
LogstashLogbackSink: Replace log.trace with call to HttpLogWriter.write()

### ISSUE THREAD

**Issue by wulfcolin** [zalando/logbook#838]
Being able to provide a custom `HttpLogWriter` for the `LogstashLogbackSink` and calling the respective write methods instead of `log.trace` would increase the configurability.

## Detailed Description
Replace `log.trace` in `LogstashLogbackSink` with calls to a provided `HttpLogWriter` or the default one

## Context
This change enables logging of requests on other levels, such as DEBUG, INFO, etc.

## Your Environment
* Version used: 2.2.0

**Comment by whiskeysierra** [comment]
My knowledge of logstash-logback is pretty limited, tbh. I had the impression that it's pretty much bound to Logback, hence the direct dependency to a logger. Technically we can introduce a writer there, similar to the DefaultSink implementation.

@skjolber What's your take on this?

**Comment by skjolber** [comment]
I guess he wants to control the log level - was not that possible before? I would prefer to do the same, so we can continue to use the same log level as in v1. 

But passing in `HttpLogWriter` is probably not the best approach (?), as it supports just a single argumet, and we're adding two sibling fields to the log statement (the String `message` and the Marker `http`).

**Comment by whiskeysierra** [comment]
> I guess he wants to control the log level - was not that possible before (at least some other place in the lib)?

Actually, I removed that ability and now it's always TRACE. One can control whether TRACE is enabled or not using their logging framework of choice, but it's always TRACE. (Unless some frameworks allow to rewrite levels using configurations, but I'm not aware of that.)

**Comment by wulfcolin** [comment]
I do not understand why it should always be logged to trace? Doesn't it make sense to have it configurable?

**Comment by skjolber** [comment]
Would you consider making it configurable again? If someone already is doing a lot of logging and want to add request-/response logging, they might want another level than trace (i.e. info is fair) so it fits in with their current global log level (which is usually debug or info).

**Comment by whiskeysierra** [comment]
> If someone already is doing a lot of logging and want to add request-/response logging, they might want another level than trace (i.e. info is fair) so it fits in with their current global log level (which is usually debug or info).

One can configure different levels for different loggers. No need to change the level in the code or configure it there.

I removed it because it doesn't add any value over having the logging framework just enable/disable TRACE. The effect is the same.

**Comment by skjolber** [comment]
I understand you viewpoint, both approaches will result in the statement being printed. But the perception of request-/response-logging might differ from the classic `trace` level, in some apps the right value might be `info`. 

Image I've got an app with a lot of trace messages, most of which adds low informational value, and request-/response-logging. So I go to the log accumulation tool and it just lets me set a minimum level. So then it is not possible to get the request-/response statements without those other trace messages.

**Comment by wulfcolin** [comment]
Exactly my point. I don't want it be logged as `trace` but `info`.

**Comment by whiskeysierra** [comment]
> and it just lets me set a minimum level

Sounds like the problem to me 😜 

Jokes aside, how do you deal with this issue with other libraries? I have not seen any library or framework out there that allows to configure the log level they are using to log messages.

We're just trying to reinvent what good logging frameworks should already give you anyway.

Side note: Request/response logging is all about tracing calls within your system, i.e. TRACE is by far the most logical level to use.

**Comment by wulfcolin** [comment]
> Side note: Request/response logging is all about tracing calls within your system, i.e. TRACE is by far the most logical level to use.
Sometimes you need information about which calls go into your system, but it doesn't have to be as detailed (e.g. body can be omitted, when running on `info` and added when running on `trace`).

**Comment by skjolber** [comment]
A quick google and I found CXF logging at INFO, fegin logging at DEBUG. Some libraries seem to check which log level is enabled, and include more or less details based on that. I guess the issue here is that the correct log level for request-/response-logging is not universially agreed upon.

**Comment by whiskeysierra** [comment]
My argument was solely based on the implied semantics of the levels, given their name. Tracing traditionally refers to very detailed inspection of entry and exit points, e.g. functions or procedures.

**Comment by whiskeysierra** [comment]
> A quick google and I found CXF logging at INFO, fegin logging at DEBUG. Some libraries seem to check which log level is enabled, and include more or less details based on that. I guess the issue here is that the correct log level for request-/response-logging is not universially agreed upon.

And nobody makes it configurable, or do they?

**Comment by skjolber** [comment]
CXF and Fegin it seems not, but in addition to the other arguments, you could argue that all request-response-logging should be on the same level. And that level is not known in advance, aparently. 

I see the lack of log-level customization elsewhere is more like a change for Logbook to shine, the use-case is fair.

**Comment by whiskeysierra** [comment]
> But passing in `HttpLogWriter` is probably not the best approach (?), as it supports just a single argumet, and we're adding two sibling fields to the log statement (the String `message` and the Marker `http`).

Since this was the answer to the original issue, I'll close it now.
We can continue the log level discussion here or create a new issue to track it.
