### ISSUE TITLE
Provide ability to enable/disable Logbook in runtime

### ISSUE THREAD

**Issue by patkovskyi** [zalando/logbook#845]
## Detailed Description
My team would like to have a way to enable/disable Logbook in runtime.

## Context
We'd like to use ZooKeeper for the dynamic reconfiguration of our app.
Quickly disabling access log might be necessary for performance or privacy reasons.

## Possible Implementation
Not sure. 
Expose enable() / disable() methods on Logbook object? 
Expose reconfigure() which would return a new builder()?

## Your Environment
* Version used: 2.2.0
* Link to your project: proprietary

**Comment by whiskeysierra** [comment]
There are already two features that allow you to do that:

1. `Sink#isActive` and `HttpLogWriter#isActive`
    If you use the `DefaultSink` and the `DefaultHttpLogWriter` then `isActive` delegates to the underlying `Logger` and checks whether the TRACE level is being activated. Most logging frameworks allow you to change log levels at runtime.
    In case you have a custom `Sink` implementation, you need to override `isActive` by hand.
2. [Custom condition](https://github.com/zalando/logbook#conditional)
    A custom supplied condition (just a `Predicate`) is used for each request to determine whether logging is done or not. You can have one that has e.g. an `AtomicBoolean` inside that you can toggle, if needed.
