### ISSUE TITLE
Provide function in JSON Body filter to obfuscate values rather than replacing completely.

### ISSUE THREAD

**Issue by dnandola-wyze** [zalando/logbook#851]
I need a mechanism where I can hash the values in JSON body rather than replace them completely with "XXX". One way of doing that is to provide a function in JSONBodyFilters like:

@API(status = EXPERIMENTAL)
    public static BodyFilter replaceJsonStringProperty(
            final Predicate<String> predicate, final Function<String, String> replacement) {

        return replaceStringFunction(predicate, replacement);
    }

I can submit a PR for this and have the code ready (but unable to push a new branch upstream).

**Comment by whiskeysierra** [comment]
> I can submit a PR for this and have the code ready

Great!

> but unable to push a new branch upstream

You need to create a fork and push your branch there.
