### ISSUE TITLE
Have a method in JSONBodyFilter to provide a replacement function apart from replacement string

### ISSUE THREAD

**Issue by dnandola-wyze** [zalando/logbook#852]
I need a mechanism where I can hash the values of specific keys JSON body rather than replace them completely with "XXX". One way of doing that is to provide a function in JSONBodyFilters like:

@API(status = EXPERIMENTAL)
    public static BodyFilter replaceJsonStringProperty(
            final Predicate<String> predicate, final Function<String, String> replacement) {

        return replaceStringFunction(predicate, replacement);
    }

I can submit a PR for this and have the code ready but don't have access rights to submit a PR.

**Comment by whiskeysierra** [comment]
Released as 2.3.0 to central just now. Thanks for your contribution! 🎉 🤝
