### ISSUE TITLE
using logbook with spring boot zuul as gateway

### ISSUE THREAD

**Issue by wubin1989** [zalando/logbook#857]
## Description

Our project uses spring boot zuul as gateway. 
We are using logbook to log request and response at gateway, but when the gateway redirects request, it will lost request body.

## Expected Behavior

When gateway redirects requests, it will carry request body.

## Actual Behavior

Missing request body

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Link to your project:

**Comment by whiskeysierra** [comment]
Steps to reproduce or a sample project or even better a falling test case
as a pr would be needed.
