### ISSUE TITLE
Allow inheritance across the library

### ISSUE THREAD

**Issue by rjmveloso** [zalando/logbook#869]
Is there any reason behind the usage of final's all across the library?

I'm currently using logbook with a requirement to change the position http headers are presented using FastJsonHttpLogFormatter.
It was not possible to inherit from it and customize the prepare methods to handle headers the way we need.
The way it was achieved was mostly copy-paste the code of the formatter and adpapt.

In fact I really don't understand the point of marking a bunch of classes as final. Is it possible to open a little bit more the library?

Cheers, good job.

**Comment by whiskeysierra** [comment]
We're are favouring composition over inheritance. There is nothing that you
can't do with composition. Inheritance has too many downsides.

**Comment by rjmveloso** [comment]
IMHO I would let developers to decide.
Nevertheless, FastJsonHttpLogFormatter is not prepared to apply any change, neither by composition or inheritance. You cannot, for instance, change the order of headers.

**Comment by whiskeysierra** [comment]
Is that just an example or something you really want to do? Why would the
order of headers be important?

**Comment by rjmveloso** [comment]
It was a requirement by the business line to adapt to a logging system.
Of course we achieved what was required, and keeping logbook, but with copy-paste and adaptation to our needs.

**Comment by whiskeysierra** [comment]
> Nevertheless, FastJsonHttpLogFormatter is not prepared to apply any change, neither by composition or inheritance.

I'm more than happy to accept PRs. Such features are usually based on demand and nobody seemed to have needed and contributed it by now.

**Comment by whiskeysierra** [comment]
> IMHO I would let developers to decide.

Why? It increases the maintenance effort because I'd then have to govern a significantly bigger API surface.
Designing for inheritance is tricky and it's really easy to introduce breaking changes.
I don't see any value that inheritance provides, so it's just not worth my effort.

**Comment by rjmveloso** [comment]
Sorry for the late reply.
I understand your idea, I accept it, and in fact I have contributed with my need following the same principle.
However, if you are developing (and well) against a contract (interface), exposing only public methods, and not protected ones because you are not allowing inheritance, I don't see what breaking changes can be introduced. I mean, any major change would lead to a change in the library version.

**Comment by whiskeysierra** [comment]
In case you have it at hand, I strongly encourage you (and everyone else for that matter) to read *Effective Java by Joshua Bloch, Item 16: Favor composition over inheritance*. I can't explain it better than @jbloch.
