### ISSUE TITLE
Remove dependency on core

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/logbook#87]
Both logbook-servlet and logbook-httpclient depend on logbook-core, but they really should only depend on logbook-api.

**Comment by whiskeysierra** [comment]
Not sure if this is really the case. I'll close it for now, but I may look at it later again.

**Comment by AlexanderYastrebov** [comment]
Should they eventually become 4 projects versioned separately?

**Comment by whiskeysierra** [comment]
No, but it doesn't make sense to have a direct dependency to core if we really only need api (since we have it now).

**Comment by whiskeysierra** [comment]
Fixed by #91
