### ISSUE TITLE
ResponseFilter to skip body logging only for certain URLs

### ISSUE THREAD

**Issue by thestral1337** [zalando/logbook#875]
I want to skip the logging of the body response for certain URLs, but using a ResponseFilter I don't have any information about the request into the HttpResponse object. Am I missing something? Wouldn't it be better for the object HttpResponse to carry the relative HttpRequest that originated it?
Is there any workaround I can use?

> .responseFilter(new ResponseFilter() {
> 					@Override public HttpResponse filter(HttpResponse response) {
> 						//Filter only specific responses by URL
> 						return response.withoutBody();
> 					}
> 				})

**Comment by whiskeysierra** [comment]
A custom `Strategy` gives you both, the request and the response, to do that. See e.g.

https://github.com/zalando/logbook/blob/02ad199aab98cd787037b22cdcaa38306e7945f3/logbook-core/src/main/java/org/zalando/logbook/WithoutBodyStrategy.java#L15-L18
