### ISSUE TITLE
Logbook Netty - Keep-Alive Connections -  Logs not printed for all server and client requests.

### ISSUE THREAD

**Issue by PraneshSoma** [zalando/logbook#884]
Logs not printed for all server and client requests.

## Description
For keep-alive connections, Sequence(Linked List) member variable in LogbookServerHandler and LogbookClientHandler in package 'org.zalando.logbook.netty' is not initialized from second request onwards.

## Expected Behavior
Sequence(Linked List) should be initialized for every request.
Logs for **all the inbound and outbound** requests and responses should be printed  

## Actual Behavior
Sequence(Linked List) is not getting initialized for every request.
Logs for only the **first inbound and outbound** requests and response is printed  

## Possible Fix
 Sequence Member variable has to be initialized inside the first function (i.e. ChannelRead in LogbookServerHandler and ChannelWrite in LogbookClientHandler). I will raise a PR for this issue.

## Steps to Reproduce
1. Clone the repo - https://github.com/PraneshSoma/micronaut-logbook
2. Start the Application.
3. Fire two requests from the below postman collection - 
https://www.getpostman.com/collections/002b75f4175a43980ef8
4. Below log will be printed in the console once instead of two.

******************************************************************************
http://localhost:8080/product/PROD-003 , GET,{"id":"PROD-003","name":"Hand Tools","price":6.28}
******************************************************************************

## Context
Attempted to log all the inbound and out request response pairs in a log file however only first request and response pair is logged.

## Your Environment

* Version used: Java 11
* Link to your project: https://github.com/PraneshSoma/micronaut-logbook

**Comment by PraneshSoma** [comment]
@whiskeysierra : Please review the below PR and let me know your feedback 
https://github.com/PraneshSoma/logbook/pull/2.

I couldn't simulate the keep alive connection in the unit test. If you can guide\give pointers, i can add them.
Note : I have validated this change in my local and it's perfectly working for keep alive connections.

**Comment by whiskeysierra** [comment]
> I couldn't simulate the keep alive connection in the unit test.

Shouldn't it be enough to have a test that sends and receives two HTTP requests and responses respectively?

**Comment by PraneshSoma** [comment]
I tried the below in a test and there was no luck. DisposableServer is not behaving the same way as the netty server when consecutive requests have "Connection", "keep-alive" header. (Persistent connection is not created)

```    @Test
    void shouldLogRequestWithBody() throws IOException {
        
        client.headers(httpHeaders -> {
                    httpHeaders.add("Connection", "keep-alive"); })
                .post()
                .uri("/discard")
                .send(helloWorld())
                .response()
                .block();

        client.headers(httpHeaders -> {
            httpHeaders.add("Connection", "keep-alive"); })
                .post()
                .uri("/discard")
                .send(helloWorld())
                .response()
                .block();```

**Comment by whiskeysierra** [comment]
> DisposableServer is not behaving the same way as the netty server when consecutive requests have "Connection", "keep-alive" header. (Persistent connection is not created)
> 
> ```
> 
> ```

Aren't we just using the default Ractor Netty HTTP server in the test?

**Comment by whiskeysierra** [comment]
I wrote a small test and tried to skip through it with a debugger. It does evaluate keep-alive and manages persistent connections, but I believe it has something to do with our test setup. Not sure what exactly. I also couldn't find a setting to control the maximum connection timeout. Maybe it's too low?

**Comment by PraneshSoma** [comment]
i also will research on what happening with the test server.

**Comment by arunapi** [comment]
Created a [project](https://github.com/arunapi/micronaut-logbook-example) with [keep-alive tests(HelloControllerKeepAliveSpec.groovy)](https://github.com/arunapi/micronaut-logbook-example/blob/main/src/test/groovy/micronaut/logbook/example/HelloControllerKeepAliveSpec.groovy) to reproduce the issue.

You can see that the second request from the test is not logged by logbook.

**Comment by arunapi** [comment]
As per the docs of [ChannelHandler](https://netty.io/4.0/api/io/netty/channel/ChannelHandler.html) the Handler instance is dedicated to a connection.
It looks like the Sequence object in the LogbookServerHandler is shared for the connection. It can no longer log the requests since for any subsequent requests the value of variable next will never match 0 or 1

**Comment by whiskeysierra** [comment]
@arunapi Thanks for that. Ideally we would have that as a Java/JUnit 5 within Logbook to prevent future regressions.

**Comment by adamkobor** [comment]
Hi there, we are facing the same issue in our setup. What's the missing step to finalize this PR? Maybe I could give a hand to speed things up :)

**Comment by whiskeysierra** [comment]
We're missing a reliable test to be safe against regressions in the future.

**Comment by jaecktec** [comment]
To work around this issue I wrote myself this thing: 

```
class ThreadSavingHandler(
  private val nonThreadSaveHandler: () -> ChannelDuplexHandler,
) : ChannelDuplexHandler() {

  private var handler: ChannelDuplexHandler = nonThreadSaveHandler()
  private val writtenAttribute = AttributeKey.newInstance<Boolean>("written")

  override fun write(ctx: ChannelHandlerContext, msg: Any?, promise: ChannelPromise?) {
    handler.write(ctx, msg, promise)
    val attr = ctx.channel().attr(writtenAttribute)
    attr.set(true)
  }

  override fun channelRead(ctx: ChannelHandlerContext, msg: Any) {
    val attr = ctx.channel().attr(writtenAttribute)
    attr.setIfAbsent(false)
    if(attr.get()){
      handler = nonThreadSaveHandler()
      attr.set(false)
    }
    handler.channelRead(ctx, msg)
  }
}
```

Instead or working with scoped variables the ctx.channel() should be used
