### ISSUE TITLE
Separate host/path from uri 

### ISSUE THREAD

**Issue by nhomble** [zalando/logbook#915]
```StructuredHttpLogFormatter``` sets ```content.put("uri", request.getRequestUri())``` and I think this should be broken down.

## Context

When I am searching through logs in some log monitor like splunk, I find it helpful to separate larger strings like this for simpler searches. If I am doing searches across nonprod environments, the host may be different so instead of doing
```uri=*/some/path```
I can just do
```path=/some/path```

Also in cases of client side load balancing, I might be interested to see how we are distributed across hosts.
```search path=/some/api | stats count by host```

## Possible Implementation
I suggest we separate the two into different k/v pairs. 
```java
content.put("host", request.getHost());
content.put("path", request.getPath());
```
For backwards compatibility, we could keep the redundant ```uri``` field.

## Your Environment

No bug, just writing a spring boot web service. We can always write a custom implementation and extend ```prepare()``` if needed.

**Comment by nhomble** [comment]
@whiskeysierra for the query param parsing, is there a preference for picking some third party lib into `logbook-api` or do we want to rely on the underlying http lib in each sibling module? 

If I had to imagine the rationale for your original reasoning for keeping the `QueryFilter` based off of a `String`, library consumers can always implement their own filter and utilize their http lib to parse the query string. Similarly, library consumers could implement `StructuredHttpLogFormatter` and add query params.

**Comment by whiskeysierra** [comment]
Multiple reasons, actually:
- there is no official RFC that actually specifies query parameters
- Logbook's primary purpose is to log requests "as-is", with as little transformation as possible
- minimal dependencies
- no desire to implement **and maintain** a custom implementation

**Comment by nhomble** [comment]
Yeah that makes sense to me. Then I think we agree that supporting query params as suggested in the pr won't be implemented? 

Ppl who need it can implement the interfaces as I mentioned above

**Comment by whiskeysierra** [comment]
> Then I think we agree that supporting query params as suggested in the pr won't be implemented?

Yes 👍
