### ISSUE TITLE
java.io.IOException: Stream closed on GetMapping

### ISSUE THREAD

**Issue by softwareDome** [zalando/logbook#936]
Endpoints on Sprint RestControllers are throws an IOException (Stream closed) due missing a RequestBody to stream. Mostly the Exception occured is there nothing or always read from HttpRequest.

## Description
Controller Annotations
"@RestController"
"@GetMapping" with any value
application.yml:
> - logbook:
> - include:
> - - /<any-path>
> - filter.enabled: true
> - format.style: http
> - strategy: body-only-if-status-at-least
> - minimum-status: 200

## Expected Behavior

No Exception and payload logging as well.

## Actual Behavior

see description

## Possible Fix

Workarounds:
- use default strategy  - remove body-only-if-status-at-least
- use @RequestBody
- create own Logbook programatically

## Steps to Reproduce

https://github.com/softwareDome/logbook-test

## Context

n/a

## Your Environment

•	Spring Boot: 2.3.5-RELEASE
•	Zalando LogBook: 2.4.1
	
Maven home: apache-maven-3.6.3
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by whiskeysierra** [comment]
I can't say that I really understand this. Does the problem go away when you remove logbook? Why would you need a request body for a get request? Can you provide a test case or sample to reproduce it?

**Comment by softwareDome** [comment]
Hi Willi,
greetings to Berlin from Bavaria :)
a) The issue goes away without logbook. 
b) The request body is just a workaround to fix it.
c) there is a sample project: https://github.com/softwareDome/logbook-test

**Comment by whiskeysierra** [comment]
Hi! Thanks for the sample project. If I checkout the current HEAD (https://github.com/softwareDome/logbook-test/commit/2d1f052038b1ebafdf02e432119fc0306c1e7480), what is the sequence of steps to reproduce it?

I tried:

```bash
mvn spring-boot:run
# in separate terminal
http :8080/justdoit identifier==Willi
```

Response looks good. Traffic is not logged. Should it? Or should it already fail?

**Comment by whiskeysierra** [comment]
I just realized that the logging configuration sends logbook traffic to a file. But I can't find it.

**Comment by softwareDome** [comment]
hmm,
2021-01-25 14:14:41.197 ERROR[logbook-test] [-nio-8080-exec-1] .c.c.C.[.[.[.[dispatcherServlet]: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.io.IOException: Stream closed
	at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:359)
	at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:132)
	at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:110)
	at org.zalando.logbook.servlet.ByteStreams.copy(ByteStreams.java:26)
	at org.zalando.logbook.servlet.ByteStreams.toByteArray(ByteStreams.java:17)

**Comment by softwareDome** [comment]
from the console just now

**Comment by whiskeysierra** [comment]
That happens if you checkout your sample and just run it  and execute a GET request?

**Comment by softwareDome** [comment]
> That happens if you checkout your sample and just run it and execute a GET request?

yes of course

**Comment by whiskeysierra** [comment]
Interesting. I can't reproduce it. If I execute the steps outlined in https://github.com/zalando/logbook/issues/936#issuecomment-766798485 I don't see exceptions nor request/response logs.

For reference:

```
$ java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.9.1, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"

$ http --version
2.3.0
```

**Comment by softwareDome** [comment]
There was a typo in the resources directory name therefore the spring boot application isnt packaged in a right manner.

Sorry about this, i've marked the directory in my IDE as resources root.

Please git pull the test-project from github again.
