### ISSUE TITLE
Provide a way to enable partial logging of traffic

### ISSUE THREAD

**Issue by zauli-github** [zalando/logbook#938]
Hi, 
as i can see from your docs, there's a rigid rules that states:
_Requests/responses are logged as a pair or not logged at all._
Is there a way to overcome this rule?
I can't see it on the docs.

I think it can be useful for long-process requests, where, for any reasons, can be multiple reasons for the server to goes down. Am i wrong?

**Comment by whiskeysierra** [comment]
You're quoting the https://github.com/zalando/logbook#strategy paragraph, if I'm not mistaken. That one starts with:

> Logbook **used to have** a very rigid strategy

It continues to read:

> Starting with version 2.0 Logbook now comes with a Strategy pattern at its core. Make sure you read the documentation of the Strategy interface to understand the implications.

>  Is there a way to overcome this rule?

Yes, implement and register your own `Strategy` 😉

**Comment by zauli-github** [comment]
Hi,
thanks for the quick response.
So with my Strategy implementation i can provide the partial logging of traffic.
From the Strategy documentation, ( well, i'm reading the class' comments ), the way to achieve this, seems to log inside the _HttpRequest process(final HttpRequest request)_ method.

From the docs on the other methods, it seems that the log can occur "too late", i.e. _right before_ the response / response body has been buffered. Am i wrong?

**Comment by whiskeysierra** [comment]
> From the Strategy documentation, ( well, i'm reading the class' comments ), the way to achieve this, seems to log inside the _HttpRequest process(final HttpRequest request)_ method.

No, the `process` methods are just for processing the request/response, usually that's the place where you decide whether to include the body or not. Writing is done in the `write` methods.

> _Requests/responses are logged as a pair or not logged at all._
> Is there a way to overcome this rule?
> I can't see it on the docs.
> 
> I think it can be useful for long-process requests, where, for any reasons, can be multiple reasons for the server to goes down. Am i wrong?

Just to be clear, requests/responses being logged in pairs doesn't mean that we delay logging of requests until the response is done. It just means that, by default, you will always get both or none. A custom strategy is useful if you want partial logging, e.g. requests only or response only or any kind of conditional like request only if response failed.

If what you're interested in is just that requests are logged as early as possible, then you don't have to do anything. That's the default behavior.

**Comment by zauli-github** [comment]
Sorry for the late, i was interest to log request as early as possible so, I will implement a custom strategy. Thank you for the quick responses!
