### ISSUE TITLE
Empty or truncated servlet http response on async request  

### ISSUE THREAD

**Issue by nobo728x** [zalando/logbook#954]
servlet http reponse is empty or truncated

## Description
The bug is in org.zalando.logbook.servlet.LogbookFilter that assumes that if request.getDispatcherType() == ASYNC implies request.isAsyncStarted() but it's not the case, because the code after the filter (graphql servlet in my case) can start the async context and because of this the reponse is never flushed.

## Expected Behavior
Http response as writed by the servlet 

## Actual Behavior
empty http reponse

## Possible Fix
I will try the fix it 

## Steps to Reproduce
I wrote a unit test shouldResponseNotEmptyAsync (whitch fails) 
https://github.com/nobo728x/logbook/blob/main/logbook-servlet/src/test/java/org/zalando/logbook/servlet/AsyncDispatchTest.java#L114

## Context
spring-boot + graphql-java application 

## Your Environment
* Version 2.5.0 (2.4.X are affected)

**Comment by PascalSchumacher** [comment]
I guess this issue should be closed, as it was fixed with #954 and released with `2.6.2`?
