### ISSUE TITLE
Order of fields in json log format

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/logbook#96]
As a log reader 
I want to see important info closer to beginning of the log line
So it is easier for me to debug

For json formatter current order of fields is following:

Request:

    type
    correlation
    remote
    method
    uri
    headers
    body

Response:

    type
    correlation
    status
    headers
    body

Proposed change is to have order:

Request:

    type
    correlation
    method
    uri
    body
    headers
    remote

Response:

    type
    correlation
    status
    body
    headers

**Comment by lukasniemeier-zalando** [comment]
While I agree on moving remote I do not agree on moving the headers. Therefore - what about rephrasing this in a way that the JsonFormatter supports whatever ordering demanded?

**Comment by AlexanderYastrebov** [comment]
@lukasniemeier-zalando why dont you want to move headers?

**Comment by jhorstmann** [comment]
For me the current order makes sense, as it corresponds to the order the data has on the wire (with remote being on the tcp level).

For better readability during debugging there already is the `DefaultHttpLogFormatter`.
