### ISSUE TITLE
Unable to read request body from ServletRequest because InputStream is not cached anymore with latest version

### ISSUE THREAD

**Issue by mutyasaisrikar** [zalando/logbook#974]
I have a Spring interceptor where I have to read the request body in my application. I also use logbook to log request and response in custom format.

I was previously using 1.13.0 version of logbook. After migrating to latest version 2.6.0, I am able to read the request body in my Spring interceptor but it is failing at `@RequestBody` annotation in Spring Controller class

## Expected Behavior
https://github.com/mutyasaisrikar/logbook-success

I have added a test case where I am able to read my request body in interceptor

## Actual Behavior
https://github.com/mutyasaisrikar/logbook-error

The same behaviour is not working with latest version of zalando

**Comment by mutyasaisrikar** [comment]
@whiskeysierra, Can you please tell me If I am missing something as this is blocking our changes

**Comment by whiskeysierra** [comment]
Thanks for your effort, especially having two repositories is great for investigating! 

A first brief look didn't reveal anything obvious. I don't have time digging into this at the moment. If I were you I'd try to inspect both projects with a debugger to see the internals of Logbook at runtime. 1.x to 2.x was a pretty big rewrite, so comparing source code will most likely not help.
