### ISSUE TITLE
how to record request and response at the same line ?

### ISSUE THREAD

**Issue by efgod** [zalando/logbook#987]
## Your Environment

* Version used:
* Link to your project:

**Comment by whiskeysierra** [comment]
See https://github.com/zalando/logbook#strategy
 
In a nutshell:
- Custom `Strategy` implementation
  - Implement `write(Precorrelation, HttpRequest, Sink)` with an empty method body (won't log the request)
  - Implement `write(Correlation, HttpRequest, HttpResponse, Sink)` by calling `sink.writeBoth(correlation, request, response)`
- Custom `Sink` implementation
  - Implement `write(Correlation, HttpRequest, HttpResponse)` as you like, e.g. by reusing the `DefaultHttpLogFormatter` to produce two strings, concat them and then delegate to `DefaultHttpLogWriter`
