### ISSUE TITLE
Is there anyway to put a condition based on the Response instead of the Request?

### ISSUE THREAD

**Issue by benze** [zalando/logbook#990]
I'd like to use Logbook to dump the complete request/response, in the case where my response is a 4xx or 5xx message.  This will allow me to debug exactly what request generated the response that the application producing.

Similarly, as an Http client, I would like to dump the full request I'm sending out if my upstream service returns a 500; it will help me debug the problem I am having with the upstream service.

At the moment, all I see is a Predicate that I can build based on the `HttpRequest` object.  Is there anything I can do to have LogBook cache the Request and wait for the response, and if the condition is true, then dump both?

Thanks,

Eric

**Comment by whiskeysierra** [comment]
See https://github.com/zalando/logbook#strategy. What you describe is pretty much exactly what `StatusAtLeastStrategy` is doing:

https://github.com/zalando/logbook/blob/bfbb1506e7a533d202fdbdd1475a7225b04117ab/logbook-core/src/test/java/org/zalando/logbook/StatusAtLeastStrategyTest.java#L22-L25
