### ISSUE TITLE
HttpLogWriter take log level as configuration

### ISSUE THREAD

**Issue by nhomble** [zalando/logbook#999]
Allow developers to pick the loglevel without adding new java classes.

## Detailed Description

I'd like to keep `Logbook` configurations just in yml (for spring applications). With the current implementation of the writer, I have to write my own class in order to change the level. 

## Context

`Logbook` is just configured through `application.yml`

## Possible Implementation

I recommend we do a couple of things:
1. enhance `LogbookProperties` with a new property.. maybe `logbook.write.default-log-level`
2.  enhance `LogbookAutoConfiguration` and autowire the properties into the `writer()` bean method and allow devs to externally configure the log level. Hopefully we can avoid a switch-case..

**Comment by whiskeysierra** [comment]
We used to have that, but removed it because it didn't really serve a purpose. What's your use case/requirement to change the log level?

**Comment by nhomble** [comment]
It's definitely a preference (so keeping at `TRACE` by default is fine, but lemme override like most spring configurations :))

fwiw spring likes [debug level](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/filter/CommonsRequestLoggingFilter.java#L39)

**Comment by whiskeysierra** [comment]
> but lemme override like most spring configurations :))

Well, Spring itself doesn't let you customize it (as per your link). You could implement your own `HttpLogWriter`, if it's really urgent though.
